USE STUDENTDB;                                                #COUNT()
SELECT COUNT(*) AS TOTAL_STUDENTS 
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT COUNT(*) AS TOTAL_EMPLOYEES 
FROM EMPLOYEES;

USE HOSPITALDB;
SELECT COUNT(*) AS TOTAL_PATIENTS 
FROM PATIENTS;

USE LIBRARYDB;
SELECT COUNT(*) AS TOTAL_BOOKS
FROM BOOKS;

USE SHOPPINGDB;
SELECT COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS;

USE COURSEDB;
SELECT COUNT(*) AS TOTAL_COURSES
FROM COURSES;

USE ECOMMERCEDB;
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;

USE STUDENTDB;                                           
SELECT COUNT(*) AS TOTAL_STUDENTS_IN_BBA 
FROM STUDENTS
WHERE DEPARTMENT='BBA';

USE EMPLOYEEDB;
SELECT COUNT(*) AS TOTAL_EMPLOYEES_IN_IT
FROM EMPLOYEES
WHERE DEPARTMENT='IT';

USE HOSPITALDB;
SELECT COUNT(*) AS TOTAL_PATIENTS_WITH_NULL_DISEASE 
FROM PATIENTS
WHERE DISEASE IS NULL;

USE LIBRARYDB;
SELECT COUNT(*) AS TOTAL_BOOKS_IN_TECHNOLOGY
FROM BOOKS
WHERE CATEGORY='TECHNOLOGY';

USE SHOPPINGDB;
SELECT COUNT(*) AS TOTAL_PRODUCTS_IN_ELECTRONICS
FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS';

USE STUDENTDB;                                           
SELECT COUNT(*) AS STUDENTS_AGED_ABOVE_20
FROM STUDENTS
WHERE AGE>20;

USE EMPLOYEEDB;
SELECT COUNT(*) AS EMPLOYEES_WITH_SALARY_MORE_THAN_50000
FROM EMPLOYEES
WHERE SALARY>50000.00;

USE SHOPPINGDB;
SELECT COUNT(*) AS PRODUCTS_WITH_PRICE_BETWEEN_10K_50K
FROM PRODUCTS
WHERE PRICE BETWEEN 10000.00 AND 50000.00;

USE ECOMMERCEDB;
SELECT COUNT(*) AS CUSTOMERS_FROM_CHENNAI
FROM CUSTOMERS
WHERE CITY='CHENNAI';

USE STUDENTDB;                                           
SELECT COUNT(*) AS STUDENTS_WITH_NO_EMAIL
FROM STUDENTS
WHERE EMAIL IS NULL;

USE EMPLOYEEDB;
SELECT COUNT(*) AS EMPLOYEES_WITH_NO_EMAIL
FROM EMPLOYEES
WHERE EMAIL IS NULL;

USE STUDENTDB;                                           
SELECT COUNT(DISTINCT DEPARTMENT) AS TOTAL_DEPARTMENTS
FROM STUDENTS;

USE SHOPPINGDB;
SELECT COUNT(DISTINCT BRAND) AS TOTAL_BRANDS
FROM PRODUCTS;





USE EMPLOYEEDB;                                            #SUM()
SELECT SUM(SALARY) AS TOTAL_SALARY_PAID_ALL_EMPLOYEES
FROM EMPLOYEES;

SELECT SUM(SALARY) AS TOTAL_SALARY_PAID_FOR_IT_DEPARTMENT
FROM EMPLOYEES
WHERE DEPARTMENT='IT';

USE LIBRARYDB;
SELECT SUM(QUANTITY) AS TOTAL_QUANTITY_OF_ALL_BOOKS
FROM BOOKS;

USE SHOPPINGDB;
SELECT SUM(AVAILABLESTOCK) AS TOTAL_STOCK_AVAILABLE
FROM PRODUCTS;

SELECT SUM(PRICE) AS TOTAL_PRICE_OF_ALL_PRODUCTS
FROM PRODUCTS;

USE COURSEDB;
SELECT SUM(FEES) AS TOTAL_FEES_OF_ALL_COURSES
FROM COURSES;

USE EMPLOYEEDB;
SELECT SUM(SALARY) AS TOTAL_SALARY_OF_EMPLOYEES_WITH_SALARY_GREATER_THAN_40000
FROM EMPLOYEES
WHERE SALARY>40000.00;

USE SHOPPINGDB;
SELECT SUM(PRICE) AS TOTAL_PRICE_OF_PRODUCTS_IN_ELECTRONICS
FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS';

USE LIBRARYDB;
SELECT SUM(QUANTITY) AS QUANTITY_OF_BOOKS_IN_TECHNOLOGY
FROM BOOKS
WHERE CATEGORY='TECHNOLOGY';

USE SHOPPINGDB;
SELECT SUM(AVAILABLESTOCK) AS QUANTITY_OF_PRODUCTS_IN_SAMSUNG
FROM PRODUCTS
WHERE BRAND='SAMSUNG';

USE EMPLOYEEDB;
SELECT SUM(SALARY) AS TOTAL_SALARY_PAID_FOR_HR
FROM EMPLOYEES
WHERE DESIGNATION='HR';

USE COURSEDB;
SELECT SUM(FEES) AS FEES_FOR_CSE
FROM COURSES
WHERE DEPARTMENT='CSE';


USE SHOPPINGDB;
SELECT SUM(AVAILABLESTOCK) AS QUANTITY_OF_PRODUCTS_WITH_PRICE_GREATER_THAN_10000
FROM PRODUCTS
WHERE PRICE>10000.00;

USE EMPLOYEEDB;
SELECT SUM(SALARY) AS SALARY_OF_EMPLOYEES_AGED_MORE_THAN_30
FROM EMPLOYEES
WHERE AGE>30;

USE LIBRARYDB;
SELECT SUM(PRICE) AS PRICE_OF_BOOKS_IN_TECHNOLOGY
FROM BOOKS
WHERE CATEGORY='TECHNOLOGY';

USE SHOPPINGDB;
SELECT SUM(AVAILABLESTOCK) AS QUANTITY_OF_PRODUCTS_GREATER_THAN_10
FROM PRODUCTS
WHERE AVAILABLESTOCK>10;

USE EMPLOYEEDB;
SELECT SUM(SALARY) AS SALARY_OF_DEVELOPER
FROM EMPLOYEES
WHERE DESIGNATION='DEVELOPER';

USE COURSEDB;
SELECT SUM(FEES) AS FEES_FOR_6_MONTH_COURSES
FROM COURSES
WHERE DURATION='6 MONTHS';

USE LIBRARYDB;
SELECT SUM(QUANTITY) AS QUANTITY_OF_BOOKS_PRICED_500_1000
FROM BOOKS
WHERE PRICE BETWEEN 500.00 AND 1000.00;

USE SHOPPINGDB;
SELECT SUM(AVAILABLESTOCK) AS QUANTITY_OF_PRODUCTS_IN_ELECTRONICS
FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS';




USE EMPLOYEEDB;                                               #MIN()
SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES;

SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT';

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE = (SELECT MIN(PRICE) 
FROM BOOKS);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE = (SELECT MIN(PRICE) 
FROM PRODUCTS);

USE COURSEDB;
SELECT MIN(FEES) AS LOWEST_FEE_COURSE
FROM COURSES;

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE AGE = (SELECT MIN(AGE) 
FROM STUDENTS);

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE = (SELECT MIN(AGE) 
FROM PATIENTS);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE QUANTITY= (SELECT MIN(QUANTITY) 
FROM BOOKS);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE AVAILABLESTOCK= (SELECT MIN(AVAILABLESTOCK) 
FROM PRODUCTS);

USE EMPLOYEEDB;                                              
SELECT * FROM EMPLOYEES 
WHERE SALARY =(SELECT MIN(SALARY) 
FROM EMPLOYEES
WHERE DEPARTMENT = 'SALES');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE = (SELECT MIN(PRICE) 
FROM BOOKS
WHERE CATEGORY='TECHNOLOGY');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MIN(PRICE) 
FROM PRODUCTS
WHERE CATEGORY='PANT');

USE COURSEDB;
SELECT * FROM COURSES 
WHERE DEPARTMENT='CSE' 
AND FEES = (SELECT MIN(FEES) 
FROM COURSES);

USE EMPLOYEEDB;                                              
SELECT * FROM EMPLOYEES 
WHERE SALARY =(SELECT MIN(SALARY) 
FROM EMPLOYEEWHERE DESIGNATION = 'DEVELOPER');

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE DEPARTMENT ='VISCOM'
AND AGE = (SELECT MIN(AGE)
FROM STUDENTS
WHERE DEPARTMENT ='VISCOM');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MIN(PRICE) 
FROM PRODUCTS
WHERE AVAILABLESTOCK>10);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE QUANTITY= (SELECT MIN(QUANTITY) 
FROM BOOKS);

USE EMPLOYEEDB;                                              
SELECT * FROM EMPLOYEES 
WHERE SALARY = (SELECT MIN(SALARY) 
FROM EMPLOYEES
WHERE SALARY>40000.00);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MIN(PRICE) 
FROM PRODUCTS
WHERE BRAND='SAMSUNG');

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING = (SELECT MIN(RATING)
FROM MOVIES);




USE EMPLOYEEDB;                                               #MAX()
SELECT * FROM EMPLOYEES 
WHERE SALARY = (SELECT MAX(SALARY)
FROM EMPLOYEES);

SELECT * FROM EMPLOYEES 
WHERE SALARY = (SELECT MAX(SALARY) 
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE = (SELECT MAX(PRICE) 
FROM BOOKS);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE = (SELECT MAX(PRICE) 
FROM PRODUCTS);

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES = (SELECT MAX(FEES)
FROM COURSES);

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE AGE = (SELECT MAX(AGE) 
FROM STUDENTS);

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE = (SELECT MAX(AGE) 
FROM PATIENTS);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE QUANTITY= (SELECT MAX(QUANTITY) 
FROM BOOKS);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE AVAILABLESTOCK= (SELECT MAX(AVAILABLESTOCK) 
FROM PRODUCTS);

USE EMPLOYEEDB;                                              
SELECT * FROM EMPLOYEES 
WHERE SALARY =(SELECT MAX(SALARY) 
FROM EMPLOYEES
WHERE DEPARTMENT = 'SALES');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE  PRICE = (SELECT MAX(PRICE) 
FROM BOOKS
WHERE CATEGORY='TECHNOLOGY');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MAX(PRICE) 
FROM PRODUCTS
WHERE CATEGORY='PANT');

USE COURSEDB;
SELECT * FROM COURSES 
WHERE FEES = (SELECT MAX(FEES) 
FROM COURSES
WHERE DEPARTMENT='CSE');

USE EMPLOYEEDB;                                              
SELECT * FROM EMPLOYEES 
WHERE SALARY =(SELECT MAX(SALARY) 
FROM EMPLOYEES
WHERE DESIGNATION = 'HR');

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE DEPARTMENT ='VISCOM'
AND AGE = (SELECT MAX(AGE)
FROM STUDENTS
WHERE DEPARTMENT ='VISCOM');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MAX(PRICE) 
FROM PRODUCTS
WHERE AVAILABLESTOCK>10);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE QUANTITY= (SELECT MAX(QUANTITY) 
FROM BOOKS);

USE EMPLOYEEDB;                                              
SELECT * FROM EMPLOYEES 
WHERE SALARY = (SELECT MAX(SALARY) 
FROM EMPLOYEES
WHERE SALARY>40000.00);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MAX(PRICE) 
FROM PRODUCTS
WHERE BRAND='SAMSUNG');

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING = (SELECT MAX(RATING)
FROM MOVIES);




USE EMPLOYEEDB;                                           #AVG()   
SELECT ROUND(AVG(SALARY),2) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY),2) AS AVERAGE_SALARY_IN_IT
FROM EMPLOYEES
WHERE DEPARTMENT='IT';

USE LIBRARYDB;
SELECT ROUND(AVG(PRICE),2) AS AVERAGE_PRICE
FROM BOOKS;

USE SHOPPINGDB;
SELECT ROUND(AVG(PRICE),2) AS AVERAGE_PRICE
FROM PRODUCTS;

USE COURSEDB;
SELECT ROUND(AVG(FEES),2) AS AVERAGE_FEES
FROM COURSES;

USE STUDENTDB;
SELECT ROUND(AVG(AGE)) AS AVERAGE_AGE
FROM STUDENTS;

USE HOSPITALDB;
SELECT ROUND(AVG(AGE)) AS AVERAGE_AGE
FROM PATIENTS;

USE LIBRARYDB;
SELECT ROUND(AVG(QUANTITY)) AS AVERAGE_QUANTITY
FROM BOOKS;

USE SHOPPINGDB;
SELECT ROUND(AVG(AVAILABLESTOCK)) AS AVERAGE_AVAILABLESTOCK
FROM PRODUCTS;

USE EMPLOYEEDB;                                              
SELECT ROUND(AVG(SALARY),2) AS AVERAGE_SALARY_IN_HR
FROM EMPLOYEES
WHERE DEPARTMENT='HR';

USE LIBRARYDB;
SELECT ROUND(AVG(PRICE),2) AS AVERAGE_PRICE_IN_TECHNOLOGY
FROM BOOKS
WHERE CATEGORY='HORROR';

USE COURSEDB;
SELECT ROUND(AVG(FEES),2) AS AVERAGE_FEES_CSE
FROM COURSES
WHERE DEPARTMENT='CSE';

USE EMPLOYEEDB;                                              
SELECT ROUND(AVG(SALARY),2) AS AVERAGE_SALARY_OF_DEVELOPER
FROM EMPLOYEES
WHERE DESIGNATION='DEVELOPER';

USE STUDENTDB;
SELECT ROUND(AVG(AGE)) AS AVERAGE_AGE_OF_BBA_STUDENTS
FROM STUDENTS
WHERE DEPARTMENT='BBA';

USE SHOPPINGDB;
SELECT ROUND(AVG(PRICE),2) AS AVERAGE_PRICE_WITH_STOCK_MORE_THAN_10
FROM PRODUCTS
WHERE AVAILABLESTOCK>10;

USE LIBRARYDB;
SELECT ROUND(AVG(QUANTITY)) AS AVERAGE_QUANTITY
FROM BOOKS
WHERE PRICE BETWEEN 500.00 AND 1000.00;

USE SHOPPINGDB;
SELECT ROUND(AVG(PRICE),2) AS AVERAGE_PRICE_OF_SAMSUNG
FROM PRODUCTS
WHERE BRAND='SAMSUNG';

USE MOVIEDB;
SELECT ROUND(AVG(RATING),2) AS AVERAGE_RATING
FROM MOVIES;