USE STUDENTDB;                        #COLUMN ALIAS
SELECT STUDENTNAME AS STUDENT_NAME FROM STUDENTS;

USE EMPLOYEEDB;                        
SELECT EMPLOYEENAME AS EMPLOYEE_NAME FROM EMPLOYEES;

SELECT SALARY AS MONTHLY_SALARY FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME AS PRODUCT_NAME FROM PRODUCTS;

SELECT PRICE AS PRODUCT_PRICE FROM PRODUCTS;

USE LIBRARYDB;
SELECT TITLE AS BOOK_NAME FROM BOOKS;

USE COURSEDB;
SELECT COURSENAME AS COURSE_NAME FROM COURSES;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME AS CUSTOMER_NAME FROM CUSTOMERS;

USE STUDENTDB;                       
SELECT DEPARTMENT AS DEPARTMENT_NAME FROM STUDENTS;

USE EMPLOYEEDB;                        
SELECT DESIGNATION AS JOB_ROLE FROM EMPLOYEES;

SELECT JOININGDATE AS DATE_OF_JOINING FROM EMPLOYEES;

USE ECOMMERCEDB;
SELECT REGISTEREDDATE AS REGISTERED_DATE FROM CUSTOMERS;

USE SHOPPINGDB;
SELECT AVAILABLESTOCK AS AVAILABLE_STOCK FROM PRODUCTS;

USE COURSEDB;
SELECT FEES AS COURSE_FEES FROM COURSES;

USE STUDENTDB;                       
SELECT EMAIL AS EMAIL_ID FROM STUDENTS;

USE EMPLOYEEDB;                        
SELECT PHONENUMBER AS CONTACT_NUMBER FROM EMPLOYEES;

USE LIBRARYDB;
SELECT AUTHOR AS AUTHOR_NAME FROM BOOKS;

USE SHOPPINGDB;
SELECT BRAND AS BRAND_NAME FROM PRODUCTS;

USE HOSPITALDB;
SELECT BLOODGROUP AS BLOOD_GROUP FROM PATIENTS;

USE MOVIEDB;
SELECT RATING AS MOVIE_RATING FROM MOVIES;




USE EMPLOYEEDB;                           #ALIAS WITH EXPRESSIONS
SELECT EMPLOYEENAME,SALARY,
SALARY*12 AS `ANNUAL_SALARY` FROM EMPLOYEES;

SELECT EMPLOYEENAME,SALARY,
ROUND(SALARY*1.10,2) AS `NCREMENTED_SALARY` 
FROM EMPLOYEES;

SELECT EMPLOYEENAME,SALARY,
ROUND(SALARY-SALARY*5/100,2) AS `NET_SALARY` 
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE*AVAILABLESTOCK AS `TOTAL_VALUE` 
FROM PRODUCTS;

SELECT PRODUCTNAME,PRICE,
ROUND(PRICE-PRICE*10/100,2) AS `DISCOUNTED_PRICE` 
FROM PRODUCTS;

SELECT PRODUCTNAME,BRAND,PRICE,
ROUND(PRICE*1.18,2) AS `FINAL_PRICE` 
FROM PRODUCTS;

USE LIBRARYDB;
SELECT TITLE,PRICE,
ROUND(PRICE-PRICE*20/100,2) AS `DISCOUNTED_PRICE` 
FROM BOOKS;

USE COURSEDB;
SELECT COURSENAME,FEES,
ROUND(FEES-FEES*15/100,2) AS `FINAL_FEES` 
FROM COURSES;

USE STUDENTDB;                       
SELECT STUDENTNAME,AGE,AGE+1 AS AGE_NEXT_YEAR 
FROM STUDENTS;

USE EMPLOYEEDB;                           
SELECT EMPLOYEENAME,SALARY,
SALARY/12 AS `MONTHLY_SALARY` 
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE*AVAILABLESTOCK AS `STOCK_VALUE` 
FROM PRODUCTS;

USE EMPLOYEEDB;                           
SELECT EMPLOYEENAME,SALARY,
SALARY*12*1,10 AS `ANNUAL_SALARY_AFTER_INCREMENT` 
FROM EMPLOYEES;

USE STUDENTDB;                               
SELECT LENGTH(STUDENTNAME) AS NAME_LENGTH 
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT UPPER(EMPLOYEENAME) AS UPPER_NAME 
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT LOWER(PRODUCTNAME) AS `LOWER_PRODUCT_NAME` 
FROM PRODUCTS;

USE STUDENTDB;
SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULL_NAME 
FROM EMPLOYEES;

SELECT EMPLOYEENAME, 
DATE_ADD(JOININGDATE, INTERVAL 126 DAY) AS `FUTURE_DATE`
FROM EMPLOYEES;

SELECT EMPLOYEENAME,
DATE_SUB(JOININGDATE, INTERVAL 42 DAY) AS `PREVIOUS_DATE`
FROM EMPLOYEES;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME, SALARY, 
ABS(SALARY - 5000) AS `SALARY_DIFFERENCE`
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME, ROUND(PRICE,2) AS `ROUNDED_PRICE` 
FROM PRODUCTS;




USE STUDENTDB;                                     #ALIAS WITH AGGREGATE FUNCTION
SELECT COUNT(*) AS TOTAL_STUDENTS
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES;

SELECT MIN(SALARY) AS MINIMUM_SALARY
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT SUM(AVAILABLESTOCK) AS TOTAL_STOCK
FROM PRODUCTS;

SELECT AVG(TPRICE) AS AVERAGE_PRICE
FROM PRODUCTS;

SELECT MAX(PRICE) AS HIGHEST_PRICE
FROM PRODUCTS;

SELECT MIN(PRICE) AS LOWEST_PRICE
FROM PRODUCTS;

USE COURSEDB;
SELECT SUM(FEES) AS TOTAL_COURSE_FEES
FROM COURSES;

SELECT AVG(CFEES) AS AVERAGE_COURSE_FEES
FROM COURSES;

SELECT MAX(FEES) AS MAXIMUM_COURSE_FEE
FROM COURSES;

SELECT MIN(FEES) AS MINIMUM_COURSE_FEE
FROM COURSES;

USE LIBRARYDB;
SELECT SUM(QUANTITY) AS TOTAL_BOOKS
FROM BOOKS;

SELECT AVG(PRICE) AS AVERAGE_BOOK_PRICE
FROM BOOKS;

SELECT MAX(PRICE) AS MAXIMUM_BOOK_PRICE
FROM BOOKS;

SELECT MIN(PRICE) AS MINIMUM_BOOK_PRICE
FROM BOOKS;

USE EMPLOYEEDB;
SELECT COUNT(DISTINCT DEPARTMENT) AS TOTAL_DEPARTMENTS
FROM EMPLOYEES;



USE EMPLOYEEDB;                                      #ALIAS WITH CASE
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=100000.00 THEN 'HIGH'
WHEN SALARY>=50000.00 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENTNAME,MARKS,
CASE WHEN MARKS>=40 THEN 'PASS'
ELSE 'FAIL'
END AS RESULT_STATUS
FROM STUDENTS;

USE SHOPPINGDB;
SELECT PRODUCTNAME,AVAILABLESTOCK,
CASE WHEN STOCK>0 THEN 'IN STOCK'
ELSE 'OUT OF STOCK'
END AS STOCK_STATUS
FROM PRODUCTS;

USE STUDENTDB;
SELECT STUDENTNAME,AGE,
CASE WHEN AGE<18 THEN 'MINOR'
WHEN AGE>=18 THEN 'ADULT'
END AS AGE_CATEGORY
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,EXPERIENCE,
CASE WHEN EXPERIENCE>=10 THEN 'SENIOR'
WHEN EXPERIENCE>=5 THEN 'MID LEVEL'
ELSE 'FRESHER'
END AS EXPERIENCE_LEVEL
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE,
CASE WHEN PRICE>=50000.00 THEN 'EXPENSIVE'
WHEN PRICE>=10000.00 THEN 'AFFORDABLE'
ELSE 'CHEAP'
END AS PRICE_CATEGORY
FROM PRODUCTS;

USE COURSEDB;
SELECT COURSENAME,FEES,
CASE WHEN FEES>=50000.00 THEN 'HIGH'
WHEN FEES>=30000.00 THEN 'MEDIUM'
ELSE 'LOW'
END AS FEE_CATEGORY
FROM COURSES;

USE MOVIEDB;
SELECT TITLE,RATING,
CASE WHEN RATING>=8.0 THEN 'EXCELLENT'
WHEN RATING>=6.0 THEN 'GOOD'
WHEN RATING>=4.0 THEN 'AVERAGE'
ELSE 'FLOP'
END AS RATING_CATEGORY
FROM MOVIES;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,EMAIL,
CASE WHEN EMAIL IS NOT NULL THEN 'AVAILABLE'
ELSE 'NOT AVAILABLE'
END AS EMAIL_STATUS
FROM CUSTOMERS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,EXPERIENCE,
CASE WHEN EXPERIENCE>=5 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS PROMOTION_STATUS
FROM EMPLOYEES;




USE EMPLOYEEDB;                           #TABLE ALIASES
SELECT E.EMPLOYEENAME, E.SALARY
FROM EMPLOYEES AS E;

USE STUDENTDB;
SELECT S.STUDENTNAME, S.DEPARTMENT
FROM STUDENTS AS S;

USE SHOPPINGDB;
SELECT P.PRODUCTNAME, P.PRICE
FROM PRODUCTS AS P;

USE LIBRARYDB;
SELECT B.TITLE, B.PRICE
FROM BOOKS AS B;

USE COURSEDB;
SELECT C.COURSENAME, C.FEES
FROM COURSES AS C;

USE ECOMMERCEDB;
SELECT CU.CUSTOMERNAME, CU.CITY
FROM CUSTOMERS AS CU;

USE EMPLOYEEDB;
SELECT E.EMPLOYEENAME, E.SALARY
FROM EMPLOYEES AS E
WHERE E.SALARY > 50000;

USE SHOPPINGDB;
SELECT P.PRODUCTNAME, P.PRICE
FROM PRODUCTS AS P
WHERE P.PRICE > 10000;

USE EMPLOYEEDB;
#NOT SURE ABOUT QUESTION NUMBER 79 AND 80





USE EMPLOYEEDB;                                   #ADVANCED ALIAS PRACTICE
SELECT EMPLOYEENAME AS EMPLOYEE_NAME,
SALARY AS MONTHLY_SALARY,
SALARY * 12 AS ANNUAL_SALARY
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME AS PRODUCT_NAME,
PRICE AS PRODUCT_PRICE,
AVAILABLESTOCK AS PRODUCT_QUANTITY,
PRICE * AVAILABLESTOCK AS TOTAL_STOCK_VALUE
FROM PRODUCTS;

USE STUDENTDB;
SELECT STUDENTNAME AS STUDENT_NAME,
MARK AS MARKS,
CASE WHEN MARK>=40 THEN 'PASS'
ELSE 'FAIL'
END AS RESULT_STATUS
FROM STUDENTS;

USE COURSEDB;
SELECT COURSENAME AS COURSE_NAME,
FEES AS ORIGINAL_FEES,
FEES - (FEES * 0.10) AS DISCOUNTED_FEES
FROM COURSES;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME AS EMPLOYEE_NAME,
SALARY AS SALARY,
CASE WHEN SALARY>=100000 THEN 'HIGH'
WHEN SALARY>=50000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME AS PRODUCT_NAME,
PRICE AS PRODUCT_PRICE,
ROUND(PRICE*0.18,2) AS GST_AMOUNT,
ROUND(PRICE+PRICE*0.18,2) AS FINAL_PRICE
FROM PRODUCTS;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME AS CUSTOMER_NAME,
YEAR(REGISTEREDDATE) AS REGISTERED_YEAR
FROM CUSTOMERS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME AS EMPLOYEE_NAME,
DATE_FORMAT(JOININGDATE, '%d-%m-%Y') AS JOINING_DATE
FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENTNAME AS STUDENT_NAME,
LENGTH(STUDENTNAME) AS NAME_LENGTH
FROM STUDENTS;

USE LIBRARYDB;
SELECT TITLE AS BOOK_NAME,
ROUND(PRICE-PRICE*0.10,2) AS DISCOUNTED_PRICE
FROM BOOKS;

USE EMPLOYEEDB;
SELECT ROUND(AVG(SALARY),2) AS AVG_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEENAME,SALARY,
(SELECT ROUND(AVG(SALARY),2) FROM EMPLOYEES) AS AVG_SALARY
FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY)
FROM EMPLOYEES);

SELECT MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEES;

SELECT MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT SUM(PRICE * AVAILABLESTOCK) AS TOTAL_INVENTORY_VALUE
FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT DEPARTMENT AS DEPARTMENT_NAME,
COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT AS DEPARTMENT_NAME,
ROUND(AVG(SALARY),2) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE SHOPPINGDB;
SELECT CATEGORY AS CATEGORY_NAME,
SUM(PRICE * AVAILABLESTOCK) AS TOTAL_VALUE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY AS CATEGORY_NAME,
MAX(PRICE) AS MAXIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY AS CATEGORY_NAME,
MIN(PRICE) AS MINIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;








