USE EMPLOYEEDB;                                                       #ANY
SELECT * FROM EMPLOYEES 
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');

SELECT * FROM EMPLOYEES 
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'IT');

SELECT * FROM EMPLOYEES 
WHERE SALARY = ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'FINANCE');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE > ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');

SELECT * FROM PRODUCTS 
WHERE PRICE < ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ACCESSORIES');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE > ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

SELECT * FROM BOOKS 
WHERE PRICE < ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'SCIENCE');

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE AGE > ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'IT');

SELECT * FROM STUDENTS
WHERE AGE < ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');

USE COURSEDB;
SELECT * FROM COURSES 
WHERE FEES > ANY (SELECT FEES FROM STUDENTS WHERE DEPARTMENT = 'IT');

SELECT * FROM COURSES
WHERE FEES < ANY (SELECT FEES FROM STUDENTS WHERE DEPARTMENT = 'CSE');

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES 
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE > ANY (SELECT PRICE FROM PRODUCTS WHERE BRAND = 'SAMSUNG');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE QUANTITY > ANY (SELECT QUANTITY FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

USE HOSPITALDB;
SELECT * FROM PATIENTS 
WHERE AGE > ANY (SELECT AGE FROM PATIENTS WHERE DISEASE = 'FEVER');




USE EMPLOYEEDB;                                                       #ANY
SELECT * FROM EMPLOYEES 
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');

SELECT * FROM EMPLOYEES 
WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'IT');

SELECT * FROM EMPLOYEES 
WHERE SALARY = ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'FINANCE');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');

SELECT * FROM PRODUCTS 
WHERE PRICE < ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ACCESSORIES');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE > ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

SELECT * FROM BOOKS 
WHERE PRICE < ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'SCIENCE');

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE AGE > ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'IT');

SELECT * FROM STUDENTS
WHERE AGE < ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');

USE COURSEDB;
SELECT * FROM COURSES 
WHERE FEES > ALL (SELECT FEES FROM STUDENTS WHERE DEPARTMENT = 'IT');

SELECT * FROM COURSES
WHERE FEES < ALL (SELECT FEES FROM STUDENTS WHERE DEPARTMENT = 'CSE');

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES 
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE BRAND = 'SAMSUNG');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE QUANTITY > ALL (SELECT QUANTITY FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

USE HOSPITALDB;
SELECT * FROM PATIENTS 
WHERE AGE > ALL (SELECT AGE FROM PATIENTS WHERE DISEASE = 'FEVER');





USE EMPLOYEEDB;                                                       #ANY AND ALL
SELECT * FROM EMPLOYEES 
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');

SELECT * FROM EMPLOYEES 
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE < ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');

SELECT * FROM PRODUCTS 
WHERE PRICE < ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE > ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

SELECT * FROM BOOKS 
WHERE PRICE > ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE AGE > ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');

SELECT * FROM STUDENTS
WHERE AGE > ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');

USE EMPLOYEEDB;                                                       
SELECT * FROM EMPLOYEES 
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER');

SELECT * FROM EMPLOYEES 
WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER');


