USE STUDENTDB;                                                     #BETWEEN
SELECT * FROM STUDENTS
WHERE AGE BETWEEN 18 AND 25;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 30000.00 AND 60000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE BETWEEN 20 AND 40;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE BETWEEN 500.00 AND 1000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE BETWEEN 5000.00 AND 50000.00;

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES BETWEEN 20000.00 AND 50000.00;

USE HOTELDB;
SELECT * FROM ROOMS
WHERE PRICEPERDAY BETWEEN 2000.00 AND 5000.00;

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING BETWEEN 3.0 AND 5.0;

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE STUDENTID BETWEEN 001 AND 010;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES 
WHERE EMPLOYEEID BETWEEN 001 AND 010;




USE STUDENTDB;                                              #NOT BETWEEN
SELECT * FROM STUDENTS
WHERE AGE NOT BETWEEN 18 AND 25;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 30000.00 AND 60000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE NOT BETWEEN 20 AND 40;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE NOT BETWEEN 500.00 AND 1000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE NOT BETWEEN 5000.00 AND 50000.00;

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES NOT BETWEEN 20000.00 AND 50000.00;

USE HOTELDB;
SELECT * FROM ROOMS
WHERE PRICEPERDAY NOT BETWEEN 2000.00 AND 5000.00;

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING NOT BETWEEN 3.0 AND 5.0;

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE STUDENTID NOT BETWEEN 001 AND 010;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES 
WHERE EMPLOYEEID NOT BETWEEN 001 AND 010;





USE STUDENTDB;                                      #BETWEEN WITH CONDITIONS
SELECT * FROM STUDENTS
WHERE AGE BETWEEN 18 AND 25
AND DEPARTMENT='BBA';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 40000.00 AND 70000.00
AND DEPARTMENT='IT';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE BETWEEN 25 AND 50
AND GENDER='FEMALE';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE BETWEEN 500.00 AND 1500.00
AND CATEGORY='TECHNOLOGY';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE BETWEEN 10000.00 AND 50000.00
AND CATEGORY='ELECTRONICS';

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES BETWEEN 25000.00 AND 75000.00
AND DEPARTMENT='CSE';

USE HOTELDB;
SELECT * FROM ROOMS
WHERE PRICEPERDAY BETWEEN 2000.00 AND 4000.00
AND AVAILABILITY='AVAILABLE';

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING BETWEEN 3.5 AND 5.0
AND `LANGUAGE`='TAMIL';





USE STUDENTDB;                                      #NOT BETWEEN WITH CONDITIONS
SELECT * FROM STUDENTS
WHERE AGE NOT BETWEEN 18 AND 25
AND DEPARTMENT='IT';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 30000.00 AND 60000.00
AND DEPARTMENT='HR';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE NOT BETWEEN 20 AND 40
AND BLOODGROUP='O POSITIVE';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE NOT BETWEEN 500.00 AND 1000.00
AND CATEGORY='TECHNOLOGY';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE NOT BETWEEN 5000.00 AND 50000.00
AND CATEGORY='ELECTRONICS';

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES NOT BETWEEN 20000.00 AND 50000.00
AND DEPARTMENT='IT';

USE HOTELDB;
SELECT * FROM ROOMS
WHERE PRICEPERDAY NOT BETWEEN 2000.00 AND 5000.00
AND AVAILABILITY='AVAILABLE';



USE EMPLOYEEDB;                                        #DATE WITH BETWEEN
SELECT * FROM EMPLOYEES
WHERE JOININGDATE BETWEEN '2026-01-01' AND '2026-06-31';

USE HOSPITALDB;                                      
SELECT * FROM PATIENTS
WHERE ADMISSIONDATE BETWEEN '2026-08-01' AND '2026-08-21';

USE SHOPPINGDB;                                      
SELECT * FROM PRODUCTS
WHERE MANUFACTURINGDATE BETWEEN '2026-01-01' AND '2026-04-01';


USE ECOMMERCEDB;                                      
SELECT * FROM CUSTOMERS
WHERE REGISTEREDDATE BETWEEN '2026-01-01' AND '2026-06-31';


USE MOVIEDB;                                      
SELECT * FROM MOVIES
WHERE RELEASEDATE BETWEEN '2026-01-01' AND '2026-06-31';

