USE STUDENTDB;                                         #BASIC CASE
SELECT STUDENTNAME,AGE,
CASE WHEN AGE>=18 THEN 'ADULT'
ELSE 'MINOR'
END AS 'AGE CATEGORY'
FROM STUDENTS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=60000.00 THEN 'HIGH'
WHEN SALARY>=40000.00 THEN 'MEDIUM'
ELSE 'LOW'
END AS 'SALARY CATEGORY'
FROM EMPLOYEES;

USE STUDENTDB;                                        
SELECT STUDENTNAME,MARK,
CASE WHEN MARK>=90 THEN 'EXCELLENT'
WHEN MARK>=75 THEN 'VERY GOOD'
WHEN MARK>=50 THEN 'GOOD'
ELSE 'FAIL'
END AS 'PERFORMANCE CATEGORY'
FROM STUDENTS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=50000.00 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS 'ELIGIBILITY CAREGORY'
FROM EMPLOYEES;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,PRICE,
CASE WHEN PRICE>=50000.00 THEN 'EXPENSIVE'
WHEN PRICE>=10000.00 THEN 'MODERATE'
ELSE 'AFFORDABLE'
END AS 'PRICE CAREGORY'
FROM PRODUCTS;

USE LIBRARYDB;                                         
SELECT TITLE,PRICE,
CASE WHEN PRICE>=1000.00 THEN 'PREMIUM'
ELSE 'REGULAR'
END AS 'PRICE CAREGORY'
FROM BOOKS;

USE HOSPITALDB;                                         
SELECT PATIENTNAME,AGE,
CASE WHEN AGE>=60 THEN 'SENIOR CITIZEN'
WHEN AGE>=18 THEN 'ADULT'
ELSE 'MINOR'
END AS 'AGE CAREGORY'
FROM PATIENTS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,EXPERIENCE,
CASE WHEN EXPERIENCE>=10 THEN 'SENIOR'
WHEN EXPERIENCE>=5 THEN 'INTERMEDIATE'
ELSE 'JUNIOR'
END AS 'EXPERIENCE CATEGORY'
FROM EMPLOYEES;

USE COURSEDB;
SELECT COURSENAME,FEES,
CASE WHEN FEES>=50000.00 THEN 'HIGH FEE'
WHEN FEES>=30000.00 THEN 'MEDIUM FEE'
ELSE 'LOW FEE'
END AS 'FEE CATEGORY'
FROM COURSES;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,AVAILABLESTOCK,
CASE WHEN AVAILABLESTOCK=0 THEN 'OUT OF STOCK'
WHEN AVAILABLESTOCK<10 THEN 'LOW STOCK'
ELSE 'AVAILABLE'
END AS 'AVAILABILITY CAREGORY'
FROM PRODUCTS;

USE STUDENTDB;                                        
SELECT STUDENTNAME,MARK,
CASE WHEN MARK>=40 THEN 'PASS'
ELSE 'FAIL'
END AS 'PERFORMANCE CATEGORY'
FROM STUDENTS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=70000.00 THEN 'HIGH SALARY'
ELSE 'LOW SALARY'
END AS 'SALARY CAREGORY'
FROM EMPLOYEES;

USE LIBRARYDB;                                         
SELECT TITLE,PRICE,
CASE WHEN PRICE>=1500.00 THEN 'COSTLY'
ELSE 'AFFORDABLE'
END AS 'PRICE CAREGORY'
FROM BOOKS;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,AVAILABLESTOCK,
CASE WHEN AVAILABLESTOCK>=100 THEN 'BULK STOCK'
ELSE 'NORMAL STOCK'
END AS 'STOCK CAREGORY'
FROM PRODUCTS;

USE MOVIEDB;                                         
SELECT TITLE,RATING,
CASE WHEN RATING>=4.5 THEN 'EXCELLENT'
WHEN RATING>=3.0 THEN 'GOOD'
ELSE 'AVERAGE'
END AS 'RATING CAREGORY'
FROM MOVIES;

USE ECOMMERCEDB;                                         
SELECT CUSTOMERNAME,AGE,
CASE WHEN AGE>=60 THEN 'SENIOR'
WHEN AGE>=30 THEN 'ADULT'
ELSE 'YOUNG'
END AS 'AGE CAREGORY'
FROM CUSTOMERS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=100000.00 THEN 'GRADE A'
WHEN SALARY>=60000.00 THEN 'GRADE B'
ELSE 'GRADE C'
END AS 'SALARY CAREGORY'
FROM EMPLOYEES;

USE STUDENTDB;                                        
SELECT STUDENTNAME,ATTENDANCE,
CASE WHEN ATTENDANCE>=90 THEN 'EXCELLENT'
WHEN ATTENDANCE>=75 THEN 'GOOD'
ELSE 'LOW'
END AS 'ATTENDANCE CATEGORY'
FROM STUDENTS;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,PRICE,
CASE WHEN PRICE>=100000.00 THEN 'LUXURY'
WHEN PRICE>=50000.00 THEN 'PREMIUM'
ELSE 'STANDARD'
END AS 'PRICE CAREGORY'
FROM PRODUCTS;

USE COURSEDB;                                         
SELECT COURSENAME,DURATION,
CASE WHEN DURATION>=12 THEN 'LONG TERM'
WHEN DURATION>=6 THEN 'MEDIUM TERM'
ELSE 'SHORT TERM'
END AS 'DURATION CAREGORY'
FROM COURSES;





USE EMPLOYEEDB;                                #CASE WITH MULTIPLE CONDITION                      
SELECT EMPLOYEENAME,SALARY,
CASE WHEN DEPARTMENT ='IT' AND SALARY>=60000.00 THEN 'IT HIGH SALARY'
WHEN DEPARTMENT ='HR' AND SALARY>=50000.00 THEN 'HR HIGH SALARY'
ELSE 'OTHER'
END AS 'SALARY CATEGORY'
FROM EMPLOYEES;

USE STUDENTDB;                                        
SELECT STUDENTNAME,MARK,DEPARTMENT,
CASE WHEN DEPARTMENT='CSE' AND MARK>=80 THEN 'CSE EXCELLENT'
WHEN DEPARTMENT='IT' AND MARK>=80 THEN 'IT EXCELLENT'
ELSE 'OTHER'
END AS 'MARK CATEGORY'
FROM STUDENTS;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,PRICE,
CASE WHEN CATEGORY='ELECTRONICS' AND PRICE>=50000.00 THEN 'PREMIUM ELECTRONICS'
WHEN CATEGORY='ELECTRONICS' AND PRICE<50000.00 THEN 'REGULAR ELECTRONICS'
ELSE 'OTHER CATEGORY'
END AS 'CAREGORY'
FROM PRODUCTS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,SALARY,EXPERIENCE,
CASE WHEN SALARY>=70000.00 AND EXPERIENCE>=5 THEN 'SENIOR HIGH SALARY'
WHEN SALARY>=50000.00 THEN 'GOOD SALARY'
ELSE 'REGULAR'
END AS 'SALARY CAREGORY'
FROM EMPLOYEES;

USE STUDENTDB;                                        
SELECT STUDENTNAME,AGE,ATTENDANCE,
CASE WHEN ATTENDANCE>=75 AND AGE>=18 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS 'ELIGIBILITY CATEGORY'
FROM STUDENTS;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,AVAILABLESTOCK,
CASE WHEN AVAILABLESTOCK=0 THEN 'OUT OF STOCK'
WHEN AVAILABLESTOCK<10 THEN 'LOW STOCK'
WHEN AVAILABLESTOCK>=0 THEN 'AVAILABLE'
END AS 'AVAILABILITY CAREGORY'
FROM PRODUCTS;

USE LIBRARYDB;                                         
SELECT TITLE,PRICE,
CASE WHEN CATEGORY='TECHNOLOGY' AND PRICE>1000.00 THEN 'PREMIUM TECHNOLOGY'
WHEN CATEGORY='TECHNOLOGY' AND PRICE<=1000.00 THEN 'REGULAR TECHNOLOGY'
ELSE 'OTHER'
END AS 'CAREGORY'
FROM BOOKS;

USE HOSPITALDB;                                         
SELECT PATIENTNAME,AGE,
CASE WHEN DISEASE IS NOT NULL AND AGE>=60 THEN 'SENIOR PATIENT'
WHEN AGE>=18 THEN 'ADULT PATIENT'
ELSE 'YOUNG PATIENT'
END AS 'AGE CAREGORY'
FROM PATIENTS;

USE ECOMMERCEDB;                                         
SELECT CUSTOMERNAME,CITY,COUNTRY,
CASE WHEN CITY='CHENNAI' AND COUNTRY='INDIA' THEN 'CHENNAI CUSTOMER'
ELSE 'OTHER CUSTOMER'
END AS 'CUSTOMER CAREGORY'
FROM CUSTOMERS;

USE EMPLOYEEDB;                                                     
SELECT EMPLOYEENAME,SALARY,
CASE WHEN DEPARTMENT ='IT' AND SALARY>=50000.00 THEN 'IT HIGH'
WHEN DEPARTMENT ='IT' AND SALARY<50000.00 THEN 'HR NORMAL'
ELSE 'OTHER DEPARTMENT'
END AS 'SALARY CATEGORY'
FROM EMPLOYEES;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,AVAILABLESTOCK,PRICE,
CASE WHEN PRICE>=50000.00 AND AVAILABLESTOCK>10 THEN 'PREMIUM AVAILABLE'
WHEN PRICE>=50000.00 AND AVAILABLESTOCK=0 THEN 'PREMIUM UNAVAILABLE'
ELSE'REGULAR'
END AS 'PREMIUM AVAILABILITY'
FROM PRODUCTS;

USE STUDENTDB;                                        
SELECT STUDENTNAME,MARK,ATTENDANCE,
CASE WHEN ATTENDANCE>=90 AND MARK>=90 THEN 'OUTSTANDING'
WHEN ATTENDANCE>=75 AND MARK>=75 THEN 'GOOD'
ELSE 'NEEDS IMPROVEMENT'
END AS 'PERFORMANCE CATEGORY'
FROM STUDENTS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,SALARY,EXPERIENCE,
CASE WHEN SALARY>=80000.00 AND EXPERIENCE>=10 THEN 'SENIOR'
WHEN EXPERIENCE>=5 THEN 'MID LEVEL'
ELSE 'JUNIOR'
END AS 'SALARY CAREGORY'
FROM EMPLOYEES;

USE COURSEDB;                                         
SELECT COURSENAME,DURATION,FEES,
CASE WHEN DURATION>=12 AND FEES>=50000.00 THEN 'PREMIUM LONG TERM'
WHEN FEES>=30000.00 THEN 'STANDARD'
ELSE 'BASIC'
END AS 'DURATION CAREGORY'
FROM COURSES;

USE MOVIEDB;                                         
SELECT TITLE,RATING,
CASE WHEN RATING>=4.5 AND LANGUAGE='TAMIL' THEN 'TAMIL HIT'
WHEN RATING>=4.5 THEN 'HIT'
ELSE 'AVERAGE'
END AS 'RATING CAREGORY'
FROM MOVIES;

USE LIBRARYDB;                                         
SELECT TITLE,PRICE,CATEGORY,
CASE WHEN CATEGORY='TECHNOLOGY' AND PRICE>1500.00 THEN 'PREMIUM TECHNOLOGY'
WHEN CATEGORY='SCIENCE' AND PRICE>1000.00 THEN 'PREMIUM SCIENCE'
ELSE 'REGULAR'
END AS 'CAREGORY'
FROM BOOKS;

USE EMPLOYEEDB;                                                   
SELECT EMPLOYEENAME,SALARY,
CASE WHEN DEPARTMENT ='IT' AND SALARY>60000.00 THEN 'IT SENIOR'
WHEN DEPARTMENT ='HR' AND SALARY>50000.00 THEN 'HR SENIOR'
ELSE 'OTHER'
END AS 'SALARY CATEGORY'
FROM EMPLOYEES;

USE STUDENTDB;                                        
SELECT STUDENTNAME,DEPARTMENT,AGE,
CASE WHEN DEPARTMENT='CSE' AND AGE<21 THEN 'YOUNG CSE'
WHEN DEPARTMENT='IT' AND AGE<21 THEN 'YOUNG IT'
ELSE 'OTHER'
END AS 'CATEGORY'
FROM STUDENTS;

USE ECOMMERCEDB;                                         
SELECT CUSTOMERNAME,CITY,COUNTRY,
CASE WHEN CITY='CHENNAI' AND EMAIL IS NOT NULL THEN 'VERIFIED CHENNAI'
WHEN CITY='CHENNAI' AND EMAIL IS NULL THEN 'UNVERIFIED CHENNAI'
ELSE 'OTHER CITY'
END AS 'VERIFICATION CAREGORY'
FROM CUSTOMERS;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,AVAILABLESTOCK,BRAND,
CASE WHEN BRAND IS NULL THEN 'UNKNOWN BRAND'
WHEN AVAILABLESTOCK=0 THEN 'OUT OF STOCK'
WHEN AVAILABLESTOCK<0 THEN 'LOW STOCK'
ELSE'AVAILABLE'
END AS 'CATEGORISATION'
FROM PRODUCTS;





USE STUDENTDB;                                  #CASE WITH NULL                         
SELECT *,
CASE WHEN EMAIL IS NULL THEN 'EMAIL MISSING'
WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
END AS 'EMAIL AVAILABILITY'
FROM STUDENTS;

USE EMPLOYEEDB;                                                   
SELECT *,
CASE WHEN DEPARTMENT IS NOT NULL THEN 'DEPARTMENT ASSIGNED'
WHEN DEPARTMENT IS NULL THEN 'DEPARTMENT MISSING'
END AS 'DEPARTMENT ASSIGNING STATUS '
FROM EMPLOYEES;

USE SHOPPINGDB;                                         
SELECT *,
CASE WHEN BRAND IS NULL THEN 'BRAND MISSING'
WHEN BRAND IS NOT NULL THEN 'BRAND AVAILABLE'
END AS 'BRAND AVAILABILITY'
FROM PRODUCTS;

USE LIBRARYDB;                                         
SELECT *,
CASE WHEN AUTHOR IS NULL THEN 'AUTHOR MISSING'
WHEN AUTHOR IS NOT NULL THEN 'AUTHOR AVAILABLE'
END AS 'AUTHOR AVAILABILITY'
FROM BOOKS;

USE ECOMMERCEDB;                                         
SELECT *,
CASE WHEN EMAIL IS NULL THEN 'EMAIL MISSING'
WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
END AS 'EMAIL AVAILABILITY'
FROM CUSTOMERS;

USE HOSPITALDB;                                         
SELECT *,
CASE WHEN DISEASE IS NULL THEN 'DISEASE MISSING'
WHEN DISEASE IS NOT NULL THEN 'DISEASE AVAILABLE'
END AS 'DISEASE AVAILABILITY'
FROM PATIENTS;

USE SHOPPINGDB;                                         
SELECT *,
CASE WHEN DISCOUNT IS NULL THEN 'NO DISCOUNT'
WHEN DISCOUNT IS NOT NULL THEN 'DISCOUNT AVAILABLE'
END AS 'DISCOUNT AVAILABILITY'
FROM PRODUCTS;

USE STUDENTDB;                                                    
SELECT *,
CASE WHEN MOBILENUMBER IS NULL THEN 'MOBILENUMBER MISSING'
WHEN MOBILENUMBER IS NOT NULL THEN 'MOBILENUMBER AVAILABLE'
END AS 'MOBILENUMBER AVAILABILITY'
FROM STUDENTS;

USE LIBRARYDB;                                         
SELECT *,
CASE WHEN PUBLISHEDYEAR IS NULL THEN 'PUBLISHEDYEAR MISSING'
WHEN PUBLISHEDYEAR IS NOT NULL THEN 'PUBLISHEDYEAR AVAILABLE'
END AS 'PUBLISHEDYEAR AVAILABILITY'
FROM BOOKS;




USE EMPLOYEEDB;                                       #CASE WITH AGGREGATE FUNCTIONS
SELECT COUNT(CASE WHEN SALARY>=50000.00 THEN 1
END) AS 'EMPLOYEE COUNT' FROM EMPLOYEES;

USE STUDENTDB;
SELECT COUNT(CASE WHEN MARK>=40 THEN 1
END) AS 'PASSED COUNT' FROM STUDENTS;

USE SHOPPINGDB;
SELECT COUNT(CASE WHEN AVAILABLESTOCK<0 THEN 1
END) AS 'OUT OF STOCK PRODUCTS' FROM PRODUCTS;

SELECT COUNT(CASE WHEN PRICE>5000.00 THEN 1
END) AS 'PRODUCTS PRICED MORE THAN 5000' FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT SUM(CASE WHEN SALARY>=50000.00 THEN SALARY
END) AS 'TOTAL SALARY OF EMPLOYEES WITH SALARY MORE THAN 50000' FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT SUM(CASE WHEN CATEGORY='ELECTRONICS' THEN PRICE*AVAILABLESTOCK
END) AS 'PRICE OF ELECTRONIC PRODUCTS' FROM PRODUCTS;

SELECT SUM(CASE WHEN AVAILABLESTOCK>10 THEN AVAILABLESTOCK
END) AS 'TOTAL STOCK OF BULK PRODUCTS' FROM PRODUCTS;

USE STUDENTDB;
SELECT COUNT(CASE WHEN ATTENDANCE>=75 THEN 1
END) AS 'GOOD ATTENDANCE COUNT' FROM STUDENTS;

USE EMPLOYEEDB;                                       
SELECT COUNT(CASE WHEN DEPARTMENT='IT' THEN 1
END) AS 'IT EMPLOYEE COUNT' FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT SUM(CASE WHEN PRICE>10000.00 THEN PRICE*AVAILABLESTOCK
END) AS 'VALUE OF COSTLY PRODUCTS' FROM PRODUCTS;





USE EMPLOYEEDB;                             #ADVANCED CASE PRACTICE                      
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=100000.00 THEN 'GRADE A'
WHEN SALARY>=70000.00 THEN 'GRADE B'
WHEN SALARY>=50000.00 THEN 'GRADE C'
WHEN SALARY>=30000.00 THEN 'GRADE D'
ELSE 'GRADE E'
END AS 'SALARY CAREGORY'
FROM EMPLOYEES;


USE STUDENTDB;                                       
SELECT STUDENTNAME,MARK,
CASE WHEN MARK>=90 THEN 'EXCELLENT'
WHEN MARK>=75 THEN 'VERY GOOD'
WHEN MARK>=60 THEN 'GOOD'
WHEN MARK>=40 THEN 'AVERAGE'
ELSE 'FAIL NEED TO IMPROVE'
END AS 'PERFORMANCE CATEGORY'
FROM STUDENTS;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,PRICE,
CASE WHEN PRICE>=50000.00 THEN 'EXPENSIVE'
WHEN PRICE>=10000.00 THEN 'MODERATE'
WHEN PRICE>=5000.00 THEN 'AFFORDABLE'
ELSE 'CHEAP'
END AS 'PRICE CAREGORY'
FROM PRODUCTS;

USE LIBRARYDB;                                         
SELECT TITLE,PRICE,
CASE WHEN PRICE>=3000.00 THEN 'PREMIUM'
WHEN PRICE>=2000.00 THEN 'EXPENSIVE'
WHEN PRICE>=1000.00 THEN 'MODERATE'
ELSE 'AFFORDABLE'
END AS 'PRICE CAREGORY'
FROM BOOKS;

USE ECOMMERCEDB;                                         
SELECT CUSTOMERNAME,AGE,
CASE WHEN AGE>=80 THEN 'SUPER SENIOR'
WHEN AGE>=60 THEN 'SENIOR'
WHEN AGE>=30 THEN 'ADULT'
ELSE 'YOUNG'
END AS 'AGE CAREGORY'
FROM CUSTOMERS;

USE EMPLOYEEDB;                                          
SELECT EMPLOYEENAME,SALARY, SALARY * 12 AS 'ANNUAL SALARY',
CASE WHEN SALARY>=100000.00 THEN 'GRADE A'
WHEN SALARY>=70000.00 THEN 'GRADE B'
WHEN SALARY>=50000.00 THEN 'GRADE C'
WHEN SALARY>=30000.00 THEN 'GRADE D'
ELSE 'GRADE E'
END AS 'SALARY CAREGORY'
FROM EMPLOYEES;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,PRICE,AVAILABLESTOCK,
CASE WHEN AVAILABLESTOCK=0 THEN 'OUT OF STOCK'
WHEN AVAILABLESTOCK<10 THEN 'LOW STOCK'
ELSE 'AVAILABLE'
END AS 'AVAILABILITY CAREGORY'
FROM PRODUCTS;

USE STUDENTDB;                                        
SELECT STUDENTNAME,ATTENDANCE,MARK,
CASE WHEN ATTENDANCE>=75 AND MARK>=75 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS 'ELIGIBILITY'
FROM STUDENTS;

USE COURSEDB;                                         
SELECT COURSENAME,FEES,
CASE WHEN FEES>=50000.00 THEN 'PREMIUM'
WHEN FEES>=30000.00 THEN 'STANDARD'
ELSE 'BASIC'
END AS 'FEES CAREGORY'
FROM COURSES;

USE MOVIEDB;                                         
SELECT TITLE,RATING,
CASE WHEN RATING>=8 THEN 'BLOCKBUSTER'
WHEN RATING>=7 THEN 'SUPER HIT'
WHEN RATING>=6 THEN 'HIT'
WHEN RATING>=5 THEN 'AVERAGE'
WHEN RATING>=4 THEN 'BELOW AVERAGE'
ELSE 'FLOP'
END AS 'RATING CAREGORY'
FROM MOVIES;

USE EMPLOYEEDB;                                        
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=90000.00 THEN 'GRADE A'
WHEN SALARY>=70000.00 THEN 'GRADE B'
WHEN SALARY>=50000.00 THEN 'GRADE C'
ELSE 'GRADE D'
END AS 'SALARY CAREGORY'
FROM EMPLOYEES;

USE STUDENTDB;                                       
SELECT STUDENTNAME,MARK,
CASE WHEN MARK>=90 THEN 'DISTINCTION'
WHEN MARK>=75 THEN 'FIRST CLASS'
WHEN MARK>=50 THEN 'SECOND CLASS'
ELSE 'FAIL'
END AS 'PERFORMANCE CATEGORY'
FROM STUDENTS;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,PRICE,
CASE WHEN PRICE>=100000.00 THEN 'LUXURY'
WHEN PRICE>=50000.00 THEN 'PREMIUM'
WHEN PRICE>=10000.00 THEN'STANDARD'
WHEN PRICE<10000.00 THEN 'BUDGET'
END AS 'PRICE CAREGORY'
FROM PRODUCTS;

USE EMPLOYEEDB;                                         
SELECT EMPLOYEENAME,EXPERIENCE,
CASE WHEN EXPERIENCE=10 THEN 'EXPERT'
WHEN EXPERIENCE>=5 THEN 'EXPERIENCED'
WHEN EXPERIENCE>=2 THEN 'INTERMEDIATE'
WHEN EXPERIENCE<2 THEN 'FRESHER'
END AS 'EXPERIENCE CATEGORY'
FROM EMPLOYEES;

USE STUDENTDB;                                       
SELECT STUDENTNAME,MARK,
CASE WHEN MARK>=90 THEN 'EXCELLENT'
WHEN MARK>=75 THEN 'GOOD'
WHEN MARK>=60 THEN 'AVERAGE'
WHEN MARK<60 THEN 'POOR'
END AS 'PERFORMANCE CATEGORY'
FROM STUDENTS;

USE EMPLOYEEDB;           
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=80000.00 THEN ROUND(SALARY*1.20,2)
WHEN SALARY>=50000.00 THEN ROUND(SALARY*1.10,2)
ELSE ROUND(SALARY*1.05,2)
END AS 'BONUS SALARY'
FROM EMPLOYEES;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,PRICE,
CASE WHEN PRICE>=100000.00 THEN ROUND(PRICE-PRICE*20/100,2)
WHEN PRICE>=50000.00 THEN ROUND(PRICE-PRICE*15/100,2)
WHEN PRICE>=10000.00 THEN ROUND(PRICE-PRICE*10/100,2)
ELSE ROUND(PRICE-PRICE*5/100,2)
END AS 'DISCOUNT PRICE'
FROM PRODUCTS;

USE STUDENTDB;                                        
SELECT STUDENTNAME,ATTENDANCE,MARK,
CASE WHEN ATTENDANCE>=75 AND MARK>=50 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS 'ELIGIBILITY'
FROM STUDENTS;

USE EMPLOYEEDB;                                        
SELECT EMPLOYEENAME,SALALRY,EXPERIENCE,
CASE WHEN EXPERIENCE>=5 AND SALALRY>=60000.00 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS 'ELIGIBILITY'
FROM EMPLOYEES;

USE SHOPPINGDB;                                         
SELECT PRODUCTNAME,AVAILABLESTOCK,
CASE WHEN AVAILABLESTOCK=0 THEN 'ORDER IMMIDIATELY'
WHEN AVAILABLESTOCK<10 THEN 'REORDER'
WHEN AVAILABLESTOCK>=10 THEN 'NO REORDER'
END AS 'ORDER STATUS'
FROM PRODUCTS;