USE STUDENTDB;                                 #BASIC DISTINCT

SELECT DISTINCT department
FROM students;

SELECT DISTINCT GENDER
FROM students;

USE EMPLOYEEDB;

SELECT DISTINCT department
FROM EMPLOYEES;

SELECT DISTINCT designation
FROM EMPLOYEES;

USE HOSPITALDB;

SELECT DISTINCT BLOODGROUP
FROM PATIENTS;

SELECT DISTINCT DISEASE
FROM PATIENTS;

USE LIBRARYDB;

SELECT DISTINCT CATEGORY
FROM BOOKS;

SELECT DISTINCT AUTHOR
FROM BOOKS;

USE SHOPPINGDB;

SELECT DISTINCT CATEGORY
FROM PRODUCTS;

SELECT DISTINCT BRAND
FROM PRODUCTS;

USE COURSESDB;

SELECT DISTINCT DEPARTMENT
FROM COURSES:

SELECT DISTINCT COURSE_DURATION 
FROM COURSES;

USE MOVIEDB;

SELECT DISTINCT `LANGUAGE`
FROM MOVIES;

SELECT DISTINCT GENRE
FROM MOVIES;

USE ECOMMERCEDB;

SELECT DISTINCT CITY
FROM CUSTOMERS;

SELECT DISTINCT STATE
FROM CUSTOMERS;

SELECT DISTINCT COUNTRY
FROM CUSTOMERS;

USE EMPLOYEEDB;

SELECT DISTINCT department, Designation
FROM EMPLOYEES;

USE SHOPPINGDB;

SELECT DISTINCT CATEGORY , BRAND
FROM PRODUCTS;

USE ECOMMERCEDB;

SELECT DISTINCT CITY, STATE
FROM CUSTOMERS;




USE STUDENTDB;                                             #DISTINCT WITH CONDITION                          

SELECT DISTINCT department
FROM students
WHERE AGE>20;

USE EMPLOYEEDB;

SELECT DISTINCT designation
FROM EMPLOYEES
WHERE SALARY>40000.00;

USE HOSPITALDB;

SELECT DISTINCT DISEASE
FROM PATIENTS
WHERE AGE>30;

USE LIBRARYDB;

SELECT DISTINCT CATEGORY
FROM BOOKS
WHERE PRICE>500;

USE SHOPPINGDB;

SELECT DISTINCT BRAND
FROM PRODUCTS
WHERE PRICE>10000.00;

USE MOVIEDB;

SELECT DISTINCT GENRE
FROM MOVIES
WHERE RATING>4.00;

USE ECOMMERCEDB;

SELECT DISTINCT CITY
FROM CUSTOMERS
WHERE COUNTRY='INDIA';

USE STUDENTDB;                                             

SELECT DISTINCT department
FROM students
WHERE DEPARTMENT IN ('BA','BBA');

USE EMPLOYEEDB;

SELECT DISTINCT department
FROM EMPLOYEES
WHERE SALARY BETWEEN 30000.00 AND 60000.00;

USE SHOPPINGDB;

SELECT DISTINCT CATEGORY
FROM PRODUCTS
WHERE AVAILABLESTOCK>10;




USE STUDENTDB;                                         #DISTINCT WITH OTHER OPERATORS

SELECT DISTINCT department
FROM students
WHERE DEPARTMENT IN ('BA','BBA','IT','CSE');

USE EMPLOYEEDB;

SELECT DISTINCT department
FROM EMPLOYEES
WHERE DEPARTMENT NOT IN ('HR','FINANCE');

USE SHOPPINGDB;

SELECT DISTINCT CATEGORY
FROM PRODUCTS
WHERE PRICE BETWEEN 5000.00 AND 50000.00;

USE LIBRARYDB;

SELECT DISTINCT CATEGORY
FROM BOOKS
WHERE PRICE NOT BETWEEN 500.00 AND 1000.00;

USE ECOMMERCEDB;

SELECT DISTINCT CITY
FROM CUSTOMERS
WHERE EMAIL IS NOT NULL;

SELECT DISTINCT CITY
FROM CUSTOMERS
WHERE EMAIL IS NULL;

USE EMPLOYEEDB;

SELECT DISTINCT department
FROM EMPLOYEES
WHERE SALARY>50000.00;

USE STUDENTDB;                                    

SELECT DISTINCT department
FROM students
WHERE AGE NOT BETWEEN 18 AND 25;

USE SHOPPINGDB;

SELECT DISTINCT BRAND
FROM PRODUCTS
WHERE BRAND IS NOT NULL;

USE HOSPITALDB;

SELECT DISTINCT BLOODGROUP
FROM PATIENTS
WHERE DISEASE IS NULL;