USE AUG28DB;                                          #EXISTS
SELECT * FROM DEPARTMENTS D
WHERE EXISTS (SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENTID = D.DEPARTMENTID );

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM DEPARTMENTS D
WHERE D.DEPARTMENTID = E.DEPARTMENTID);

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM DEPARTMENTS D
WHERE D.DEPARTMENTID = S.DEPARTMENTID);

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID);

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID);

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM ENROLLMENTS EN
WHERE EN.STUDENTID = S.STUDENTID);

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM PAYMENTS P
WHERE P.CUSTOMERID = C.CUSTOMERID);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID);

SELECT * FROM DEPARTMENTS D
WHERE EXISTS (SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENTID = D.DEPARTMENTID
AND E.SALARY > 50000);

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM EMPLOYEES E2
WHERE E2.DEPARTMENTID = E.DEPARTMENTID
AND E2.SALARY > 70000);

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM STUDENTS S2
WHERE S2.DEPARTMENTID = S.DEPARTMENTID
AND S2.AGE > 21);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM PRODUCTS P2
WHERE P2.CATEGORY = P.CATEGORY
AND P2.PRICE > 50000);

SELECT *FROM BOOKS B
WHERE EXISTS (SELECT *
FROM BOOKS B2
WHERE B2.CATEGORY = B.CATEGORY
AND B2.PRICE > 1000);

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.ORDER_AMOUNT > 10000);

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID);

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM ASSIGNMENTS A
WHERE A.STUDENTID = S.STUDENTID);

SELECT * FROM COURSES C
WHERE EXISTS (SELECT *
FROM ENROLLMENTS E
WHERE E.COURSEID = C.COURSEID);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID
AND O.QUANTITY > 10);

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND YEAR(O.ORDER_DATE) = 2026);





SELECT * FROM CUSTOMERS C                                             #NOT EXISTS
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID);

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID);

SELECT * FROM STUDENTS S
WHERE NOT EXISTS (SELECT *
FROM ENROLLMENTS EN
WHERE EN.STUDENTID = S.STUDENTID);

SELECT * FROM COURSES C
WHERE NOT EXISTS (SELECT *
FROM ENROLLMENTS E
WHERE E.COURSEID = C.COURSEID);

SELECT * FROM DEPARTMENTS D
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENTID = D.DEPARTMENTID);

SELECT * FROM CUSTOMERS C
WHERE NOT EXISTS (SELECT *
FROM PAYMENTS P
WHERE P.CUSTOMERID = C.CUSTOMERID);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID);

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID);

SELECT * FROM STUDENTS S
WHERE NOT EXISTS (SELECT *
FROM ASSIGNMENTS A
WHERE A.STUDENTID = S.STUDENTID);

SELECT * FROM DEPARTMENTS D
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENTID = D.DEPARTMENTID
AND E.SALARY > 70000);

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEES E2
WHERE E2.DEPARTMENTID = E.DEPARTMENTID
AND E2.SALARY > 70000);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM PRODUCTS P2
WHERE P2.CATEGORY = P.CATEGORY
AND P2.PRICE > 50000);

SELECT * FROM BOOKS B
WHERE NOT EXISTS (SELECT *
FROM BOOKS B2
WHERE B2.CATEGORY = B.CATEGORY
AND B2.PRICE > 1000);

SELECT * FROM CUSTOMERS C
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.ORDER_AMOUNT > 10000);

SELECT * FROM COURSES C
WHERE NOT EXISTS (SELECT *
FROM ENROLLMENTS E
WHERE E.COURSEID = C.COURSEID);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID
AND YEAR(O.ORDER_DATE) = 2026);

SELECT * FROM CUSTOMERS C
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND YEAR(O.ORDER_DATE) = 2026);

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.STATUS = 'ACTIVE');

SELECT * FROM STUDENTS S
WHERE NOT EXISTS (SELECT *
FROM ASSIGNMENTS A
WHERE A.STUDENTID = S.STUDENTID
AND A.STATUS = 'SUBMITTED');




SELECT * FROM EMPLOYEES E                             #EXISTS WITH CONDITIONS    
WHERE EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.PROJECT_STATUS = 'ACTIVE');

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.ORDER_AMOUNT > 5800);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT * 
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID
AND O.QUANTITY > 5);

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM ENROLLMENTS E
JOIN COURSES C ON C.COURSEID = E.COURSEID
WHERE E.STUDENTID = S.STUDENTID
AND C.COURSENAME = 'DATA ENGINEERING');

SELECT * FROM EMPLOYEES E               #THE QUESTION WAS TO DISPLAY EMPLOYEES WHOSE DEPARTMENT HAS AT LEAST 
WHERE EXISTS (SELECT *                   #ONE EMPLOYEE WITH SALARY GREATER THAN 60,000.I AM NOT SURE ABOUT THE 
FROM EMPLOYEES E2                        #SECOND TABLE WHETHER IT IS ANOTHER EMPLOYEE TABLE OR NOT 
WHERE E2.DEPARTMENTID = E.DEPARTMENTID    #SO I ASSUMED IT FOR ANOTHER EMPLOYEE TABLE
AND E2.SALARY > 60000);

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM STUDENTS S2
WHERE S2.DEPARTMENTID = S.DEPARTMENTID
AND S2.MARKS > 98);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM PRODUCTS P2
WHERE P2.CATEGORY = P.CATEGORY
AND P2.STOCK > 100);

SELECT * FROM BOOKS B
WHERE EXISTS (SELECT *
FROM BOOKS B2
WHERE B2.CATEGORY = B.CATEGORY
AND B2.PRICE < 500);

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.STATUS = 'DELIVERED');

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.STATUS = 'COMPLETED');

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM ASSIGNMENTS A
WHERE A.STUDENTID = S.STUDENTID
AND A.MARKS > 88);

SELECT * FROM COURSES C
WHERE EXISTS (SELECT *
FROM ENROLLMENTS E
WHERE E.COURSEID = C.COURSEID);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID
AND O.ORDER_DATE BETWEEN '2026-08-01'
AND '2026-08-31');

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.CITY = 'CHENNAI');

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.TEAM = 'DATA ENGINEERING');

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM ENROLLMENTS E
JOIN COURSES C ON C.COURSEID = E.COURSEID
WHERE E.STUDENTID = S.STUDENTID
AND C.FEES > 30000);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM PRODUCTS P2
WHERE P2.BRAND = P.BRAND
AND P2.STOCK < 10);

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM EMPLOYEES E2
WHERE E2.DEPARTMENTID = E.DEPARTMENTID
AND E2.DESIGNATION = 'MANAGER');

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.QUANTITY > 10);

SELECT * FROM BOOKS B
WHERE EXISTS (SELECT *
FROM BOOKS B2
WHERE B2.AUTHOR = B.AUTHOR
AND B2.BOOKID <> B.BOOKID);





SELECT * FROM CUSTOMERS C                      # NOT EXISTS WITH CONDITIONS 
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.ORDER_AMOUNT > 10000);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID
AND O.QUANTITY > 10);

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.STATUS = 'ACTIVE');

SELECT * FROM STUDENTS S
WHERE NOT EXISTS (SELECT *
FROM ASSIGNMENTS A
WHERE A.STUDENTID = S.STUDENTID
AND A.MARKS < 40);

SELECT * FROM COURSES C
WHERE NOT EXISTS (SELECT *
FROM ENROLLMENTS E
WHERE E.COURSEID = C.COURSEID);

SELECT * FROM DEPARTMENTS D
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENTID = D.DEPARTMENTID
AND E.SALARY > 60000);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM PRODUCTS P2
WHERE P2.CATEGORY = P.CATEGORY
AND P2.STOCK < 5);

SELECT * FROM BOOKS B
WHERE NOT EXISTS (SELECT *
FROM BOOKS B2
WHERE B2.CATEGORY = B.CATEGORY
AND B2.PRICE > 2000);

SELECT * FROM CUSTOMERS C
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.STATUS = 'CANCELLED');

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.STATUS = 'PENDING');

SELECT * FROM STUDENTS S
WHERE NOT EXISTS (SELECT *
FROM ENROLLMENTS E
JOIN COURSES C ON C.COURSEID = E.COURSEID
WHERE E.STUDENTID = S.STUDENTID
AND C.FEES > 50000);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID
AND YEAR(O.ORDER_DATE) = 2026);

SELECT * FROM CUSTOMERS C
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.ORDER_DATE >= '2026-08-01'
AND O.ORDER_DATE < '2026-09-01');

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.TEAM = 'ANALYTICS');

SELECT * FROM STUDENTS S
WHERE NOT EXISTS (SELECT *
FROM ASSIGNMENTS A
WHERE A.STUDENTID = S.STUDENTID
AND A.MARKS > 90);

SELECT * FROM PRODUCTS P
WHERE NOT EXISTS (SELECT *
FROM PRODUCTS P2
WHERE P2.CATEGORY = P.CATEGORY
AND P2.PRICE > 100000);

SELECT * FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT *
FROM EMPLOYEES E2
WHERE E2.DEPARTMENTID = E.DEPARTMENTID
AND E2.DESIGNATION = 'MANAGER');

SELECT * FROM CUSTOMERS C
WHERE NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.STATUS = 'DELIVERED');

SELECT * FROM STUDENTS S
WHERE NOT EXISTS (SELECT *
FROM ENROLLMENTS E
JOIN COURSES C ON C.COURSEID = E.COURSEID
WHERE E.STUDENTID = S.STUDENTID
AND C.COURSENAME = 'PYTHON');



SELECT * FROM CUSTOMERS C                             #CHALLENGE QUESTIONS 
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID)
AND NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.STATUS = 'CANCELLED');

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID)
AND NOT EXISTS (SELECT *
FROM RETURNS R
WHERE R.PRODUCTID = P.PRODUCTID);

SELECT * FROM EMPLOYEES E
WHERE EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID)
AND NOT EXISTS (SELECT *
FROM EMPLOYEEPROJECTS EP
WHERE EP.EMPLOYEEID = E.EMPLOYEEID
AND EP.STATUS = 'COMPLETED');

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM ENROLLMENTS E
WHERE E.STUDENTID = S.STUDENTID)
AND NOT EXISTS (SELECT *
FROM ASSIGNMENTS A
WHERE A.STUDENTID = S.STUDENTID);

SELECT * FROM DEPARTMENTS D
WHERE EXISTS (SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENTID = D.DEPARTMENTID)
AND NOT EXISTS (SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENTID = D.DEPARTMENTID
AND E.SALARY < 25000);

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID)
AND NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.PRODUCTID = P.PRODUCTID
AND O.QUANTITY > 20);

SELECT * FROM CUSTOMERS C
WHERE EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.STATUS = 'DELIVERED')
AND NOT EXISTS (SELECT *
FROM ORDERS O
WHERE O.CUSTOMERID = C.CUSTOMERID
AND O.STATUS = 'CANCELLED');

SELECT * FROM STUDENTS S
WHERE EXISTS (SELECT *
FROM STUDENTS S2
WHERE S2.DEPARTMENTID = S.DEPARTMENTID
AND S2.MARKS > 90)
AND S.MARKS < 90;

SELECT * FROM PRODUCTS P
WHERE EXISTS (SELECT *
FROM PRODUCTS P2
WHERE P2.CATEGORY = P.CATEGORY
AND P2.PRICE >= 50000)
AND P.PRICE < 50000;