USE EMPLOYEEDB;                                                   #ARITHMETIC EXPRESSION
SELECT * ,SALARY+5000.00 AS `NEW SALARY` FROM EMPLOYEES;

SELECT * ,SALARY*1.05 AS `NEW SALARY` FROM EMPLOYEES;

SELECT * ,SALARY-2000.00 AS `NEW SALARY` FROM EMPLOYEES;

SELECT * ,SALARY*12 AS `ANNUAL SALARY` FROM EMPLOYEES;

SELECT * ,(SALARY-(SALARY*5/100)) AS `NEW SALARY` FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT *,ROUND (PRICE*18/100,2) AS GST,ROUND(PRICE+(PRICE*18/100),2) AS `FINAL AMOUNT` FROM PRODUCTS;

SELECT *,ROUND (PRICE*10/100,2) AS DISCOUNT,ROUND(PRICE-(PRICE*10/100),2) AS `FINAL AMOUNT` FROM PRODUCTS;

SELECT *,ROUND (PRICE*15/100,2) AS DISCOUNT,ROUND(PRICE-(PRICE*15/100),2) AS `FINAL AMOUNT` FROM PRODUCTS;

USE LIBRARYDB;
SELECT *,ROUND (PRICE*10/100,2) AS TAX,ROUND(PRICE+(PRICE*10/100),2) AS `FINAL AMOUNT` FROM BOOKS;

SELECT *,ROUND (PRICE*20/100,2) AS DISCOUNT,ROUND(PRICE-(PRICE*20/100),2) AS `FINAL AMOUNT` FROM BOOKS;

USE COURSEDB;
SELECT *,ROUND (FEES*05/100,2) AS GST,ROUND(FEES+(FEES*05/100),2) AS `FINAL FEES` FROM COURSES;

SELECT *,ROUND (FEES*10/100,2) AS DISCOUNT,ROUND(FEES-(FEES*10/100),2) AS `FINAL FEES` FROM COURSES;

USE SHOPPINGDB;
SELECT *, AVAILABLESTOCK * PRICE AS `PRODUCT VALUE` FROM PRODUCTS;

USE LIBRARYDB;
SELECT *, QUANTITY * PRICE AS `INVENTORY VALUE` FROM BOOKS;

USE EMPLOYEEDB;
SELECT * ,((SALARY*1.10)*12) AS `ANNUAL SALARY` FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT *,ROUND(PRICE*20/100,2) AS `DISCOUNT`,
ROUND(PRICE*0.80,2) AS `AMOUNT AFTER DISCOUNT`,
ROUND(PRICE*0.80*18/100,2) AS `GST`,
ROUND(PRICE*0.80*1.18,2) AS `TOTAL PRICE` FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT * ,(SALARY+3000.00) AS `SALARY WITH ALLOWANCE` FROM EMPLOYEES;

USE COURSEDB;
SELECT *,ROUND (FEES*15/100,2) AS `SCHOLARSHIP DISCOUNT`,ROUND(FEES-(FEES*15/100),2) AS `FINAL FEES` FROM COURSES;

USE SHOPPINGDB;
SELECT *, AVAILABLESTOCK * PRICE AS `STOCK VALUE` FROM PRODUCTS;

USE EMPLOYEEDB;                                                  
SELECT * ,SALARY-50000.00 AS `DIFFERENCE` FROM EMPLOYEES;





USE EMPLOYEEDB;                            #COMPARISON EXPRESSIONS
SELECT * FROM EMPLOYEES 
WHERE SALARY>50000.00;

SELECT * FROM EMPLOYEES 
WHERE SALARY<30000.00;

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE>20;

SELECT * FROM STUDENTS
WHERE AGE=21;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE>10000.00;

SELECT * FROM PRODUCTS
WHERE AVAILABLESTOCK<10;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE BETWEEN 500.00 AND 1000.00;

USE EMPLOYEEDB;                            
SELECT * FROM EMPLOYEES 
WHERE SALARY<>40000.00;

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE>=18;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE<=10000.00;

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES>30000.00;

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING>=4.0;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE<60;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE AGE <> 25;

USE EMPLOYEEDB;                            
SELECT * FROM EMPLOYEES 
WHERE SALARY BETWEEN 40000.00 AND 70000.00;




USE EMPLOYEEDB;                                             #LOGICAL EXPRESSIONS
SELECT * FROM EMPLOYEES 
WHERE SALARY<>40000.00 AND DEPARTMENT='IT';

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE>20 AND DEPARTMENT='CSE';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE<=10000.00 AND AVAILABLESTOCK>10;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE>500.00 OR CATEGORY='TECHNOLOGY';

USE EMPLOYEEDB;                                            
SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT='IT' OR 'HR';

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE DEPARTMENT NOT IN ('IT');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS' AND PRICE BETWEEN 10000.00 AND 50000.00;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY = 'CHENNAI' OR 'BANGLORE';

USE EMPLOYEEDB;                                            
SELECT * FROM EMPLOYEES 
WHERE SALARY>50000.00 AND DESIGNATION='DEVELOPER';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE<500.00 OR PRICE>1500;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE>30 AND BLOODGROUP='O POSITIVE';

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE>22 OR DEPARTMENT='IT';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IS NOT NULL AND PRICE>5000.00;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY = 'CHENNAI' AND EMAIL IS NOT NULL;

USE EMPLOYEEDB;                                            
SELECT * FROM EMPLOYEES 
WHERE SALARY NOT BETWEEN 30000.00 AND 50000.00;





USE STUDENTDB;                                    #STRING EXPRESSIONS
SELECT UPPER(STUDENTNAME) FROM STUDENTS;

USE EMPLOYEEDB;
SELECT LOWER(EMPLOYEENAME) FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENTNAME,LENGTH(STUDENTNAME) AS `LENGTH OF NAME`FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,LEFT(EMPLOYEENAME,3) FROM EMPLOYEES;

SELECT EMPLOYEENAME,RIGHT(EMPLOYEENAME,2) FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT UPPER(PRODUCTNAME) AS PRODUCTS ,PRICE FROM PRODUCTS;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,LENGTH(CUSTOMERNAME) AS `LENGTH OF NAME`FROM CUSTOMERS;

USE LIBRARYDB;
SELECT TRIM(TITLE) AS `TRIMMED TITLES` FROM BOOKS;

USE STUDENTDB;
SELECT CONCAT(STUDENTNAME,' ',DEPARTMENT) AS `NAME WITH DEPARTMENT`FROM STUDENTS;

USE EMPLOYEEDB;
SELECT CONCAT(EMPLOYEENAME,'-',SALARY) AS `NAME WITH SALARY` FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT CONCAT(PRODUCTNAME,'-',BRAND) AS `NAME WITH BRAND` FROM PRODUCTS;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,CONCAT(CITY,',',STATE) AS `PLACE`FROM CUSTOMERS;

USE COURSEDB;
SELECT CONCAT(COURSENAME,',',DEPARTMENT) AS `COURSE` FROM COURSES;

USE STUDENTDB;
SELECT STUDENTNAME,LEFT(STUDENTNAME,1) AS `1ST LETTER` FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,RIGHT(EMPLOYEENAME,1) AS `LAST LETTER` FROM EMPLOYEES;




SELECT CURRENT_DATE();                         #DATE & TIME EXPRESSIONS

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT NOW();

USE EMPLOYEEDB;
SELECT JOININGDATE,JOININGDATE+INTERVAL 30 DAY AS `30 DAYS AFTER JOINING` FROM EMPLOYEES;

SELECT JOININGDATE,JOININGDATE+INTERVAL 90 DAY AS `90 DAYS AFTER JOINING` FROM EMPLOYEES;

USE HOSPITALDB;
SELECT ADMISSIONDATE, ADMISSIONDATE+INTERVAL 7 DAY  AS `1 WEEK AFTER ADMISSION` FROM PATIENTS;

USE ECOMMERCEDB;
SELECT REGISTEREDDATE, REGISTEREDDATE-INTERVAL 42 DAY AS `42 DAYS BEFORE REGISTRATION` FROM CUSTOMERS;

USE SHOPPINGDB;
SELECT PRODUCTNAME,MANUFACTURINGDATE,MANUFACTURINGDATE+ INTERVAL 126 DAY AS `126 DAYS AFTER MANUFACTURING` FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT DATE_FORMAT(JOININGDATE ,'%d-%m-%Y') AS `JOINING DATE` FROM EMPLOYEES;

USE ECOMMERCEDB;
SELECT DATE_FORMAT(REGISTEREDDATE, '%m/%d/%Y') AS `REGISTERED DATE` FROM CUSTOMERS;

USE SHOPPINGDB;
SELECT DATE_FORMAT(MANUFACTURINGDATE,'%d-%M-%Y')AS `MANUFACTURING DATE` FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT DATE_FORMAT(JOININGDATE ,'%Y') AS `JOINING YEAR` FROM EMPLOYEES;

USE ECOMMERCEDB;
SELECT DATE_FORMAT(REGISTEREDDATE, '%M') AS `REGISTERED MONTH` FROM CUSTOMERS;

USE SHOPPINGDB;
SELECT DATE_FORMAT(MANUFACTURINGDATE,'%D %W')AS `MANUFACTURED DAY` FROM PRODUCTS;




USE EMPLOYEEDB;
SELECT SUM(SALARY) AS `TOTAL SALARY` FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY),2) AS `AVERAGE SALARY` FROM EMPLOYEES;

SELECT MAX(SALARY) AS `HIGHLY PAID EMPLOYEE` FROM EMPLOYEES;

SELECT MIN(SALARY) AS `LEAST PAID EMPLOYEE` FROM EMPLOYEES;

SELECT COUNT(EMPLOYEEID) AS `TOTAL NUMBER OF EMPLOYEES` FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT SUM(PRICE*AVAILABLESTOCK) AS `TOTAL VALUE OF ALL PRODUCTS` FROM PRODUCTS;

SELECT ROUND(AVG(PRICE),2) AS `AVERAGE PRICE PRODUCTS` FROM PRODUCTS;

USE LIBRARYDB;
SELECT MAX(PRICE) AS `COSTLIEST BOOK` FROM BOOKS;

USE COURSEDB;
SELECT MIN(FEES) AS `LOW FEE COURSE` FROM COURSES;

USE SHOPPINGDB;
SELECT COUNT(PRODUCTID) FROM PRODUCTS
WHERE PRICE>10000.00;




USE EMPLOYEEDB;                           #EXPRESSION WITH ALIAS
SELECT EMPLOYEENAME, SALARY AS `MONTHLY SALARY` FROM EMPLOYEES;

SELECT EMPLOYEENAME, SALARY*12 AS `ANNUAL SALARY` FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE,ROUND(PRICE-(PRICE*DISCOUNT/100),2) AS `DISCOUNTED PRICE` FROM PRODUCTS;

SELECT PRODUCTNAME,PRICE,ROUND(PRICE*1.18,2) AS `FINAL PRICE` FROM PRODUCTS;

USE COURSEDB;
SELECT COURSENAME,FEES,ROUND(FEES-(FEES*DISCOUNT/100),2) AS `FINAL FEES` FROM COURSES;

USE STUDENTDB;
SELECT STUDENTNAME,LENGTH(STUDENTNAME) AS `NAME LENGTH`FROM STUDENTS;

USE EMPLOYEEDB;                                                 
SELECT EMPLOYEENAME,SALARY,ROUND(SALARY*1.10,2) AS `INCREMENTED SALARY` FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,AVAILABLESTOCK,PRICE,(AVAILABLESTOCK*PRICE) AS `TOTAL VALUE` FROM PRODUCTS;
