USE EMPLOYEEDB;                                #GROUP BY
SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE STUDENTDB;
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY DEPARTMENT;

USE SHOPPINGDB;
SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS
GROUP BY CATEGORY;

USE ECOMMERCEDB;
SELECT CITY, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY CITY;

USE EMPLOYEEDB;
SELECT DESIGNATION, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DESIGNATION;

USE COURSEDB;
SELECT COURSENAME, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY COURSENAME;

USE EMPLOYEEDB;
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE EMPLOYEEDB;
SELECT DEPARTMENT, ROUND(AVG(SALARY),2) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE EMPLOYEEDB;
SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE EMPLOYEEDB;
SELECT DEPARTMENT, MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE SHOPPINGDB;
SELECT CATEGORY, SUM(AVAILABLESTOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY;

USE SHOPPINGDB;
SELECT CATEGORY, ROUND(AVG(PRICE),2) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

USE SHOPPINGDB;
SELECT CATEGORY, MIN(PRICE) AS MINIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

USE SHOPPINGDB;
SELECT CATEGORY, MAX(PRICE) AS MAXIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

USE COURSEDB;
SELECT DEPARTMENT, SUM(FEES) AS TOTAL_FEES
FROM COURSES
GROUP BY DEPARTMENT;

USE COURSEDB;
SELECT DEPARTMENT, ROUND(AVG(FEES),2) AS AVERAGE_FEES
FROM COURSES
GROUP BY DEPARTMENT;

USE ECOMMERCEDB;
SELECT CITY, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY CITY;

USE AUG28DB;
SELECT PRODUCTID, SUM(AVAILABLESTOCK) AS TOTAL_QUANTITY
FROM ORDERS
GROUP BY PRODUCTID;

USE AUG28DB;
SELECT CUSTOMERID, SUM(AVAILABLESTOCK * PRICE) AS TOTAL_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMERID;

USE EMPLOYEEDB;
SELECT YEAR(JOININGDATE) AS JOINING_YEAR, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY YEAR(JOININGDATE);




USE EMPLOYEEDB;                                #GROUP BY WITH COUNT()
SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE STUDENTDB;
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY DEPARTMENT;

USE SHOPPINGDB;
SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS
GROUP BY CATEGORY;

USE ECOMMERCEDB;
SELECT CITY, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY CITY;

USE EMPLOYEEDB;
SELECT DESIGNATION, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DESIGNATION;

USE AUG28DB;
SELECT COURSEID, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY COURSEID;

USE AUG28DB;
SELECT CUSTOMERID, COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY CUSTOMERID;

USE AUG28DB;
SELECT PRODUCTID, COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY PRODUCTID;

USE EMPLOYEEDB;
SELECT YEAR(JOININGDATE) AS HIRING_YEAR, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY YEAR(JOININGDATE);

USE STUDENTDB;
SELECT GENDER, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY GENDER;

USE SHOPPINGDB;
SELECT BRAND, COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS
GROUP BY BRAND;

USE ECOMMERCEDB;
SELECT STATE, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY STATE;

USE EMPLOYEEDB;
SELECT EXPERIENCE_LEVEL, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY EXPERIENCE_LEVEL;

USE LIBRARYDB;
SELECT AUTHOR, COUNT(*) AS BOOK_COUNT
FROM BOOKS
GROUP BY AUTHOR;

USE COURSEDB;
SELECT COURSENAME, COUNT(*) AS COURSE_COUNT
FROM COURSES
GROUP BY COURSENAME;




USE EMPLOYEEDB;                                   #GROUP BY WITH SUM()
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE AUG28DB;
SELECT CUSTOMERID, SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM ORDERS
GROUP BY CUSTOMERID;

USE SHOPPINGDB;
SELECT PRODUCTID, SUM(AVAILABLESTOCK) AS TOTAL_QUANTITY
FROM PRODUCTS
GROUP BY PRODUCTID;

USE SHOPPINGDB;
SELECT CATEGORY, SUM(AVAILABLESTOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, SUM(PRICE * AVAILABLESTOCK) AS TOTAL_PRODUCT_VALUE
FROM PRODUCTS
GROUP BY CATEGORY;

USE COURSEDB;
SELECT DEPARTMENT, SUM(FEES) AS TOTAL_FEES
FROM COURSES
GROUP BY DEPARTMENT;

USE EMPLOYEEDB;
SELECT DESIGNATION, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DESIGNATION;

USE AUG28DB;
SELECT CITY, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM ORDERS
GROUP BY CITY;

USE AUG28DB;
SELECT MONTH(ORDER_DATE) AS ORDER_MONTH, SUM(ORDER_AMOUNT) AS TOTAL_ORDER_AMOUNT
FROM ORDERS
GROUP BY MONTH(ORDER_DATE);

USE AUG28DB;
SELECT CATEGORY, SUM(ORDERID) AS TOTAL_QUANTITY_SOLD
FROM ORDERS
GROUP BY CATEGORY;

USE SHOPPINGDB;
SELECT BRAND, SUM(PRICE * AVAILABLESTOCK) AS TOTAL_INVENTORY_VALUE
FROM PRODUCTS
GROUP BY BRAND;

USE EMPLOYEEDB;
SELECT YEAR(JOININGDATE) AS JOINING_YEAR, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY YEAR(JOININGDATE);

USE AUG28DB;
SELECT CUSTOMERID, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM ORDERS
GROUP BY CUSTOMERID;

USE COURSEDB;
SELECT COURSEID, SUM(FEES) AS TOTAL_FEES
FROM COURSES
GROUP BY COURSEID;

USE AUG28DB;
SELECT CUSTOMERID, SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS
GROUP BY CUSTOMERID;




USE EMPLOYEEDB;                      #GROUP BY WITH AVG(),MIN(),MAX()
SELECT DEPARTMENT, ROUND(AVG(SALARY),2) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;

USE SHOPPINGDB;
SELECT CATEGORY, ROUND(AVG(PRICE),2) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, MAX(PRICE) AS MAXIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

SELECT CATEGORY, MIN(PRICE) AS MINIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

USE STUDENTDB;
SELECT DEPARTMENT, AVG(MARK) AS AVERAGE_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MAX(MARK) AS HIGHEST_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, MIN(MARK) AS LOWEST_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

USE COURSEDB;
SELECT COURSENAME, ROUND(AVG(FEES),2) AS AVERAGE_FEES
FROM COURSES
GROUP BY COURSENAME;

SELECT COURSENAME, MAX(FEES) AS HIGHEST_FEES
FROM COURSES
GROUP BY COURSENAME;

SELECT COURSENAME, MIN(FEES) AS LOWEST_FEES
FROM COURSES
GROUP BY COURSENAME;

USE AUG28DB;
SELECT CUSTOMERID, AVG(ORDER_AMOUNT) AS AVERAGE_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMERID;

SELECT CUSTOMERID, MAX(ORDER_AMOUNT) AS HIGHEST_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMERID;

SELECT CUSTOMERID, MIN(ORDER_AMOUNT) AS LOWEST_ORDER_AMOUNT
FROM ORDERS
GROUP BY CUSTOMERID;



USE EMPLOYEEDB;                                                      #HAVING
SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*)>5;

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*)<5;

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*)=5;

SELECT DEPARTMENT, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>50000;

SELECT DEPARTMENT, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY)<40000;

SELECT DEPARTMENT, MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING MAX(SALARY)>100000;

SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING MIN(SALARY)>30000;

USE SHOPPINGDB;
SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS
GROUP BY CATEGORY
HAVING COUNT(*)>10;

SELECT CATEGORY, ROUND(AVG(PRICE),2) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
HAVING AVG(PRICE)>5000;

SELECT CATEGORY, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY
HAVING SUM(AVAILABLESTOCK)>1000;

USE ECOMMERCEDB;
SELECT CITY, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY CITY
HAVING COUNT(*)>20;

USE AUG28DB;
SELECT CUSTOMERID, COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY CUSTOMERID
HAVING COUNT(*)>5;

SELECT PRODUCTID, COUNT(*) AS ORDER_COUNT
FROM ORDERS
GROUP BY PRODUCTID
HAVING COUNT(*)>10;

USE EMPLOYEEDB;
SELECT DEPARTMENTID, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENTID
HAVING SUM(SALARY)>500000;

USE STUDENTDB;
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY DEPARTMENT
HAVING COUNT(*)>30;




USE EMPLOYEEDB;									#WHERE + GROUP BY + HAVING
SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
WHERE SALARY > 30000.00
GROUP BY DEPARTMENT
HAVING COUNT(*)>5;

SELECT DEPARTMENT, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
WHERE EXPERIENCE>2
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>50000.00;

USE AUG28DB;
SELECT CUSTOMERID, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM ORDERS
WHERE SALES_AMOUNT>1000.00
GROUP BY CUSTOMERID
HAVING SUM(SALES_AMOUNT)>10000.00;

USE SHOPPINGDB;
SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS
WHERE PRICE>500.00
GROUP BY CATEGORY
HAVING COUNT(*)>5;

USE STUDENTDB;
SELECT DEPARTMENT, AVG(MARKS) AS AVERAGE_MARKS
FROM STUDENTS
WHERE MARKS>40
GROUP BY DEPARTMENT
HAVING AVG(MARKS)>70;

USE SHOPPINGDB;
SELECT CATEGORY, SUM(AVAILABLESTOCK) AS TOTAL_STOCK
FROM PRODUCTS
WHERE AVAILABLESTOCK>10
GROUP BY CATEGORY
HAVING SUM(AVAILABLESTOCK)>500.00;

USE ECOMMERCEDB;
SELECT CITY, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
WHERE AGE>18
GROUP BY CITY
HAVING COUNT(*)>10;

USE COURSEDB;
SELECT DEPARTMENT, AVG(FEES) AS AVERAGE_FEES
FROM COURSES
WHERE FEES>20000.00
GROUP BY DEPARTMENT
HAVING AVG(FEES)>30000.00;

USE AUG28DB;
SELECT CUSTOMERID, COUNT(*) AS ORDER_COUNT
FROM ORDERS
WHERE ORDER_AMOUNT>5000.00
GROUP BY CUSTOMERID
HAVING COUNT(*)>3;

USE EMPLOYEEDB;
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE SALARY>40000.00
GROUP BY DEPARTMENT
HAVING SUM(SALARY)>300000.00;




USE EMPLOYEEDB;                                 #GROUP BY MULTIPLE COLUMNS
SELECT DEPARTMENT, DESIGNATION, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT, DESIGNATION;

SELECT DEPARTMENT, DESIGNATION, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT, DESIGNATION;

USE STUDENTDB;
SELECT DEPARTMENT, GENDER, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY DEPARTMENT, GENDER;

SELECT DEPARTMENT, GENDER, AVG(MARK) AS AVERAGE_MARKS
FROM STUDENTS
GROUP BY DEPARTMENTID, GENDER;

USE SHOPPINGDB;
SELECT CATEGORY, BRAND, COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS
GROUP BY CATEGORY, BRAND;

SELECT CATEGORY, BRAND, AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY, BRAND;

USE AUG28DB;
SELECT CUSTOMERID, CITY, SUM(SALES_AMOUNT) AS TOTAL_SALES
FROM ORDERS
GROUP BY CUSTOMERID, CITY;

SELECT CUSTOMERID, PRODUCTID, SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS
GROUP BY CUSTOMERID, PRODUCTID;

USE ECOMMERCEDB;
SELECT CITY, STATE, COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS
GROUP BY CITY, STATE;

USE EMPLOYEEDB;
SELECT DEPARTMENT, DESIGNATION, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT, DESIGNATION
HAVING SUM(SALARY)>200000.00;




















































































































































































































