USE STUDENTDB;                                              #IN OPERATOR

SELECT * FROM STUDENTS
WHERE DEPARTMENT IN ('BA','BBA','VISCOM');

USE EMPLOYEEDB;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN ('IT','HR','FINANCE');

USE HOSPITALDB;

SELECT * FROM PATIENTS
WHERE BLOODGROUP IN ('A POSITIVE','B POSITIVE','O POSITIVE');

USE LIBRARYDB;

SELECT * FROM BOOKS
WHERE CATEGORY IN ('HORROR','DRAMA','FANTASY');

USE SHOPPINGDB;

SELECT * FROM PRODUCTS
WHERE CATEGORY IN ('ELECTRONIC', 'FURNITURE', 'ACCESSORIES');

USE COURSESDB;

SELECT * FROM STUDENTCOURSES
WHERE DEPARTMENT IN ('IT','CSE','ECE');

USE MOVIEDB;

SELECT * FROM MOVIES
WHERE `LANGUAGE` IN ('TAMIL','ENGLISH','HINDI');

USE HOTELDB;

SELECT * FROM ROOMS
WHERE ROOMTYPE IN ('SINGLE ROOM','DOUBLE ROOM');

USE ECOMMERCEDB;

SELECT * FROM CUSTOMERS
WHERE CITY IN ('CHENNAI','COIMBATORE','MADURAI');

USE EMPLOYEEDB;

SELECT * FROM employees
WHERE DESIGNATION IN ('DEVELOPER','TESTER','MARKETING HEAD');




USE STUDENTDB;                                              #NOT IN OPERATOR

SELECT * FROM STUDENTS
WHERE DEPARTMENT NOT IN ('BA','IT','VISCOM');

USE EMPLOYEEDB;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT NOT IN ('ACCOUNTS','HR','FINANCE');

USE HOSPITALDB;

SELECT * FROM PATIENTS
WHERE BLOODGROUP NOT IN ('A POSITIVE','B POSITIVE','O POSITIVE');

USE LIBRARYDB;

SELECT * FROM BOOKS
WHERE CATEGORY NOT IN ('HORROR','HISTORY');

USE SHOPPINGDB;

SELECT * FROM PRODUCTS
WHERE CATEGORY NOT IN ('ELECTRONIC','ACCESSORIES');

USE COURSESDB;

SELECT * FROM STUDENTCOURSES
WHERE DEPARTMENT NOT IN ('IT','CSE');

USE MOVIEDB;

SELECT * FROM MOVIES
WHERE `LANGUAGE` NOT IN ('TAMIL','ENGLISH');

USE HOTELDB;

SELECT * FROM ROOMS
WHERE ROOMTYPE NOT IN ('SINGLE ROOM','DOUBLE ROOM');

USE ECOMMERCEDB;

SELECT * FROM CUSTOMERS
WHERE CITY NOT IN ('CHENNAI','COIMBATORE');

USE EMPLOYEEDB;

SELECT * FROM employees
WHERE DESIGNATION NOT IN ('DEVELOPER','TESTER','ANALYST');




USE STUDENTDB;                                           #IN WITH NUMERIC VALUES

SELECT * FROM STUDENTS
WHERE STUDENTID IN (001,005,010);

USE EMPLOYEEDB;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID IN (001,005,010);

USE SHOPPINGDB;

SELECT * FROM PRODUCTS
WHERE PRODUCTID IN (001,005,009);

USE LIBRARYDB;

SELECT * FROM BOOKS
WHERE PRICE IN (500.00,700.00,1200.00);

USE HOTELDB;

SELECT * FROM ROOMS
WHERE ROOMNUMBER IN (101,202,305);



USE STUDENTDB;                                           #NOT IN WITH NUMERIC VALUES

SELECT * FROM STUDENTS
WHERE STUDENTID NOT IN (001,005,010);

USE EMPLOYEEDB;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID NOT IN (001,005,010);

USE SHOPPINGDB;

SELECT * FROM PRODUCTS
WHERE PRODUCTID NOT IN (001,005,009);

USE LIBRARYDB;

SELECT * FROM BOOKS
WHERE PRICE NOT IN (500.00,750.00,1000.00);

USE HOTELDB;

SELECT * FROM ROOMS
WHERE ROOMNUMBER NOT IN (101,205,301);




USE EMPLOYEEDB;                                       #IN/NOT IN WITH CONDITIONS

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN ('SALES','IT','ACCOUNTS') AND SALARY>40000.00;

USE STUDENTDB;                                       

SELECT * FROM STUDENTS
WHERE DEPARTMENT IN ('BA','BBA','VISCOM') AND AGE>20;

USE SHOPPINGDB;

SELECT * FROM PRODUCTS
WHERE CATEGORY IN ('FURNITURE', 'TECHNOLOGY') AND PRICE>20000.00;

USE LIBRARYDB;

SELECT * FROM BOOKS
WHERE CATEGORY IN ('HORROR','BIOGRAPHY') AND PRICE<1000.00;

USE ECOMMERCEDB;

SELECT * FROM CUSTOMERS
WHERE CITY IN ('CHENNAI','MADURAI','HYDERABAD') AND REGISTEREDDATE IS NOT NULL;

USE EMPLOYEEDB;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT NOT IN ('HR','FINANCE') AND SALARY>30000.00;

USE STUDENTDB;                                       

SELECT * FROM STUDENTS
WHERE DEPARTMENT NOT IN ('IT','CSE') AND AGE>21;

USE SHOPPINGDB;

SELECT * FROM PRODUCTS
WHERE CATEGORY NOT IN ('TECHNOLOGY','FURNITURE') AND AVAILABLESTOCK>10;

USE MOVIEDB;

SELECT * FROM MOVIES
WHERE `LANGUAGE` IN ('TAMIL','ENGLISH','HINDI') AND RATING>4;

USE HOSPITALDB;

SELECT * FROM PATIENTS
WHERE BLOODGROUP IN ('A POSITIVE','B POSITIVE','O POSITIVE') AND AGE>30;
