USE STUDENTDB;                                       #IS NULL
SELECT * FROM STUDENTS
WHERE EMAIL IS NULL;
SELECT * FROM STUDENTS
WHERE MOBILENUMBER IS NULL;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IS NULL;
SELECT * FROM EMPLOYEES
WHERE EMAIL IS NULL;

USE HOSPITALDB;
SELECT * FROM PATIENTS 
WHERE DISEASE IS NULL;
SELECT * FROM PATIENTS 
WHERE DOCTORNAME IS NULL;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PUBLISHEDYEAR IS NULL;
SELECT * FROM BOOKS
WHERE AUTHOR IS NULL;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IS NULL;
SELECT * FROM PRODUCTS
WHERE MANUFACTURINGDATE IS NULL;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE EMAIL IS NULL;
SELECT * FROM CUSTOMERS
WHERE COUNTRY IS NULL;





USE STUDENTDB;                                       #IS NOT NULL
SELECT * FROM STUDENTS
WHERE EMAIL IS NOT NULL;
SELECT * FROM STUDENTS
WHERE DEPARTMENT IS NOT NULL;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE SALARY IS NOT NULL;
SELECT * FROM EMPLOYEES
WHERE EMAIL IS NOT NULL;

USE HOSPITALDB;
SELECT * FROM PATIENTS 
WHERE DISEASE IS NOT NULL;
SELECT * FROM PATIENTS 
WHERE DOCTORNAME IS NOT NULL;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE AUTHOR IS NOT NULL;
SELECT * FROM BOOKS
WHERE PRICE IS NOT NULL;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IS NOT NULL;
SELECT * FROM PRODUCTS
WHERE MANUFACTURINGDATE IS NOT NULL;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE EMAIL IS NOT NULL;
SELECT * FROM CUSTOMERS
WHERE COUNTRY IS NOT NULL;




USE STUDENTDB;                                       #IS NULL WITH CONDITIONS
SELECT * FROM STUDENTS
WHERE EMAIL IS NULL AND DEPARTMENT = 'BBA';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IS NULL AND SALARY>30000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS 
WHERE DISEASE IS NULL AND AGE>25;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IS NULL AND PRICE>5000.00;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE EMAIL IS NULL AND CITY='CHENNAI';






USE STUDENTDB;                                       #IS NOT NULL WITH CONDITIONS
SELECT * FROM STUDENTS
WHERE EMAIL IS NOT NULL AND DEPARTMENT = 'VISCOM';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IS NOT NULL AND SALARY>40000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS 
WHERE DISEASE IS NOT NULL AND AGE>30;

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE AUTHOR IS NOT NULL AND PRICE<1000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IS NOT NULL AND AVAILABLESTOCK>10;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE EMAIL IS NOT NULL AND CITY='CHENNAI';




USE STUDENTDB;                                       #MIXED
SELECT * FROM STUDENTS
WHERE EMAIL IS NULL OR DEPARTMENT = 'VISCOM';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMAIL IS NOT NULL AND DEPARTMENT IN ('IT','SALES');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IS NULL OR DISCOUNT IS NULL;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE EMAIL IS NOT NULL AND COUNTRY IS NOT NULL;

USE HOSPITALDB;
SELECT * FROM PATIENTS 
WHERE DISEASE IS NULL AND PHONE IS NOT NULL;


