USE STUDENTDB;                                                     #LIKE WITH %
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'A%';

SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE '%A';

SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE '%AN%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE 'R%';

SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE '%N';

SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE '%AR%';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE PATIENTNAME LIKE '%P';

SELECT * FROM PATIENTS
WHERE PATIENTNAME LIKE '%I';

SELECT * FROM PATIENTS
WHERE DISEASE LIKE 'FEVER';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE 'S%';

SELECT * FROM BOOKS
WHERE TITLE LIKE '%SQL';

SELECT * FROM BOOKS
WHERE TITLE LIKE '%DATA%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE 'M%';

SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%PHONE';

SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%BOOK%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'K%';

SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%A';

SELECT * FROM CUSTOMERS
WHERE CITY LIKE '%PUR%';

USE COURSEDB;
SELECT * FROM COURSES
WHERE COURSENAME LIKE '%DATA%';

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE TITLE LIKE 'THE%';




USE STUDENTDB;                                                     #LIKE WITH _
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE '_____';

SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE '______';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE '_____';

SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE 'A____';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE PATIENTNAME LIKE '____';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE '_____';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '______';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '_____';

USE STUDENTDB;                                                 
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE '_A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE '_R%';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE PATIENTNAME LIKE '__I%';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE '_O%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '_A%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '_A%';

USE STUDENTDB;                                                 
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'AK%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE 'R_H%';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE 'S_L%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE 'M__I%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'K%A';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE '_______';




USE STUDENTDB;                                                     #COMBINING % & _
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE 'R_H%';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE PATIENTNAME LIKE 'P%A';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE 'S%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE 'M%E';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'K%A';

USE STUDENTDB;                                                     
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE '_A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE '_R%N';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE 'D%SQL%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%PHONE%';




USE STUDENTDB;                                                     #NOT LIKE
SELECT * FROM STUDENTS
WHERE STUDENTNAME NOT LIKE 'A%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME NOT LIKE '%N';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE DISEASE NOT LIKE 'FEVER';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE NOT LIKE 'S%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME NOT LIKE '%PHONE%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME NOT LIKE '%A';

USE COURSEDB;
SELECT * FROM COURSES
WHERE COURSENAME NOT LIKE '%DATA%';

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE TITLE NOT LIKE 'THE%';

USE STUDENTDB;                                                     
SELECT * FROM STUDENTS
WHERE STUDENTNAME NOT LIKE '%AN%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME NOT LIKE 'R%';




USE STUDENTDB;                                             #LIKE WITH OTHER CONDITIONS
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'A%'
AND AGE>20;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE 'R%'
AND SALARY>40000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE PATIENTNAME  LIKE 'P%'
AND AGE BETWEEN 20 AND 40;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE '%SQL%'
AND PRICE<1000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%PHONE%'
AND PRICE>5000.00;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CUSTOMERNAME  LIKE 'K%'
AND CITY = 'CHENNAI';

USE STUDENTDB;                                          
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'A%'
AND DEPARTMENT='IT';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE '%AR%'
AND DEPARTMENT='IT';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND LIKE 'S%'
AND CATEGORY='ELECTRONICS';

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE TITLE LIKE 'M%'
AND `LANGUAGE`='TAMIL';





USE STUDENTDB;                                        #MIXED LIKE & WILDCARD CHALLENGE
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'A%A';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE 'S%'
AND EMPLOYEENAME LIKE '%R%';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE PATIENTNAME LIKE '%RI%';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE '%DATA%';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE 'SMART%';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY LIKE '%PUR';

USE COURSEDB;
SELECT * FROM COURSES
WHERE COURSENAME LIKE 'DATA%' 
AND COURSENAME LIKE '%SCIENCE%';

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE TITLE LIKE '%LOVE%';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE 'A_____';

USE STUDENTDB;                                        
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE '____A';