USE STUDENTDB;                                      #AND OPERATOR
SELECT * FROM STUDENTS
WHERE DEPARTMENT='BA' AND AGE>18;

SELECT * FROM STUDENTS
WHERE AGE BETWEEN 18 AND 25 AND GENDER='FEMAILE';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT='IT' AND SALARY>40000.00;

SELECT * FROM EMPLOYEES
WHERE DESIGNATION='DEVELOPER' AND SALARY>50000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE>30 AND GENDER='FEMALE';

SELECT * FROM PATIENTS
WHERE BLOODGROUP='O POSITIVE' AND DISEASE='FEVER';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY='TECHNOLOGY' AND PRICE>500.00;

SELECT * FROM BOOKS
WHERE CATEGORY='TECHNOLOGY' AND PRICE BETWEEN 500.00 AND 1000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS' AND PRICE>10000.00;

SELECT * FROM PRODUCTS
WHERE AVAILABLESTOCK>10 AND PRICE<50000.00;

USE COURSEDB;
SELECT * FROM COURSES
WHERE DEPARTMENT='CSE'AND FEES>30000.00;

SELECT * FROM COURSES
WHERE COURSEDURATION='6 MONTHS'AND FEES<50000.00;

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE `LANGUAGE`='TAMIL' AND RATING>4.0;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY = 'CHENNAI' AND COUNTRY = 'INDIA';

USE STUDENTDB;                              
SELECT * FROM STUDENTS
WHERE AGE BETWEEN 18 AND 25 AND DEPARTMENT='CSE';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT='IT' AND SALARY BETWEEN 40000.00 AND 70000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY='TECHNOLOGY' AND BRAND='SAMSUNG';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE AUTHOR='JOHN' AND PRICE>500.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE AGE>25 AND DISEASE IS NOT NULL;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY = 'CHENNAI' AND EMAIL IS NOT NULL;




USE STUDENTDB;                                      #OR OPERATOR
SELECT * FROM STUDENTS
WHERE DEPARTMENT='BA' OR DEPARTMENT='BBA';

SELECT * FROM STUDENTS
WHERE AGE<18 OR AGE>25;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = 'IT' OR DEPARTMENT = 'HR';

SELECT * FROM EMPLOYEES
WHERE SALARY<30000.00 OR SALARY>60000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE BLOODGROUP='A POSITIVE' OR BLOODGROUP='O POSITIVE';

SELECT * FROM PATIENTS
WHERE DISEASE='FEVER' OR DISEASE='COLD';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY='TECHNOLOGY' OR CATEGORY='SCIENCE';

SELECT * FROM BOOKS
WHERE PRICE<500.00 OR PRICE>1500.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY='TECHNOLOGY' OR CATEGORY='ACCESSORIES';

SELECT * FROM PRODUCTS
WHERE PRICE>50000.00 OR AVAILABLESTOCK<5;

USE COURSEDB;
SELECT * FROM COURSES
WHERE DEPARTMENT='CSE'OR DEPARTMENT='IT';

SELECT * FROM COURSES
WHERE FEES<25000.00 OR FEES>75000.00;

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE `LANGUAGE`='TAMIL' OR `LANGUAGE`='ENGLISH';

SELECT * FROM MOVIES
WHERE RATING<3.0 OR RATING>4.5;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY = 'CHENNAI' OR CITY = 'BANGLORE';

USE STUDENTDB;                                 
SELECT * FROM STUDENTS
WHERE DEPARTMENT='CSE' OR AGE>22;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DESIGNATION = 'TESTER' OR DESIGNATION = 'DEVELOPER';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND='SAMSUNG' OR BRAND='APPLE';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY='TECHNOLOGY' OR PRICE>1000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE BLOODGROUP='O NEGATIVE' OR AGE>50;




USE STUDENTDB;                                      #NOT OPERATOR
SELECT * FROM STUDENTS
WHERE NOT DEPARTMENT='IT';

SELECT * FROM STUDENTS
WHERE NOT AGE>20;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE NOT DEPARTMENT='HR';

SELECT * FROM EMPLOYEES
WHERE NOT DESIGNATION='DEVELOPER';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE NOT GENDER='MALE';

SELECT * FROM PATIENTS
WHERE NOT BLOODGROUP='O POSITIVE';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE NOT CATEGORY='TECHNOLOGY';

SELECT * FROM BOOKS
WHERE NOT PRICE BETWEEN 500.00 AND 1000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE NOT CATEGORY='ELECTRONICS';

SELECT * FROM PRODUCTS
WHERE NOT PRICE>10000.00;

USE COURSEDB;
SELECT * FROM COURSES
WHERE NOT DEPARTMENT='CSE';

SELECT * FROM COURSES
WHERE NOT FEES BETWEEN 30000.00 AND 60000.00;

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE NOT `LANGUAGE`='TAMIL';

SELECT * FROM MOVIES
WHERE NOT RATING>4.0;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE NOT CITY = 'CHENNAI';

USE STUDENTDB;                                  
SELECT * FROM STUDENTS
WHERE NOT DEPARTMENT='CSE' AND AGE>20;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE NOT DEPARTMENT='IT' AND SALARY>30000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE NOT CATEGORY='ELECTRONICS' AND AVAILABLESTOCK>10;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE NOT CATEGORY='TECHNOLOGY' OR PRICE>1000.00;

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE NOT DISEASE='FEVER';





USE STUDENTDB;                                      #MIXED LOGICAL OPERATOR
SELECT * FROM STUDENTS
WHERE DEPARTMENT='IT' 
AND AGE>20 
OR DEPARTMENT='CSE';

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT='IT' 
AND SALARY>50000.00 
OR DESIGNATION='MANAGER';

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS' 
AND PRICE>10000.00 
OR BRAND='APPLE';

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY='TECHNOLOGY'
AND PRICE>500.00 
OR AUTHOR='JOHN';

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE GENDER='FEMALE' 
AND AGE>30 
OR BLOODGROUP='O POSITIVE';

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE  CITY = 'CHENNAI' 
AND EMAIL IS NOT NULL 
OR CITY = 'BANGLORE';

USE STUDENTDB;                              
SELECT * FROM STUDENTS
WHERE DEPARTMENT='IT' 
OR DEPARTMENT='CSE'
AND AGE>20 ;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT='IT' 
OR DEPARTMENT='HR'
AND SALARY>40000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS' 
OR CATEGORY='ACCESSORIES' 
AND PRICE BETWEEN 5000.00 AND 50000.00;

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE `LANGUAGE`='TAMIL'
OR `LANGUAGE`='ENGLISH'
AND RATING>4.0;



USE STUDENTDB;                         #LOGICAL OPERATORS WITH NULL,IN,BETWEEN & LIKE
SELECT * FROM STUDENTS
WHERE DEPARTMENT='IT' 
AND EMAIL IS NOT NULL;   

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT='IT' 
OR EMAIL IS NULL;    

USE HOSPITALDB;
SELECT * FROM PATIENTS
WHERE BLOODGROUP='A POSITIVE'
OR BLOODGROUP='B POSITIVE'
AND AGE>25;  

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY='TECHNOLOGY' 
OR CATEGORY='SCIENCE'
AND PRICE BETWEEN 500.00 AND 1500.00;  

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IS NOT NULL  
AND PRICE>10000.00; 

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE  CITY = 'CHENNAI' 
OR CITY = 'COIMBATORE'
AND EMAIL IS NOT NULL;

USE STUDENTDB;                                      
SELECT * FROM STUDENTS
WHERE STUDENTNAME LIKE 'A%' 
AND AGE>20 ;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEENAME LIKE '%AN%'
OR SALARY>50000.00;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%PHONE%'
AND PRICE BETWEEN 5000.00 AND 50000.00;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE TITLE LIKE 'S%' 
OR CATEGORY='TECHNOLOGY';



