SELECT EMPLOYEENAME,SALARY,
ROUND(SALARY,2) AS ROUNDED_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEENAME,SALARY,
ABS(SALARY - 50000)
FROM EMPLOYEES;

SELECT PRODUCTNAME,PRICE,
CEIL(PRICE) 
FROM PRODUCTS;

SELECT PRODUCTNAME,PRICE,
FLOOR(PRICE) 
FROM PRODUCTS;

SELECT EMPLOYEENAME,SALARY,
MOD(SALARY,10000) AS ABS_REMAINDER
FROM EMPLOYEES;

SELECT STUDENTNAME,MARKS,
POWER(MARKS,2) 
FROM STUDENTS;

SELECT PRODUCTNAME,PRICE,
SQRT(PRICE) 
FROM PRODUCTS;

SELECT PRODUCTNAME,PRICE,
ROUND(PRICE,2) AS ROUNDED_PRICE
FROM PRODUCTS;