USE STUDENTDB;                                  #ORDER BY SINGLE COLUMN
SELECT * FROM STUDENTS
ORDER BY STUDENTNAME ASC;

SELECT * FROM STUDENTS
ORDER BY STUDENTNAME DESC;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
ORDER BY SALARY ASC;

SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
ORDER BY PRICE ASC;

SELECT * FROM PRODUCTS
ORDER BY PRICE DESC;

USE LIBRARYDB;
SELECT * FROM BOOKS
ORDER BY PRICE ASC;

SELECT * FROM BOOKS
ORDER BY PRICE DESC;

USE STUDENTDB;
SELECT * FROM STUDENTS
ORDER BY AGE ASC;

SELECT * FROM STUDENTS
ORDER BY AGE DESC;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
ORDER BY JOININGDATE ASC;

SELECT * FROM EMPLOYEES
ORDER BY JOININGDATE DESC;

USE COURSEDB;
SELECT * FROM COURSES
ORDER BY FEES ASC;

SELECT * FROM COURSES
ORDER BY FEES DESC;

USE MOVIEDB;
SELECT * FROM MOVIES
ORDER BY RATING DESC;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
ORDER BY CITY ASC;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
ORDER BY AVAILABLESTOCK DESC;

USE HOSPITALDB;
SELECT * FROM PATIENTS
ORDER BY AGE ASC;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
ORDER BY EXPERIENCE DESC;

USE LIBRARYDB;
SELECT * FROM BOOKS
ORDER BY PUBLISHEDYEAR ASC;




USE EMPLOYEEDB;                                 #ORDER BY WITH WHERE
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT='IT'
ORDER BY SALARY ASC;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT='IT'
ORDER BY SALARY DESC;

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE DEPARTMENT='CSE'
ORDER BY AGE DESC;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS'
ORDER BY PRICE ASC;

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE>500.00
ORDER BY PRICE DESC;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
WHERE SALARY>40000.00
ORDER BY SALARY ASC;

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE>20
ORDER BY STUDENT_NAME ASC;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE AVAILABLESTOCK<10
ORDER BY AVAILABLESTOCK ASC;

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES>30000.00
ORDER BY FEES DESC;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY='CHENNAI'
ORDER BY CUSTOMERNAME ASC;




USE EMPLOYEEDB;                          #ORDER BY WITH MULTIPLE COLUMNS
SELECT * FROM EMPLOYEES
ORDER BY DEPARTMENT ASC, SALARY DESC;

USE STUDENTDB;
SELECT * FROM STUDENTS
ORDER BY DEPARTMENT ASC, AGE DESC;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
ORDER BY CATEGORY ASC, PRICE DESC;

USE LIBRARYDB;
SELECT *FROM BOOKS
ORDER BY CATEGORY ASC, PRICE ASC;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
ORDER BY DESIGNATION ASC, SALARY DESC;

USE STUDENTDB;
SELECT * FROM STUDENTS
ORDER BY GENDER ASC, MARK DESC;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
ORDER BY CITY ASC, CUSTOMERNAME ASC;

USE SHOPPINDB;
SELECT * FROM PRODUCTS
ORDER BY BRAND ASC, PRICE DESC;

USE COURSEDB;
SELECT * FROM COURSES
ORDER BY DEPARTMENT ASC, FEES DESC;

USE HOSPITALDB;
SELECT * FROM PATIENTS
ORDER BY BLOODGROUP ASC, AGE DESC;





USE EMPLOYEEDB;                                #ORDER BY WITH EXPRESSION
SELECT *,SALARY*12 AS ANNUAL_SALARY
FROM EMPLOYEES
ORDER BY ANNUAL_SALARY DESC;

USE SHOPPINGDB;
SELECT *,PRICE*AVAILABLESTOCK AS TOTAL_VALUE
FROM PRODUCTS
ORDER BY TOTAL_VALUE DESC;

USE EMPLOYEEDB;
SELECT *,SALARY*1.10 AS INCREMENTED_SALARY
FROM EMPLOYEES
ORDER BY INCREMENTED_SALARY ASC;

USE SHOPPINGDB;
SELECT *,PRICE*0.90 AS DISCOUNTED_PRICE
FROM PRODUCTS
ORDER BY DISCOUNTED_PRICE ASC;

USE STUDENTDB;
SELECT *,LENGTH(STUDENTNAME) AS NAME_LENGTH
FROM STUDENTS
ORDER BY NAME_LENGTH DESC;

USE EMPLOYEEDB;
SELECT *,SALARY*12 AS ANNUAL_SALARY
FROM EMPLOYEES
ORDER BY ANNUAL_SALARY ASC;

USE SHOPPINGDB;
SELECT *,PRICE*AVAILABLESTOCK AS STOCK_VALUE
FROM PRODUCTS
ORDER BY STOCK_VALUE DESC;

SELECT *,PRICE*0.80 AS DISCOUNTED_PRICE
FROM BOOKS
ORDER BY DISCOUNTED_PRICE ASC;

USE COURSEDB;
SELECT *,FEES*0.85 AS DISCOUNTED_FEES
FROM COURSES
ORDER BY DISCOUNTED_FEES ASC;

USE STUDENTDB;
SELECT *,AGE+1 AS NEXT_YEAR_AGE
FROM STUDENTS
ORDER BY NEXT_YEAR_AGE ASC;




USE EMPLOYEEDB;                                 #ORDER BY WITH ALIAS
SELECT SALARY*12 AS ANNUAL_SALARY
FROM EMPLOYEES
ORDER BY ANNUAL_SALARY DESC;

USE SHOPPINGDB;
SELECT PRICE*AVAILABLESTOCK AS TOTAL_VALUE
FROM PRODUCTS
ORDER BY TOTAL_VALUE DESC;

USE STUDENTDB;
SELECT LENGTH(STUDENTNAME) AS NAME_LENGTH
FROM STUDENTS
ORDER BY NAME_LENGTH ASC;

USE EMPLOYEEDB;
SELECT SALARY*1.10 AS INCREMENTED_SALARY
FROM EMPLOYEES
ORDER BY INCREMENTED_SALARY DESC;

USE SHOPPINGDB;
SELECT PRICE*0.90 AS DISCOUNTED_PRICE
FROM PRODUCTS
ORDER BY DISCOUNTED_PRICE ASC;

USE COURSEDB;
SELECT FEES*0.90 AS FINAL_FEES
FROM COURSES
ORDER BY FINAL_FEES DESC;

USE STUDENTDB;
SELECT STUDENTNAME,
CASE WHEN AGE<18 THEN 'MINOR'
ELSE 'ADULT'
END AS AGE_CATEGORY
FROM STUDENTS
ORDER BY AGE_CATEGORY ASC;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,
CASE WHEN SALARY> 100000 THEN 'HIGH'
WHEN SALARY>=50000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY
FROM EMPLOYEES
ORDER BY SALARY_CATEGORY ASC;

USE SHOPPINGDB;
SELECT PRODUCTNAME,
CASE WHEN AVAILABLESTOCK>0 THEN 'IN STOCK'
ELSE 'OUT OF STOCK'
END AS STOCK_STATUS
FROM PRODUCTS
ORDER BY STOCK_STATUS ASC;

USE MOVIEDB;
SELECT TITLE,
CASE WHEN RATING>=8 THEN 'EXCELLENT'
WHEN RATING>=6 THEN 'GOOD'
WHEN RATING>=4 THEN 'AVERAGE'
ELSE 'FLOP'
END AS RATING_CATEGORY
FROM MOVIES
ORDER BY RATING_CATEGORY ASC;





USE EMPLOYEEDB;                       #ORDER BY WITH AGGREGATE FUNCTIONS
SELECT  DEPARTMENT , COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY EMPLOYEE_COUNT DESC;

USE STUDENTDB;
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT
FROM STUDENTS
GROUP BY DEPARTMENT
ORDER BY STUDENT_COUNT ASC;

USE EMPLOYEEDB;
SELECT DEPARTMENT, ROUND(AVG(SALARY),2) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY AVERAGE_SALARY DESC;

SELECT DEPARTMENT, ROUND(MIN(SALARY),2) AS MINIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY MINIMUM_SALARY ASC;

SELECT DEPARTMENT, ROUND(MAX(SALARY),2) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY MAXIMUM_SALARY DESC;

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY TOTAL_SALARY DESC;

USE SHOPPINGDB;
SELECT CATEGORY, ROUND(AVG(PRICE),2) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY AVERAGE_PRICE DESC;

SELECT CATEGORY, ROUND(MAX(PRICE),2) AS MAXIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY MAXIMUM_PRICE DESC;

SELECT CATEGORY, ROUND(MIN(PRICE),2) AS MINIMUM_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY MINIMUM_PRICE ASC;

SELECT CATEGORY, SUM(AVAILABLESTOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY TOTAL_STOCK DESC;





USE EMPLOYEEDB;                              #ADVANCED PRACTICE
SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 5;

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
ORDER BY PRICE ASC
LIMIT 5;

USE LIBRARYDB;
SELECT * FROM BOOKS
ORDER BY PRICE DESC
LIMIT 3;

USE STUDENTDB;
SELECT * FROM STUDENTS
ORDER BY MARK DESC
LIMIT 10;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
ORDER BY EXPERIENCE DESC
LIMIT 5;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE,AVAILABLESTOCK,
PRICE*AVAILABLESTOCK AS TOTAL_STOCK_VALUE
FROM PRODUCTS
ORDER BY TOTAL_STOCK_VALUE DESC
LIMIT 5;

USE COURSEDB;
SELECT * FROM COURSES
ORDER BY FEES DESC
LIMIT 3;

USE MOVIEDB;
SELECT * FROM MOVIES
ORDER BY RATING DESC
LIMIT 5;

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES
ORDER BY JOININGDATE DESC
LIMIT 10;

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
ORDER BY REGISTEREDDATE DESC
LIMIT 5;







































































