USE STUDENTDB;                                #STRING SCALAR FUNCTIONS
SELECT UPPER(STUDENTNAME) FROM STUDENTS;

USE EMPLOYEEDB;
SELECT LOWER(EMPLOYEENAME) FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENTNAME, LENGTH(STUDENTNAME) AS `LENGTH OF NAME` FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,LEFT(EMPLOYEENAME,3) FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENTNAME,RIGHT(STUDENTNAME,3) FROM STUDENTS;

USE SHOPPINGDB;
SELECT LEFT(PRODUCTNAME,5) FROM PRODUCTS;

USE LIBRARYDB;
SELECT RIGHT(TITLE,4) FROM BOOKS;

USE STUDENTDB;
SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULLNAME FROM STUDENTS;

USE EMPLOYEEDB;
SELECT CONCAT(EMPLOYEENAME, '-', DEPARTMENT) FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT CONCAT(PRODUCTNAME, '-', BRAND) FROM PRODUCTS;

USE STUDENTDB;                             
SELECT TRIM(STUDENTNAME) FROM STUDENTS;

USE EMPLOYEEDB;
SELECT SUBSTRING(EMPLOYEENAME, 1, 4)  FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT SUBSTRING(PRODUCTNAME, 2, 5)  FROM PRODUCTS;

USE STUDENTDB;                               
SELECT UPPER(STUDENTNAME),LENGTH(STUDENTNAME) FROM STUDENTS;

USE EMPLOYEEDB;
SELECT LOWER(EMPLOYEENAME),LENGTH(EMPLOYEENAME) FROM EMPLOYEES;

USE ECOMMERCEDB;
SELECT CONCAT(CUSTOMERNAME,' From ',CITY) AS CUSTOMER FROM CUSTOMERS;

USE LIBRARYDB;
SELECT CONCAT(TITLE,' - ',CATEGORY) AS BOOKS FROM BOOKS;

USE EMPLOYEEDB;
SELECT CONCAT(EMPLOYEENAME, '-', DESIGNATION) FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT UPPER(PRODUCTNAME),LOWER(BRAND)  FROM PRODUCTS;

USE STUDENTDB;
SELECT LEFT(STUDENTNAME,1),RIGHT(STUDENTNAME,1) FROM STUDENTS;





USE EMPLOYEEDB;                                #NUMERIC SCALAR FUNCTIONS
SELECT EMPLOYEENAME, ROUND(SALARY) FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,ROUND(PRICE,2)  FROM PRODUCTS;

USE COURSEDB;
SELECT COURSENAME,ROUND(FEES,-2)  FROM COURSES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,CEIL(PRICE)  FROM PRODUCTS;

SELECT PRODUCTNAME,FLOOR(PRICE)  FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME, SALARY, 
ABS(SALARY - 5000) AS `ABSOLUTE DIFFERENCE`
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE,
MOD(PRICE, 1000) AS REMAINDER
FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME, SALARY, 
SALARY*12 AS `ANNUAL SALARY`
FROM EMPLOYEES;

SELECT EMPLOYEENAME, SALARY,
ROUND(SALARY*1.10,2) AS `SALARY AFTER INCREMENT`
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE,
ROUND(PRICE-PRICE*15/100,2) AS `DISCOUNT PRICE`
FROM PRODUCTS;

SELECT PRODUCTNAME,PRICE,
ROUND(PRICE-PRICE*10/100,2) AS `FINAL PRODUCT PRICE`
FROM PRODUCTS;

USE STUDENTDB;                             
SELECT AGE,POWER(AGE,2) FROM STUDENTS;

USE SHOPPINGDB;
SELECT AVAILABLESTOCK,POWER(AVAILABLESTOCK,3) FROM PRODUCTS;

SELECT PRODUCTNAME, PRICE, 
ABS(PRICE - 10000) AS `ABSOLUTE DIFFERENCE`
FROM PRODUCTS;

USE COURSEDB;
SELECT COURSENAME,CEIL(FEES)
FROM COURSES;

USE LIBRARYDB;
SELECT TITLE,FLOOR(PRICE)
FROM BOOKS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,SALARY,
MOD(SALARY, 10000) AS REMAINDER
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE,AVAILABLESTOCK,
AVAILABLESTOCK*PRICE AS `PRODUCT VALUE` FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME, SALARY, 
SALARY*12 AS `ANNUAL SALARY`
FROM EMPLOYEES;

SELECT EMPLOYEENAME, SALARY, 
ROUND(SALARY*1.20,2) AS `SALARY AFTER INCREMENT`
FROM EMPLOYEES;




SELECT CURRENT_DATE();                           #DATE & TIME SCALAR FUNCTIONS

SELECT CURRENT_TIME();                                                            

SELECT CURRENT_TIMESTAMP();                                                       

SELECT NOW();    

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,DEPARTMENT,SALARY,
DATE_FORMAT(JOININGDATE,'%Y') AS `JOINING YEAR` 
FROM EMPLOYEES;

SELECT EMPLOYEENAME,DEPARTMENT,SALARY,
DATE_FORMAT(JOININGDATE,'%M') AS `JOINING MONTH` 
FROM EMPLOYEES;

SELECT EMPLOYEENAME,DEPARTMENT,SALARY,
DATE_FORMAT(JOININGDATE,'%D %W') AS `JOINING DAY` 
FROM EMPLOYEES;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,
DATE_FORMAT(REGISTEREDDATE,'%Y') AS `JOINING YEAR` 
FROM CUSTOMERS;

SELECT CUSTOMERNAME,
DATE_FORMAT(REGISTEREDDATE,'%M') AS `JOINING MONTH` 
FROM CUSTOMERS;

SELECT CUSTOMERNAME,
DATE_FORMAT(REGISTEREDDATE,'%D %W') AS `JOINING DAY` 
FROM CUSTOMERS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME, JOININGDATE,
DATE_ADD(JOININGDATE, INTERVAL 30 DAY) AS `DATE AFTER 30 DAYS`
FROM EMPLOYEES;

SELECT EMPLOYEENAME, JOININGDATE,
DATE_ADD(JOININGDATE, INTERVAL 90 DAY) AS `DATE AFTER 90 DAYS`
FROM EMPLOYEES;

SELECT EMPLOYEENAME, JOININGDATE,
DATE_SUB(JOININGDATE, INTERVAL 42 DAY) AS `DATE BEFORE 42 DAYS`
FROM EMPLOYEES;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME, REGISTEREDDATE,
DATE_ADD(REGISTEREDDATE, INTERVAL 126 DAY) AS `DATE AFTER 126 DAYS`
FROM CUSTOMERS;

SELECT CUSTOMERNAME, REGISTEREDDATE,
DATE_SUB(REGISTEREDDATE, INTERVAL 30 DAY) AS `DATE BEFORE 30 DAYS`
FROM CUSTOMERS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,DEPARTMENT,SALARY,
DATE_FORMAT(JOININGDATE,'%d-%m-%Y') AS JOININGDATE
FROM EMPLOYEES;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,REGISTEREDDATE,
DATE_FORMAT(REGISTEREDDATE,'%m/%d/%Y') AS REGISTEREDDATE 
FROM CUSTOMERS;

USE SHOPPINGDB;
SELECT PRODUCTNAME,
DATE_FORMAT(MANUFACTURINGDATE,'%Y-%m-%d') AS MANUFACTURINGDATE 
FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,DEPARTMENT,SALARY,
DATE_FORMAT(JOININGDATE,'%M %Y') AS `JOINING MONTH & YEAR` 
FROM EMPLOYEES;

SELECT EMPLOYEENAME, JOININGDATE, LEAVINGDATE,
DATEDIFF(LEAVINGDATE, JOININGDATE) AS `DIFFERENCE IN DAYS`
FROM EMPLOYEES;




USE STUDENTDB;                                 #NULL HANDLING SCALAR FUNCTION
SELECT STUDENTNAME,
CASE WHEN EMAIL IS NULL THEN 'NOT AVAILABLE'
ELSE EMAIL
END AS EMAIL
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,
CASE WHEN PHONE IS NULL THEN 'NO PHONE'
ELSE PHONE
END AS PHONE
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,
CASE WHEN BRAND IS NULL THEN 'UNKNOWN BRAND'
ELSE BRAND
END AS BRAND
FROM PRODUCTS;

USE LIBRARYDB;
SELECT TITLE,
CASE WHEN AUTHOR IS NULL THEN 'UNKNOWN AUTHOR'
ELSE AUTHOR
END AS AUTHOR
FROM BOOKS;

USE ECOMMERCEDB;
SELECT CUSTOMERID,CUSTOMERNAME,
CASE WHEN EMAIL IS NULL THEN 'EMAIL MISSING'
ELSE EMAIL
END AS EMAIL
FROM CUSTOMERS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,
CASE WHEN DEPARTMENT IS NULL THEN 'NOT ASSIGNED'
ELSE DEPARTMENT
END AS DEPARTMENT
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRODUCTID,
CASE WHEN DISCOUNT IS NULL THEN '0'
ELSE DISCOUNT
END AS DISCOUNT
FROM PRODUCTS;

USE COURSEDB;
SELECT COURSENAME,COURSEID,
CASE WHEN FEES IS NULL THEN '0'
ELSE FEES
END AS FEES
FROM COURSES;

USE HOSPITALDB;
SELECT PATIENTNAME,PATIENTID,
CASE WHEN DISEASE IS NULL THEN 'NOT SPECIFIED'
ELSE DISEASE
END AS DISEASE
FROM PATIENTS;

USE STUDENTDB;
SELECT STUDENTNAME,
COALESCE(MOBILENUMBER)
FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,
COALESCE(EMAIL,'NO EMAIL') AS EMAIL
FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRODUCTID,
COALESCE(BRAND,'NO BRAND') AS BRAND
FROM PRODUCTS;

USE STUDENTDB;
SELECT STUDENTNAME,
COALESCE(EMAIL,MOBILENUMBER) 
FROM STUDENTS;

USE COURSEDB;
SELECT COURSENAME,COURSEID,
CASE WHEN COURSEDURATION IS NULL THEN 'DURATION NOT AVAILABLE'
ELSE COURSEDURATION
END AS COURSEDURATION
FROM COURSES;

USE LIBRARYDB;
SELECT TITLE,
CASE WHEN PUBLISHEDYEAR IS NULL THEN 'YEAR UNKNOWN'
ELSE PUBLISHEDYEAR
END AS PUBLISHEDYEAR
FROM BOOKS;




USE EMPLOYEEDB;                       #CONDITIONAL SCALAR FUNCTIONS
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=60000.00 THEN 'HIGH'
ELSE 'LOW'
END AS 'SALARY CATEGORY'
FROM EMPLOYEES;

USE STUDENTDB;                     
SELECT STUDENTNAME,MARK,
CASE WHEN MARK>=40 THEN 'PASS'
ELSE 'FAIL'
END AS 'PASS/FAIL'
FROM STUDENTS;

USE SHOPPINGDB;                     
SELECT PRODUCTNAME,AVAILABLESTOCK,
CASE WHEN AVAILABLESTOCK>0 THEN 'AVAILABLE'
ELSE 'OUT OF STOCK'
END AS 'AVAILABILITY'
FROM PRODUCTS;

USE EMPLOYEEDB;                       
SELECT EMPLOYEENAME,EXPERIENCE,
CASE WHEN EXPERIENCE>=5 THEN 'EXPERIENCED'
ELSE 'FRESHER'
END AS 'EXPERIENCE CATEGORY'
FROM EMPLOYEES;

USE COURSEDB;
SELECT COURSENAME,FEES,
CASE WHEN FEES>50000.00 THEN 'EXPENSIVE'
ELSE 'AFFORDABLE'
END AS 'CATEGORY'
FROM COURSES;

USE LIBRARYDB;
SELECT TITLE,PRICE,
CASE WHEN PRICE>=1000.00 THEN 'PREMIUM'
ELSE 'REGULAR'
END AS 'CATEGORY'
FROM BOOKS;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,AGE,
CASE WHEN AGE>=18 THEN 'ADULT'
ELSE 'MINOR'
END AS 'AGE CATEGORY'
FROM CUSTOMERS;

USE SHOPPINGDB;                     
SELECT PRODUCTNAME,AVAILABLESTOCK,
CASE WHEN AVAILABLESTOCK<10 THEN 'LOW STOCK'
ELSE 'SUFFICIENT STOCK'
END AS 'STOCK STATUS'
FROM PRODUCTS;

USE EMPLOYEEDB;                      
SELECT EMPLOYEENAME,SALARY,
CASE WHEN SALARY>=50000.00 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS 'ELIGIBILITY'
FROM EMPLOYEES;

USE STUDENTDB;                     
SELECT STUDENTNAME,ATTENDANCE,
CASE WHEN ATTENDANCE>=75 THEN 'ELIGIBLE'
ELSE 'NOT ELIGIBLE'
END AS 'ELIGIBILITY'
FROM STUDENTS;





USE EMPLOYEEDB;                               #MIXED SCALAR FUNCTION
SELECT UPPER(EMPLOYEENAME),
ROUND(SALARY,2) FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT LOWER(PRODUCTNAME),PRICE,
ROUND(PRICE-PRICE*10/100,2) AS `PRICE AFTER DISCOUNT` FROM PRODUCTS;

USE STUDENTDB;
SELECT UPPER(STUDENTNAME), LENGTH(STUDENTNAME) AS `LENGTH OF NAME` FROM STUDENTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,SALARY,
SALARY*12 AS `ANNUAL SALARY` FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT PRODUCTNAME,BRAND,PRICE,
ROUND(PRICE*18/100,2) AS `GST`,
ROUND(PRICE*1.18,2) AS `FINAL PRICE` FROM PRODUCTS;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,REGISTEREDDATE,DATE_FORMAT(REGISTEREDDATE,'%Y') AS `REGISTERED YEAR`
FROM CUSTOMERS;

USE EMPLOYEEDB;                            
SELECT EMPLOYEENAME,JOININGDATE,DATE_FORMAT(JOININGDATE,'%M') AS `JOINED MONTH`
FROM EMPLOYEES;

USE LIBRARYDB;
SELECT UPPER(TITLE),
ROUND(PRICE,2) AS PRICE FROM BOOKS;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE*AVAILABLESTOCK AS `STOCK VALUE` FROM PRODUCTS;

USE EMPLOYEEDB;
SELECT EMPLOYEENAME,SALARY,
ROUND(SALARY*1.10,2) AS `SALARY AFTER INCREMENT` FROM EMPLOYEES;

USE STUDENTDB;
SELECT STUDENTNAME,AGE,
POWER(AGE,2) AS `SQUARED AGE` FROM STUDENTS;

USE SHOPPINGDB;
SELECT PRODUCTNAME,PRICE,
MOD(PRICE,1000) AS `REMINDER` FROM PRODUCTS;

USE ECOMMERCEDB;
SELECT CUSTOMERNAME,REGISTEREDDATE,DATE_ADD(REGISTEREDDATE, INTERVAL 30 DAY) AS `30 DAYS AFTER REGISTERED DAY`
FROM CUSTOMERS;

USE EMPLOYEEDB;                            
SELECT EMPLOYEENAME,
CASE WHEN DEPARTMENT IS NULL THEN 'NOT ASSIGNED'
ELSE DEPARTMENT
END AS 'DEPARTMENT'
 FROM EMPLOYEES;

USE SHOPPINGDB;
SELECT UPPER(PRODUCTNAME),ROUND(PRICE,2),
CASE WHEN BRAND IS NULL THEN 'UNKNOWN'
ELSE BRAND
END AS BRAND
FROM PRODUCTS;





