SELECT STUDENTNAME AS NAME                           -- UNION 
FROM STUDENTS
UNION
SELECT EMPLOYEENAME AS NAME
FROM EMPLOYEES;


SELECT CITY
FROM CUSTOMERS
UNION
SELECT CITY
FROM EMPLOYEES;

SELECT EMAIL
FROM STUDENTS
UNION
SELECT EMAIL
FROM EMPLOYEES;

SELECT PHONE
FROM STUDENTS
UNION
SELECT PHONE
FROM CUSTOMERS;

SELECT DEPARTMENTNAME
FROM STUDENTS
UNION
SELECT DEPARTMENTNAME
FROM EMPLOYEES;

SELECT STUDENTNAME AS NAME
FROM STUDENTS
UNION
SELECT CUSTOMERNAME AS NAME
FROM CUSTOMERS;

SELECT CATEGORY
FROM PRODUCTS
UNION
SELECT CATEGORY
FROM FIRSTCOPYPRODUCTS;

SELECT COURSENAME
FROM CURRENTCOURSES
UNION
SELECT COURSENAME
FROM COMPLETEDCOURSES;

SELECT CITY
FROM CUSTOMERS
UNION
SELECT CITY
FROM SUPPLIERS;

SELECT EMPLOYEENAME AS NAME
FROM EMPLOYEES
UNION
SELECT MANAGERNAME AS NAME
FROM MANAGERS;

SELECT STUDENTID
FROM STUDENTS
UNION
SELECT STUDENTID
FROM ALUMNI;

SELECT PRODUCTID
FROM PRODUCTS
UNION
SELECT PRODUCTID
FROM DISCONTINUEDPRODUCTS;

SELECT EMAIL
FROM CUSTOMERS
UNION
SELECT EMAIL
FROM SUPPLIERS;

SELECT CITY
FROM CUSTOMERS
UNION
SELECT CITY
FROM SUPPLIERS;

SELECT DEPARTMENTID
FROM EMPLOYEES
UNION
SELECT DEPARTMENTID
FROM MANAGERS;

SELECT COURSEID
FROM CURRENTSTUDENTS
UNION
SELECT COURSEID
FROM PREVIOUSSTUDENTS;

SELECT STUDENTNAME AS NAME
FROM STUDENTS
UNION
SELECT TEACHERNAME AS NAME
FROM TEACHERS;

SELECT PHONE
FROM EMPLOYEES
UNION
SELECT PHONE
FROM CUSTOMERS;

SELECT LOCATION
FROM STUDENTS
UNION
SELECT LOCATION
FROM TEACHERS;

SELECT EMPLOYEEID
FROM EMPLOYEES
UNION
SELECT EMPLOYEEID
FROM EMPLOYEEDETAILS;




SELECT STUDENTNAME AS NAME                          -- UNION ALL 
FROM STUDENTS
UNION ALL
SELECT EMPLOYEENAME AS NAME
FROM EMPLOYEES;

SELECT CITY
FROM CUSTOMERS
UNION ALL
SELECT CITY
FROM EMPLOYEES;

SELECT EMAIL
FROM STUDENTS
UNION ALL
SELECT EMAIL
FROM CUSTOMERS;

SELECT PHONE
FROM EMPLOYEES
UNION ALL
SELECT PHONE
FROM CUSTOMERS;

SELECT DEPARTMENTNAME
FROM EMPLOYEES
UNION ALL
SELECT DEPARTMENTNAME
FROM STUDENTS;

SELECT CATEGORY
FROM PRODUCTS
UNION ALL
SELECT CATEGORY
FROM NEWPRODUCTS;

SELECT COURSENAME
FROM CURRENTCOURSES
UNION ALL
SELECT COURSENAME
FROM COMPLETEDCOURSES;

SELECT CUSTOMERNAME
FROM CUSTOMERS
UNION ALL
SELECT CUSTOMERNAME
FROM PREMIUMCUSTOMERS;

SELECT EMPLOYEEID
FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEEID
FROM RESIGNEDEMPLOYEES;

SELECT PRODUCTID
FROM PRODUCTS
UNION ALL
SELECT PRODUCTID
FROM OLDPRODUCTS;

SELECT CITY
FROM CUSTOMERS
UNION ALL
SELECT CITY
FROM SUPPLIERS;

SELECT COURSEID
FROM ENROLLMENTWEEK
UNION ALL
SELECT COURSEID
FROM ENROLLMENTWEEKEND;

SELECT EMAIL
FROM EMPLOYEES
UNION ALL
SELECT EMAIL
FROM EMPLOYEESWFH;

SELECT STUDENTID
FROM STUDENTS
UNION ALL
SELECT STUDENTID
FROM ALUMNI;

SELECT DEPARTMENTID
FROM EMPLOYEES
UNION ALL
SELECT DEPARTMENTID
FROM EMPLOYEEDETAILS;

SELECT PRODUCTNAME
FROM PRODUCTS
UNION ALL
SELECT PRODUCTNAME
FROM FIRSTCOPYPRODUCTS;

SELECT PHONE
FROM CUSTOMERS
UNION ALL
SELECT PHONE
FROM REGULARCUSTOMERS;

SELECT EMPLOYEENAME
FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEENAME
FROM EMPLOYEESWFH;

SELECT LOCATION
FROM CUSTOMERS
UNION ALL
SELECT LOCATION
FROM SUPPLIERS;

SELECT PRODUCTID
FROM PRODUCTS
UNION ALL
SELECT CUSTOMERID
FROM CUSTOMERS;




SELECT DISTINCT C.CITY                                                        -- INTERSECT <> INNER JOIN
FROM CUSTOMERS C
INNER JOIN SUPPLIERS S
ON C.CITY = S.CITY;

SELECT DISTINCT S.EMAIL
FROM STUDENTS S
INNER JOIN EMPLOYEES E
ON S.EMAIL = E.EMAIL;

SELECT DISTINCT C.PHONE
FROM CUSTOMERS C
INNER JOIN EMPLOYEES E
ON C.PHONE = E.PHONE;

SELECT DISTINCT S.DEPARTMENTNAME
FROM STUDENTS S
INNER JOIN EMPLOYEES E
ON S.DEPARTMENTNAME = E.DEPARTMENTNAME;

SELECT DISTINCT S.STUDENTID
FROM STUDENTS S
INNER JOIN ALUMNI A
ON S.STUDENTID = A.STUDENTID;

SELECT DISTINCT P.PRODUCTID
FROM PRODUCTS P
INNER JOIN OLDPRODUCTS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT DISTINCT C.COURSEID
FROM CURRENTSTUDENTS C
INNER JOIN PREVIOUSSTUDENTS P
ON C.COURSEID = P.COURSEID;

SELECT DISTINCT C.CITY
FROM CUSTOMERS C
INNER JOIN SUPPLIERS S
ON C.CITY = S.CITY;

SELECT DISTINCT E.EMPLOYEENAME
FROM EMPLOYEES E
INNER JOIN MANAGERS M
ON E.EMPLOYEENAME = M.MANAGERNAME;

SELECT DISTINCT P.CATEGORY
FROM PRODUCTS P
INNER JOIN NEWPRODUCTS N
ON P.CATEGORY = N.CATEGORY;

SELECT DISTINCT C.EMAIL
FROM CUSTOMERS C
INNER JOIN SUPPLIERS S
ON C.EMAIL = S.EMAIL;

SELECT DISTINCT S.PHONE
FROM STUDENTS S
INNER JOIN CUSTOMERS C
ON S.PHONE = C.PHONE;

SELECT DISTINCT E.DEPARTMENTID
FROM EMPLOYEES E
INNER JOIN MANAGERS M
ON E.DEPARTMENTID = M.DEPARTMENTID;

SELECT DISTINCT C.COURSENAME
FROM CURRENTCOURSES C
INNER JOIN COMPLETEDCOURSES C2
ON C.COURSENAME = C2.COURSENAME;

SELECT DISTINCT C.CUSTOMERID
FROM CURRENTCUSTOMERS C
INNER JOIN PREVIOUSCUSTOMERS P
ON C.CUSTOMERID = P.CUSTOMERID;

SELECT DISTINCT P.PRODUCTNAME
FROM PRODUCTS P
INNER JOIN DISCONTINUEDPRODUCTS D
ON P.PRODUCTNAME = D.PRODUCTNAME;

SELECT DISTINCT S.LOCATION
FROM STUDENTS S
INNER JOIN TEACHERS T
ON S.LOCATION = T.LOCATION;

SELECT DISTINCT E.EMPLOYEEID
FROM EMPLOYEES E
INNER JOIN EMPLOYEEDETAILS ED
ON E.EMPLOYEEID = ED.EMPLOYEEID;

SELECT DISTINCT S.STUDENTID
FROM STUDENTS S
INNER JOIN ALUMNI A
ON S.STUDENTID = A.STUDENTID;

SELECT DISTINCT S.PRICE
FROM SAMSUNG S
INNER JOIN APPLE A
ON S.PRICE = A.PRICE;




SELECT CITY                                          -- EXCEPT <> NOT IN
FROM CUSTOMERS
WHERE CITY NOT IN (SELECT CITY
FROM SUPPLIERS);

SELECT EMAIL
FROM STUDENTS
WHERE EMAIL NOT IN (SELECT EMAIL
FROM EMPLOYEES);

SELECT PHONE
FROM CUSTOMERS
WHERE PHONE NOT IN (SELECT PHONE
FROM EMPLOYEES);

SELECT DEPARTMENTNAME
FROM STUDENTS
WHERE DEPARTMENTNAME NOT IN (SELECT DEPARTMENTNAME
FROM EMPLOYEES);

SELECT STUDENTID
FROM STUDENTS
WHERE STUDENTID NOT IN (SELECT STUDENTID
FROM ALUMNI);

SELECT PRODUCTID
FROM PRODUCTS
WHERE PRODUCTID NOT IN (SELECT PRODUCTID
FROM OLDPRODUCTS);

SELECT COURSEID
FROM CURRENTSTUDENTS
WHERE COURSEID NOT IN (SELECT COURSEID
FROM PREVIOUSSTUDENTS);

SELECT CITY
FROM CUSTOMERS
WHERE CITY NOT IN (SELECT CITY
FROM SUPPLIERS);

SELECT EMPLOYEENAME
FROM EMPLOYEES
WHERE EMPLOYEENAME NOT IN (SELECT MANAGERNAME
FROM MANAGERS);

SELECT CATEGORY
FROM OLPRODUCTS
WHERE CATEGORY NOT IN (SELECT CATEGORY
FROM NEWPRODUCTS);

SELECT EMAIL
FROM CUSTOMERS
WHERE EMAIL NOT IN (SELECT EMAIL
FROM SUPPLIERS);

SELECT PHONE
FROM STUDENTS
WHERE PHONE NOT IN (SELECT PHONE
FROM CUSTOMERS);

SELECT DEPARTMENTID
FROM EMPLOYEES
WHERE DEPARTMENTID NOT IN (SELECT DEPARTMENTID
FROM MANAGERS);

SELECT COURSENAME
FROM CURRENTCOURSES
WHERE COURSENAME NOT IN (SELECT COURSENAME
FROM COMPLETEDCOURSES);

SELECT CUSTOMERID
FROM CURRENTCUSTOMERS
WHERE CUSTOMERID NOT IN (SELECT CUSTOMERID
FROM PREVIOUSCUSTOMERS);

SELECT PRODUCTNAME
FROM PRODUCTS
WHERE PRODUCTNAME NOT IN (SELECT PRODUCTNAME
FROM DISCONTINUEDPRODUCTS);

SELECT LOCATION
FROM FIRSTTABLE
WHERE LOCATION NOT IN (SELECT LOCATION
FROM SECONDTABLE);

SELECT EMPLOYEEID
FROM EMPLOYEES
WHERE EMPLOYEEID NOT IN (SELECT EMPLOYEEID
FROM EMPLOYEEDETAILS);

SELECT STUDENTID
FROM STUDENTS
WHERE STUDENTID NOT IN (SELECT STUDENTID
FROM ALUMNI);

SELECT PRICE
FROM BOAT
WHERE PRICE NOT IN (SELECT PRICE
FROM JBL);





SELECT * FROM EMPLOYEES                                                  --IN
WHERE DEPARTMENTID IN 
(SELECT DEPARTMENTID
FROM DEPARTMENTS);

SELECT * FROM STUDENTS
WHERE DEPARTMENTID IN 
(SELECT DEPARTMENTID
FROM DEPARTMENTS);

SELECT * FROM CUSTOMERS
WHERE CUSTOMERID IN
(SELECT CUSTOMERID
FROM ORDERS);

SELECT * FROM PRODUCTS
WHERE PRODUCTID IN 
(SELECT PRODUCTID
FROM ORDERS);

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID IN 
(SELECT EMPLOYEEID
FROM EMPLOYEEPROJECTS);

SELECT * FROM STUDENTS
WHERE STUDENTID IN 
(SELECT STUDENTID
FROM ENROLLMENTS);

SELECT * FROM CUSTOMERS
WHERE CUSTOMERID IN 
(SELECT CUSTOMERID
FROM ORDERS);

SELECT * FROM PRODUCTS
WHERE PRODUCTID IN 
(SELECT PRODUCTID
FROM ORDERS);

SELECT * FROM EMPLOYEES
WHERE DEPARTMENTID IN 
(SELECT DEPARTMENTID
FROM DEPARTMENTS
WHERE LOCATION = 'CHENNAI');

SELECT * FROM STUDENTS
WHERE DEPARTMENTID IN 
(SELECT DEPARTMENTID
FROM DEPARTMENTS
WHERE DEPARTMENTNAME IN ('DATA SCIENCE', 'IT'));





SELECT * FROM CUSTOMERS                                          --  NOT IN 
WHERE CUSTOMERID NOT IN 
(SELECT CUSTOMERID
FROM ORDERS);

SELECT * FROM PRODUCTS
WHERE PRODUCTID NOT IN 
(SELECT PRODUCTID
FROM ORDERS);

SELECT * FROM STUDENTS
WHERE STUDENTID NOT IN 
(SELECT STUDENTID
FROM ENROLLMENTS);

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID NOT IN 
(SELECT EMPLOYEEID
FROM EMPLOYEEPROJECTS);

SELECT * FROM DEPARTMENTS
WHERE DEPARTMENTID NOT IN 
(SELECT DEPARTMENTID
FROM EMPLOYEES);

SELECT * FROM CUSTOMERS
WHERE CUSTOMERID NOT IN 
(SELECT CUSTOMERID
FROM ORDERS);

SELECT *FROM PRODUCTS
WHERE PRODUCTID NOT IN 
(SELECT PRODUCTID
FROM ORDERS);

SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID NOT IN 
(SELECT EMPLOYEEID
FROM EMPLOYEEPROJECTS);

SELECT * FROM STUDENTS
WHERE STUDENTID NOT IN 
(SELECT STUDENTID
FROM ENROLLMENTS);

SELECT * FROM COURSES
WHERE COURSEID NOT IN 
(SELECT COURSEID
FROM ENROLLMENTS);



