CREATE DATABASE AUG31DB;                            --  AUTOCOMMIT
USE AUG31DB;

CREATE TABLE EMPLOYEES                                -- 1
(EMPLOYEEID INT PRIMARY KEY,
EMPLOYEENAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL(10,2));
INSERT INTO EMPLOYEES
VALUES (101, 'ARUN', 'IT', 50000);
SELECT * FROM EMPLOYEES;

SELECT @@AUTOCOMMIT;                             -- 2

SET AUTOCOMMIT = OFF;                              -- 3
INSERT INTO EMPLOYEES
VALUES (102, 'BALAJI', 'HR', 45000);
SELECT * FROM EMPLOYEES;
-- I CLOSED SQL AND OPENED IT EMPLOYEE WITH EMPLOYEEID 102'S RECORD WAS NOT THERE 

SET AUTOCOMMIT = OFF;                                      -- 4
INSERT INTO EMPLOYEES                                        
VALUES(103, 'KUMAR', 'IT', 55000),
(104, 'RAJ', 'FINANCE', 60000),
(105, 'SURESH', 'HR', 48000);
SELECT * FROM EMPLOYEES;
-- HERE AGAIN I CLOSED SQL AND OPENED IT AND RAN THE SELECT COMMAND STILL ONLY THE EMPLOYEE WITH EMPLOYEEID 101 IS PRESENT

SET AUTOCOMMIT = ON;                                          -- 5
INSERT INTO EMPLOYEES
VALUES (106, 'VIGNESH', 'SALES', 52000);
SELECT * FROM EMPLOYEES;
-- HERE ALSO I CLOSED AND OPENED THE SQL AND RAN SELECT COMMAND NOW I HAVE 2 EMPLOYEES RECORD 101 AND 106 BOTH INSERTED WHILE THE AUTOCOMMIT IS IN ON





SET AUTOCOMMIT=OFF;                                 -- 1          -- COMMIT
INSERT INTO EMPLOYEES
VALUES (201, 'AJAY', 'IT', 50000),
 (202, 'BALA', 'HR', 45000),
(203, 'CHARAN', 'FINANCE', 60000),
(204, 'DINESH', 'IT', 55000),
 (205, 'ESWAR', 'SALES', 48000);
COMMIT;
SELECT * FROM EMPLOYEES;
-- HERE ALSO I CLOSED THE SQL AND OPENED IT AGAIN AND I RAN THE SELECT COMMAND BUT THE RECORDDS ARE HERE EVEN AFTER THE AUTOCOMMIT=OFF BECAUSE OF THE COMMIT COMMAND WE USED

SET AUTOCOMMIT =OFF;                                     -- 2
UPDATE EMPLOYEES
SET SALARY = 65000
WHERE EMPLOYEEID = 201;
COMMIT;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID = 201;

SET AUTOCOMMIT =OFF;                                           -- 3
DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 202;
COMMIT;
SELECT * FROM EMPLOYEES;

SET AUTOCOMMIT = 0;                                       -- 4
INSERT INTO EMPLOYEES
VALUES (206, 'FRANKLIN', 'IT', 55000);
UPDATE EMPLOYEES
SET SALARY = 70000
WHERE EMPLOYEEID = 203;
DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 204;
COMMIT;
SELECT * FROM EMPLOYEES;


                            
CREATE TABLE PRODUCTS (PRODUCTID INT PRIMARY KEY,                             -- 5
PRODUCTNAME VARCHAR(50),
PRICE DECIMAL(10,2));
INSERT INTO PRODUCTS
VALUES (1, 'LAPTOP', 50000);
COMMIT;
SELECT * FROM PRODUCTS;
SET AUTOCOMMIT = 0;
INSERT INTO PRODUCTS
VALUES (2, 'MOUSE', 500),
(3, 'KEYBOARD', 1500);
UPDATE PRODUCTS
SET PRICE = 55000
WHERE PRODUCTID = 1;
COMMIT;
SELECT * FROM PRODUCTS;




SET AUTOCOMMIT = 0;                               -- 1            -- ROLLBACK
INSERT INTO EMPLOYEES
VALUES (301, 'KARTHIK', 'IT', 50000),
(302, 'MANOJ', 'HR', 45000),
(303, 'RAMESH', 'SALES', 48000);
SELECT * FROM EMPLOYEES;
ROLLBACK;
SELECT * FROM EMPLOYEES;
-- AFTER ROLLBACK EMPLOYEES WITH EMPLOYEE ID 301,302,303 GOT REMOVED 

SET AUTOCOMMIT = 0;                                            -- 2
UPDATE EMPLOYEES
SET SALARY = 90000
WHERE EMPLOYEEID = 101;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID = 101;
ROLLBACK;
SELECT * FROM EMPLOYEES
WHERE EMPLOYEEID = 101;
-- AGTER ROLLBACK SALARY CHANGED FROM 90000 TO 50000

SET AUTOCOMMIT = 0;                                          -- 3
DELETE FROM EMPLOYEES
WHERE EMPLOYEEID IN (203, 204);
SELECT * FROM EMPLOYEES;
ROLLBACK;
SELECT * FROM EMPLOYEES;

SET AUTOCOMMIT = 0;                                            -- 4
INSERT INTO EMPLOYEES
VALUES (304, 'ARJUN', 'IT', 55000);
UPDATE EMPLOYEES
SET SALARY = 75000
WHERE EMPLOYEEID = 105;
DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 106;
SELECT * FROM EMPLOYEES;
ROLLBACK;
SELECT * FROM EMPLOYEES;


SET AUTOCOMMIT = 0;                                          -- 5
INSERT INTO EMPLOYEES
VALUES (305, 'SURYA', 'IT', 50000),
 (306, 'KIRAN', 'HR', 45000);
UPDATE EMPLOYEES
SET SALARY = 80000
WHERE EMPLOYEEID = 101;
DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 105;
SELECT * FROM EMPLOYEES;
ROLLBACK;
SELECT * FROM EMPLOYEES;

SET AUTOCOMMIT =OFF;
INSERT INTO EMPLOYEES
VALUES (305, 'SURYA', 'IT', 50000),
(306, 'KIRAN', 'HR', 45000);
UPDATE EMPLOYEES
SET SALARY = 90000
WHERE EMPLOYEEID = 101;
DELETE FROM EMPLOYEES
WHERE EMPLOYEEID = 105;
SELECT * FROM EMPLOYEES;
COMMIT;
SELECT * FROM EMPLOYEES;