CREATE DATABASE AUG28DB;
USE AUG28DB;
CREATE TABLE STUDENTS (STUDENTID INT PRIMARY KEY,
STUDENTNAME VARCHAR(100),
DEPARTMENTID INT,
COURSEID INT);

CREATE TABLE EDUCATIONDEPARTMENTS (DEPARTMENTID INT PRIMARY KEY,
DEPARTMENTNAME VARCHAR(100));

CREATE TABLE DEPARTMENTS (DEPARTMENTID INT PRIMARY KEY,
DEPARTMENTNAME VARCHAR(100));

CREATE TABLE COURSES (COURSEID INT PRIMARY KEY,
COURSENAME VARCHAR(100),
FEES DECIMAL(10,2));

CREATE TABLE EMPLOYEES (EMPLOYEEID INT PRIMARY KEY,
EMPLOYEENAME VARCHAR(100),
MANAGERID INT,
DEPARTMENTID INT);

CREATE TABLE ORDERS (ORDERID INT PRIMARY KEY,
CUSTOMERID INT,
PRODUCTID INT,
QUANTITY INT);


CREATE TABLE CUSTOMERS (CUSTOMERID INT PRIMARY KEY,
CUSTOMERNAME VARCHAR(100),
CITY VARCHAR(100));


CREATE TABLE PRODUCTS (PRODUCTID INT PRIMARY KEY,
PRODUCTNAME VARCHAR(100),
PRICE DECIMAL(10,2));


INSERT INTO DEPARTMENTS (DEPARTMENTID, DEPARTMENTNAME) VALUES
(1, 'IT'),(2, 'HR'),(3, 'FINANCE'),(4, 'MARKETING'),(5, 'SALES'),
(6, 'OPERATIONS'),(7, 'ADMIN'),(8, 'SUPPORT'),(9, 'RESEARCH'),(10, 'TRAINING');

INSERT INTO EDUCATIONDEPARTMENTS (DEPARTMENTID, DEPARTMENTNAME) VALUES
(13, 'OTHER');

INSERT INTO COURSES (COURSEID, COURSENAME, FEES) VALUES
(101, 'PYTHON', 25000),(102, 'SQL', 30000),(103, 'DATA ENGINEERING', 50000),
(104, 'JAVA', 35000),(105, 'WEB DEVELOPMENT', 40000),(106, 'DATA SCIENCE', 60000),
(107, 'CYBER SECURITY', 45000),(108, 'CLOUD COMPUTING', 55000),
(109, 'MACHINE LEARNING', 65000),(110, 'DEVOPS', 48000);

INSERT INTO STUDENTS (STUDENTID, STUDENTNAME, DEPARTMENTID, COURSEID) VALUES
(1, 'ARUN', 11, 101),(2, 'BALAJI', 11, 102),(3, 'CHARAN', 11, 103),(4, 'DHARUN', 12, 104),
(5, 'ELAN', 12, 105),(6, 'FARHAN', 11, 106),(7, 'GOKUL', 12, 107),(8, 'HARI',NULL, 108),
(9, 'IRFAN', 12, 109),(10, 'JEEVA', NULL, 110);


INSERT INTO EMPLOYEES (EMPLOYEEID, EMPLOYEENAME, MANAGERID, DEPARTMENTID) VALUES
(101, 'RAJESH', NULL, 1),(102, 'KUMAR', 101, 1),(103, 'SURESH', 101, 1),(104, 'MANOJ', NULL, 2),
(105, 'ARAVIND', 104, 2),(106, 'VIJAY', NULL, 3),(107, 'KARTHIK', 106, 3),(108, 'NAVEEN', NULL, 4),
(109, 'PRAVEEN', 108, 4),(110, 'SANJAY', 101, 1);

INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, PRICE) VALUES
(301, 'LAPTOP', 75000),(302, 'MOBILE', 30000),(303, 'KEYBOARD', 2500),(304, 'MOUSE', 1500),
(305, 'MONITOR', 18000),(306, 'HEADPHONES', 5000),(307, 'PRINTER', 12000),(308, 'WEBCAM', 3500),(309, 'TABLET', 25000),
(310, 'SMARTWATCH', 8000);

INSERT INTO CUSTOMERS (CUSTOMERID, CUSTOMERNAME, CITY) VALUES
(201, 'AJAY', 'CHENNAI'),(202, 'BALA', 'BANGALORE'),(203, 'CHARLES', 'COIMBATORE'),
(204, 'DINESH', 'MADURAI'),(205, 'ESWAR', 'TRICHY'),(206, 'FAIZAL', 'CHENNAI'),
(207, 'GANESH', 'SALEM'),(208, 'HARISH', 'VELLORE'),(209, 'IMRAN', 'ERODE'),
(210, 'JAGAN', 'TIRUNELVELI');

INSERT INTO ORDERS (ORDERID, CUSTOMERID, PRODUCTID, QUANTITY) VALUES
(401, 201, 301, 1),(402, 202, 302, 2),(403, 203, 303, 3),(404, 204, 304, 2),
(405, 205, 305, 1),(406, 206, 306, 4),(407, 207, 307, 1),(408, 208, 308, 2),(409, 209, 309, 1),
(410, 210, 310, 3);



SELECT S.STUDENTNAME, E.DEPARTMENTNAME                                          #INNER JOIN
FROM STUDENTS S
INNER JOIN EDUCATIONDEPARTMENTS E
ON S.DEPARTMENTID = E.DEPARTMENTID;

SELECT S.STUDENTID, S.STUDENTNAME, E.DEPARTMENTNAME
FROM STUDENTS S
INNER JOIN EDUCATIONDEPARTMENTS E
ON S.DEPARTMENTID = E.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT S.STUDENTNAME, E.DEPARTMENTNAME, C.COURSENAME
FROM STUDENTS S
INNER JOIN EDUCATIONDEPARTMENTS E
ON S.DEPARTMENTID = E.DEPARTMENTID
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE E.DEPARTMENTID IS NOT NULL;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT C.CUSTOMERNAME, O.QUANTITY
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, P.PRODUCTNAME
FROM ORDERS O
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT O.ORDERID, P.PRODUCTNAME, O.QUANTITY
FROM ORDERS O
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME, O.QUANTITY
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT P.PRODUCTNAME, O.ORDERID, O.CUSTOMERID, O.QUANTITY
FROM PRODUCTS P
INNER JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

ALTER TABLE EMPLOYEES
ADD SALARY DECIMAL(10,2);

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME, E.SALARY
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME, C.FEES
FROM STUDENTS S
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'IT';

SELECT S.STUDENTNAME, C.COURSENAME, C.FEES
FROM STUDENTS S
INNER JOIN COURSES C
ON S.COURSEID = C.COURSEID
WHERE C.FEES > 30000;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
INNER JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME, O.QUANTITY, P.PRICE
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;





SELECT S.STUDENTNAME, E.DEPARTMENTNAME                                              #LEFT JOIN
FROM STUDENTS S
LEFT JOIN EDUCATIONDEPARTMENTS E
ON S.DEPARTMENTID = E.DEPARTMENTID;

SELECT E.DEPARTMENTNAME, S.STUDENTNAME
FROM EDUCATIONDEPARTMENTS E
LEFT JOIN STUDENTS S
ON E.DEPARTMENTID = S.DEPARTMENTID;

SELECT S.STUDENTNAME, E.DEPARTMENTNAME
FROM STUDENTS S
LEFT JOIN EDUCATIONDEPARTMENTS E
ON S.DEPARTMENTID = E.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
LEFT JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, C.CUSTOMERNAME
FROM ORDERS O
LEFT JOIN CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID, O.CUSTOMERID, O.QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, COUNT(O.ORDERID) AS TOTAL_ORDERS 
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERID, C.CUSTOMERNAME;

SELECT D.DEPARTMENTNAME, COUNT(E.EMPLOYEEID) AS EMPLOYEE_COUNT
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTID, D.DEPARTMENTNAME;

SELECT C.COURSENAME, COUNT(S.STUDENTID) AS STUDENT_COUNT
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
GROUP BY C.COURSEID, C.COURSENAME;

SELECT P.PRODUCTNAME, COALESCE(SUM(O.QUANTITY), 0) AS TOTAL_QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.PRODUCTID, P.PRODUCTNAME;

SELECT E.EMPLOYEENAME,
COALESCE(D.DEPARTMENTNAME, 'NOT ASSIGNED') AS DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;






SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME                          -- RIGHT JOIN
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM STUDENTS S
RIGHT JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM COURSES C
RIGHT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ORDERS O
RIGHT JOIN CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID;

SELECT O.ORDERID, C.CUSTOMERNAME
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM ORDERS O
RIGHT JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT O.ORDERID, P.PRODUCTNAME, O.QUANTITY
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM STUDENTS S
RIGHT JOIN COURSES C
ON S.COURSEID = C.COURSEID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM ORDERS O
RIGHT JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT D.DEPARTMENTNAME, COUNT(E.EMPLOYEEID) AS EMPLOYEE_COUNT
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTID, D.DEPARTMENTNAME;

SELECT C.COURSENAME, COUNT(S.STUDENTID) AS STUDENT_COUNT
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
GROUP BY C.COURSEID, C.COURSENAME;

SELECT P.PRODUCTNAME,
COALESCE(SUM(O.QUANTITY), 0) AS TOTAL_QUANTITY
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.PRODUCTID, P.PRODUCTNAME;





SELECT S.STUDENTNAME, D.DEPARTMENTNAME                                      -- FULL OUTER JOIN
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID
UNION
SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
RIGHT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
UNION
SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
UNION
SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
UNION
SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
UNION
SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
RIGHT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
UNION
SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
UNION
SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
UNION
SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
UNION
SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
RIGHT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
UNION
SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE E.EMPLOYEEID IS NULL
UNION
SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM DEPARTMENTS D
RIGHT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE D.DEPARTMENTID IS NULL;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE O.ORDERID IS NULL
UNION
SELECT C.CUSTOMERNAME, O.ORDERID
FROM CUSTOMERS C
RIGHT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE C.CUSTOMERID IS NULL;

SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
WHERE O.ORDERID IS NULL
UNION
SELECT P.PRODUCTNAME, O.ORDERID
FROM PRODUCTS P
RIGHT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
WHERE P.PRODUCTID IS NULL;

SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
LEFT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
WHERE S.STUDENTID IS NULL
UNION
SELECT C.COURSENAME, S.STUDENTNAME
FROM COURSES C
RIGHT JOIN STUDENTS S
ON C.COURSEID = S.COURSEID
WHERE C.COURSEID IS NULL;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID
UNION
SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
RIGHT JOIN DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;





SELECT S.STUDENTNAME, C.COURSENAME                       -- CROSS JOIN
FROM STUDENTS S
CROSS JOIN COURSES C;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.CUSTOMERNAME
FROM PRODUCTS P
CROSS JOIN CUSTOMERS C;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM CUSTOMERS C
CROSS JOIN PRODUCTS P;

SELECT C.COURSENAME, D.DEPARTMENTNAME
FROM COURSES C
CROSS JOIN DEPARTMENTS D;

SELECT E.EMPLOYEENAME, C.COURSENAME
FROM EMPLOYEES E
CROSS JOIN COURSES C;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTS S
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.COURSENAME
FROM PRODUCTS P
CROSS JOIN COURSES C;

SELECT C.CUSTOMERNAME, C1.COURSENAME
FROM CUSTOMERS C
CROSS JOIN COURSES C1;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.CUSTOMERNAME
FROM PRODUCTS P
CROSS JOIN CUSTOMERS C;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTS S
CROSS JOIN COURSES C;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.COURSENAME
FROM PRODUCTS P
CROSS JOIN COURSES C;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM CUSTOMERS C
CROSS JOIN PRODUCTS P;




SELECT E.EMPLOYEENAME AS EMPLOYEE_NAME,                        -- SELF JOIN
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME AS EMPLOYEE_NAME,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.MANAGERID IS NULL;

SELECT E.EMPLOYEEID,
E.EMPLOYEENAME,
E.MANAGERID,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME AS EMPLOYEE_NAME,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
INNER JOIN DEPARTMENTS D
ON M.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'IT';

SELECT E.EMPLOYEENAME,
M.EMPLOYEENAME AS MANAGER_NAME,
M.SALARY AS MANAGER_SALARY
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE M.SALARY > 70000;

SELECT E.EMPLOYEENAME,
E.SALARY AS EMPLOYEE_SALARY,
M.EMPLOYEENAME AS MANAGER_NAME,
M.SALARY AS MANAGER_SALARY
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.SALARY > M.SALARY;

SELECT E.EMPLOYEENAME,
E.SALARY AS EMPLOYEE_SALARY,
M.EMPLOYEENAME AS MANAGER_NAME,
M.SALARY AS MANAGER_SALARY
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.SALARY < M.SALARY;

SELECT E.EMPLOYEENAME AS EMPLOYEE_NAME,
E.SALARY AS EMPLOYEE_SALARY,
M.EMPLOYEENAME AS MANAGER_NAME,
M.SALARY AS MANAGER_SALARY
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E1.EMPLOYEENAME AS EMPLOYEE_1,
E2.EMPLOYEENAME AS EMPLOYEE_2,
E1.MANAGERID
FROM EMPLOYEES E1
INNER JOIN EMPLOYEES E2
ON E1.MANAGERID = E2.MANAGERID
WHERE E1.EMPLOYEEID < E2.EMPLOYEEID;

SELECT E.EMPLOYEENAME AS EMPLOYEE_NAME,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
ORDER BY MANAGER_NAME ASC;

SELECT E.EMPLOYEENAME AS EMPLOYEE_NAME,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.DEPARTMENTID = M.DEPARTMENTID;

SELECT E.EMPLOYEEID,
E.EMPLOYEENAME AS EMPLOYEE_NAME,
M.EMPLOYEEID AS MANAGER_ID,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

















































































