SELECT ROW_NUMBER()                                                                       -- ROW NUMBER
OVER (ORDER BY SALARY ASC) AS ROW_NUM,
EMPLOYEEID,EMPLOYEENAME,SALARY
FROM EMPLOYEES;

SELECT ROW_NUMBER() 
OVER (ORDER BY SALARY DESC) AS ROW_NUM,
EMPLOYEEID,EMPLOYEENAME,SALARY
FROM EMPLOYEES;

SELECT ROW_NUMBER() OVER 
(PARTITION BY DEPARTMENTID
ORDER BY EMPLOYEEID) AS ROW_NUM,
EMPLOYEEID,EMPLOYEENAME,DEPARTMENT,DEPARTMENTNAME
FROM EMPLOYEES;

WITH EMPLOYEE_ROWS AS(SELECT EMPLOYEEID,
EMPLOYEENAME,DEPARTMENT,
SALARY,ROW_NUMBER() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS ROW_NUM
FROM EMPLOYEES) 
SELECT * FROM EMPLOYEE_ROWS
WHERE ROW_NUM<=3;

SELECT ROW_NUMBER() OVER 
(PARTITION BY DEPARTMENTID
ORDER BY MARK DESC) AS ROW_NUM,
STUDENTID,STUDENTNAME,MARKS,DEPARTMENTID,DEPARTMENTNAME
FROM STUDENTS;





SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,                                                               --  RANK
RANK() OVER (ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

SELECT STUDENTID,STUDENTNAME,MARKS,
RANK() OVER (ORDER BY MARKS DESC) AS MARKS_RANK
FROM STUDENTS;

SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) 
AS SALARY_RANK
FROM EMPLOYEES;

WITH RANKED_EMPLOYEES AS 
(SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES)
SELECT * FROM RANKED_EMPLOYEES
WHERE SALARY_RANK = 1;

WITH RANKED_EMPLOYEES AS 
(SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES) 
SELECT * FROM RANKED_EMPLOYEES
WHERE SALARY_RANK <= 3;





SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,                                                                  -- DENSE RANK
DENSE_RANK() OVER (ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

SELECT STUDENTID,STUDENTNAME,MARKS,
DENSE_RANK() OVER (ORDER BY MARKS DESC) AS MARKS_RANK
FROM STUDENTS;

SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
DENSE_RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;

WITH  RANKED_EMPLOYEES AS (SELECT EMPLOYEEID,
EMPLOYEENAME,DEPARTMENT,SALARY,
DENSE_RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES)
SELECT * FROM RANKED_EMPLOYEES
WHERE SALARY_RANK = 2;

SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS RANK_RESULT,
DENSE_RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS DENSE_RANK_RESULT
FROM EMPLOYEES;





SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,                                                        --  RUNNING TOTAL
SUM(SALARY) OVER (ORDER BY EMPLOYEEID) AS RUNNING_TOTAL
FROM EMPLOYEES;

SELECT SALEID,SALEDATE,SALEAMOUNT,
SUM(SALEAMOUNT) OVER (ORDER BY SALEDATE) AS RUNNING_TOTAL
FROM SALES;

SELECT CUSTOMERID,SALEID,SALEAMOUNT,
SUM(SALEAMOUNT) OVER (PARTITION BY CUSTOMERID
ORDER BY SALEDATE) AS RUNNING_TOTAL
FROM SALES;

SELECT CUSTOMERID,ORDERID,
ORDERDATE,ORDERAMOUNT,
SUM(ORDERAMOUNT) OVER (PARTITION BY CUSTOMERID
ORDER BY ORDERDATE) AS RUNNING_TOTAL
FROM ORDERS;


SELECT EMPLOYEENAME,SALARY,
SUM(SALARY) OVER (ORDER BY SALARY) AS CUMULATIVE_SALARY
FROM EMPLOYEES;





SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,                                                        --  RUNNING AVERAGE
ROUND(AVG(SALARY) OVER (ORDER BY EMPLOYEEID),2) AS RUNNING_AVERAGE
FROM EMPLOYEES;

SELECT SALEID,SALEDATE,SALEAMOUNT,
ROUND(AVG(SALEAMOUNT) OVER (ORDER BY SALEDATE,2)) AS RUNNING_AVERAGE
FROM SALES;

SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
ROUND(AVG(SALARY) OVER (PARTITION BY DEPARTMENT
ORDER BY EMPLOYEEID),2) AS RUNNING_AVERAGE
FROM EMPLOYEES;



SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,                                                   --  AGGREGATE FUNCTIONS
SUM(SALARY) OVER () AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,
ROUND(AVG(SALARY) OVER (),2) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,
MAX(SALARY) OVER () AS MAXIMUM_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
SUM(SALARY) OVER (
PARTITION BY DEPARTMENT) AS DEPARTMENT_TOTAL_SALARY
FROM EMPLOYEES;






SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,                                                        --  LEAD()   
LEAD(SALARY) OVER (ORDER BY EMPLOYEEID) AS NEXT_EMPLOYEE_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEEID,EMPLOYEENAME,JOININGDATE,
LEAD(JOININGDATE) OVER (ORDER BY EMPLOYEEID) AS NEXT_EMPLOYEE_JOININGDATE
FROM EMPLOYEES;

SELECT EMPLOYEEID,SALEDATE,SALEAMOUNT,
LEAD(SALEAMOUNT) OVER (ORDER BY SALEDATE) AS NEXT_SALE_AMOUNT
FROM SALES;

SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,
LEAD(SALARY) OVER (ORDER BY EMPLOYEEID) AS NEXT_EMPLOYEE_SALARY,
SALARY - LEAD(SALARY) OVER (ORDER BY EMPLOYEEID) AS SALARY_DIFFERENCE
FROM EMPLOYEES;





SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,                                                             --  LAG()
LAG(SALARY) OVER (ORDER BY EMPLOYEEID) AS PREVIOUS_EMPLOYEE_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEEID,EMPLOYEENAME,JOININGDATE,
LAG(JOININGDATE) OVER (ORDER BY EMPLOYEEID) AS PREVIOUS_EMPLOYEE_JOININGDATE
FROM EMPLOYEES;


SELECT SALEID,SALEDATE,SALEAMOUNT,
LAG(SALEAMOUNT) OVER (ORDER BY SALEDATE) AS PREVIOUS_SALE_AMOUNT
FROM SALES;

SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,
LAG(SALARY) OVER (ORDER BY EMPLOYEEID) AS PREVIOUS_EMPLOYEE_SALARY,
SALARY - LAG(SALARY) OVER (ORDER BY EMPLOYEEID) AS SALARY_DIFFERENCE
FROM EMPLOYEES;




WITH RANKED_EMPLOYEES AS (SELECT EMPLOYEENAME,                                                 -- ADVANCED WINDOW FUNCTION
DEPARTMENT,SALARY,
ROW_NUMBER() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROW_NUM
FROM EMPLOYEES) 
SELECT * FROM RANKED_EMPLOYEES
WHERE ROW_NUM = 1;

WITH RANKED_EMPLOYEES AS (SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
DENSE_RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES) 
SELECT * FROM RANKED_EMPLOYEES
WHERE SALARY_RANK = 2;

SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
AVG(SALARY) OVER (PARTITION BY DEPARTMENT) AS DEPARTMENT_AVERAGE_SALARY,
SALARY - AVG(SALARY) OVER (PARTITION BY DEPARTMENT) AS DIFFERENCE_FROM_AVERAGE
FROM EMPLOYEES;

SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,
LAG(SALARY) OVER (ORDER BY EMPLOYEEID) AS PREVIOUS_EMPLOYEE_SALARY,
LEAD(SALARY) OVER (ORDER BY EMPLOYEEID) AS NEXT_EMPLOYEE_SALARY
FROM EMPLOYEES;

SELECT EMPLOYEENAME,DEPARTMENT,SALARY,
ROW_NUMBER() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS ROW_NUM,
RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS SALARY_RANK,
DENSE_RANK() OVER (PARTITION BY DEPARTMENT
ORDER BY SALARY DESC) AS DENSE_SALARY_RANK
FROM EMPLOYEES;









































