SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES;

SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES;

SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES;

SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEES;

SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES;

SELECT DEPARTMENT,
COUNT(*) AS TOTAL_STUDENTS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
AVG(MARKS) AS AVERAGE_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,
MAX(MARKS) AS HIGHEST_MARKS,
MIN(MARKS) AS LOWEST_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT CUSTOMERID,
SUM(SALESAMOUNT) AS TOTAL_SALES
FROM SALES
GROUP BY CUSTOMERID;

SELECT CATEGORY,
AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;


-- CHALLENGE QUESTIONS


SELECT EMPLOYEENAME,SALARY,                 
SALARY * 12 AS ANNUAL_SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 5;

SELECT UPPER(EMPLOYEENAME) AS EMPLOYEE_NAME,
LENGTH(EMPLOYEENAME) AS NAME_LENGTH
FROM EMPLOYEES
ORDER BY NAME_LENGTH DESC;

SELECT PRODUCTNAME,
ROUND(PRICE, 2) AS ROUNDED_PRICE
FROM PRODUCTS
ORDER BY PRICE DESC;

SELECT *
FROM PRODUCTS
ORDER BY PRICE DESC
LIMIT 10 OFFSET 10;

SELECT DEPARTMENT,
AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY AVERAGE_SALARY DESC
LIMIT 1;

SELECT EMPLOYEENAME,SALARY,
SALARY * 12 AS ANNUAL_SALARY,
ROUND(SALARY,3) AS ROUNDED_SALARY,
CASE WHEN SALARY>=70000 THEN 'HIGH'
WHEN SALARY>=40000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY
FROM EMPLOYEES
ORDER BY ANNUAL_SALARY DESC;