-- BANKING SYSTEM

-- 1
DELIMITER //

CREATE PROCEDURE TRANSFER_MONEY
(IN FROM_ACCOUNT INT,IN TO_ACCOUNT INT,
IN TRANSFER_AMOUNT DECIMAL(10,2))
BEGIN
UPDATE ACCOUNTS
SET BALANCE = BALANCE - TRANSFER_AMOUNT
WHERE ACCOUNTNUMBER = FROM_ACCOUNT;
UPDATE ACCOUNTS
SET BALANCE = BALANCE + TRANSFER_AMOUNT
WHERE ACCOUNTNUMBER = TO_ACCOUNT;
END //

DELIMITER ;


-- 2
DELIMITER //

CREATE PROCEDURE CHECK_ACCOUNT_BALANCE
(IN ACCOUNT_NO INT)
BEGIN
SELECT ACCOUNTNUMBER,BALANCE
FROM ACCOUNTS
WHERE ACCOUNTNUMBER = ACCOUNT_NO;
END //

DELIMITER ;


-- 3
DELIMITER //

CREATE PROCEDURE DEPOSIT_MONEY
(IN ACCOUNT_NO INT,IN DEPOSIT_AMOUNT DECIMAL(10,2))
BEGIN
UPDATE ACCOUNTS
SET BALANCE = BALANCE + DEPOSIT_AMOUNT
WHERE ACCOUNTNUMBER = ACCOUNT_NO;
INSERT INTO TRANSACTIONS 	
(ACCOUNTNUMBER,TRANSACTIONTYPE,
AMOUNT,TRANSACTIONDATE)
VALUES (ACCOUNT_NO,'DEPOSIT',
DEPOSIT_AMOUNT,CURDATE());
END //

DELIMITER ;


-- 4
DELIMITER //

CREATE PROCEDURE WITHDRAW_MONEY
(IN ACCOUNT_NO INT,IN WITHDRAW_AMOUNT DECIMAL(10,2))
BEGIN
IF (SELECT BALANCE FROM ACCOUNTS
WHERE ACCOUNTNUMBER = ACCOUNT_NO) >= WITHDRAW_AMOUNT
THEN
UPDATE ACCOUNTS
SET BALANCE =
CASE WHEN BALANCE >= WITHDRAW_AMOUNT
THEN BALANCE - WITHDRAW_AMOUNT
ELSE BALANCE
END
WHERE ACCOUNTNUMBER = ACCOUNT_NO;
INSERT INTO TRANSACTIONS
(ACCOUNTNUMBER,TRANSACTIONTYPE,
AMOUNT,TRANSACTIONDATE)
VALUES(ACCOUNT_NO,'WITHDRAW',
WITHDRAW_AMOUNT,CURDATE());
SELECT 'WITHDRAWAL SUCCESSFUL' AS MESSAGE;
ELSE
SELECT 'INSUFFICIENT BALANCE' AS MESSAGE;
END IF;
END //
DELIMITER ;


-- 5
DELIMITER //

CREATE PROCEDURE MONTHLY_BANK_STATEMENT
(IN CUSTOMER_ID INT,IN STATEMENT_MONTH INT,IN STATEMENT_YEAR INT)
BEGIN
SELECT C.CUSTOMERID,C.CUSTOMERNAME,
c.ACCOUNTNUMBER,T.TRANSACTIONTYPE,
T.AMOUNT,T.TRANSACTIONDATE
FROM CUSTOMERS C
INNER JOIN TRANSACTIONS T
ON C.ACCOUNTNUMBER = T.ACCOUNTNUMBER
WHERE C.CUSTOMERID = CUSTOMER_ID
AND MONTH(T.TRANSACTIONDATE) = STATEMENT_MONTH
AND YEAR(T.TRANSACTIONDATE) = STATEMENT_YEAR;
END //

DELIMITER ;



-- E-COMMERCE SYSTEM


-- 6
DELIMITER //
CREATE PROCEDURE PLACE_ORDER
(IN CUSTOMER_ID INT,IN PRODUCT_ID INT,
IN ORDER_QUANTITY INT,IN UNIT_PRICE DECIMAL(10,2))
BEGIN
INSERT INTO ORDERS (CUSTOMERID,PRODUCTID,
QUANTITY,UNITPRICE,TOTALAMOUNT,ORDERDATE)
VALUES (CUSTOMER_ID,PRODUCT_ID,ORDER_QUANTITY,
UNIT_PRICE,ORDER_QUANTITY * UNIT_PRICE,CURDATE());
END //

DELIMITER ;


-- 7
DELIMITER //

CREATE PROCEDURE ADD_PRODUCT_TO_ORDER
(IN ORDER_ID INT,IN PRODUCT_ID INT,
IN ORDER_QUANTITY INT,IN UNIT_PRICE DECIMAL(10,2))
BEGIN
INSERT INTO ORDER_ITEMS 
(ORDERID,PRODUCTID,
QUANTITY,UNITPRICE)
VALUES (ORDER_ID,PRODUCT_ID,
ORDER_QUANTITY,UNIT_PRICE);
UPDATE ORDERS
SET TOTALAMOUNT = TOTALAMOUNT +(ORDER_QUANTITY * UNIT_PRICE)
WHERE ORDERID = ORDER_ID;
END //

DELIMITER ;


-- 8
DELIMITER //

CREATE PROCEDURE CHECK_PRODUCT_STOCK
(IN PRODUCT_ID INT)
BEGIN
IF(SELECT STOCK FROM PRODUCTS
WHERE PRODUCTID = PRODUCT_ID) > 0
THEN
SELECT 'PRODUCT AVAILABLE' AS MESSAGE;
ELSE
SELECT 'OUT OF STOCK' AS MESSAGE;
END IF;
END //

DELIMITER ;


-- 9
DELIMITER //

CREATE PROCEDURE REDUCE_PRODUCT_STOCK
(IN PRODUCT_ID INT,IN ORDER_QUANTITY INT)
BEGIN
UPDATE PRODUCTS
SET STOCK = STOCK - ORDER_QUANTITY
WHERE PRODUCTID = PRODUCT_ID;
END //

DELIMITER ;


-- 10
DELIMITER //

CREATE PROCEDURE CANCEL_ORDER
(IN ORDER_ID INT)
BEGIN
UPDATE PRODUCTS P
INNER JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
SET P.STOCK = P.STOCK + O.QUANTITY
WHERE O.ORDERID = ORDER_ID;
DELETE FROM ORDERS
WHERE ORDERID = ORDER_ID;
END //

DELIMITER ;


-- 11
DELIMITER //

CREATE PROCEDURE CUSTOMER_TOTAL_SPENT
(IN CUSTOMER_ID INT,IN START_DATE DATE,IN END_DATE DATE)
BEGIN
SELECT CUSTOMERID,
SUM(TOTALAMOUNT) AS TOTAL_AMOUNT_SPENT
FROM ORDERS
WHERE CUSTOMERID = CUSTOMER_ID
AND ORDERDATE BETWEEN START_DATE AND END_DATE
GROUP BY CUSTOMERID;
END //

DELIMITER ;


-- 12
DELIMITER //

CREATE PROCEDURE CUSTOMER_PENDING_ORDERS
(IN CUSTOMER_ID INT)
BEGIN
SELECT ORDERID,CUSTOMERID,PRODUCTID,
QUANTITY,TOTALAMOUNT,ORDERDATE,ORDERSTATUS
FROM ORDERS
WHERE CUSTOMERID = CUSTOMER_ID
AND ORDERSTATUS = 'PENDING';
END //

DELIMITER ;




--  EMPLOYEE / HR SYSTEM

-- 13
DELIMITER //

CREATE PROCEDURE GET_EMPLOYEES_BY_DEPARTMENT
(IN DEPT_ID INT)
BEGIN
SELECT EMPLOYEEID,EMPLOYEENAME,DEPARTMENTID,
DESIGNATION,SALARY
FROM EMPLOYEES
WHERE DEPARTMENTID = DEPT_ID;
END //

DELIMITER ;


-- 14
DELIMITER //

CREATE PROCEDURE INCREASE_SALARY
(IN EMP_ID INT,IN PERCENTAGE DECIMAL(5,2))
BEGIN
UPDATE EMPLOYEES
SET SALARY = SALARY + (SALARY * PERCENTAGE / 100)
WHERE EMPLOYEEID = EMP_ID;
END //

DELIMITER ;


-- 15
DELIMITER //

CREATE PROCEDURE CALCULATE_ANNUAL_SALARY
(IN EMP_ID INT)
BEGIN
SELECT EMPLOYEEID,EMPLOYEENAME,
SALARY AS MONTHLY_SALARY,SALARY * 12 AS ANNUAL_SALARY
FROM EMPLOYEES
WHERE EMPLOYEEID = EMP_ID;
END //

DELIMITER ;


-- 16
DELIMITER //

CREATE PROCEDURE GET_EMPLOYEES_BY_SALARY
(IN GIVEN_SALARY DECIMAL(10,2))
BEGIN
SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENTID,SALARY
FROM EMPLOYEES
WHERE SALARY > GIVEN_SALARY;
END //

DELIMITER ;


-- 17
DELIMITER //

CREATE PROCEDURE DEPARTMENT_SALARY_REPORT()
BEGIN
SELECT DEPARTMENTID,DEPARTMENTNAME,
COUNT(EMPLOYEEID) AS TOTAL_EMPLOYEES,
SUM(SALARY) AS TOTAL_SALARY,
ROUND(AVG(SALARY)) AS AVERAGE_SALARY,
MAX(SALARY) AS HIGHEST_SALARY,
MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENTID;
END //

DELIMITER ;


-- 18
DELIMITER //

CREATE PROCEDURE DEPARTMENT_TOTAL_SALARY
(IN DEPT_ID INT)
BEGIN
SELECT DEPARTMENTID,
SUM(SALARY) AS TOTAL_SALARY_EXPENSE
FROM EMPLOYEES
WHERE DEPARTMENTID = DEPT_ID
GROUP BY DEPARTMENTID;
END //

DELIMITER ;



-- STUDENT MANAGEMENT SYSTEM

-- 19
DELIMITER //

CREATE PROCEDURE GET_STUDENTS_BY_COURSE
(IN COURSE_NAME VARCHAR(30))
BEGIN
SELECT STUDENTID,STUDENTNAME,COURSENAME
FROM STUDENTS
WHERE COURSENAME = COURSE_NAME;
END //

DELIMITER ;


-- 20
DELIMITER //

CREATE PROCEDURE STUDENT_TOTAL_AND_AVERAGE
(IN STUDENT_ID INT)
BEGIN
SELECT STUDENTID,
SUM(MARKS) AS TOTAL_MARKS,
ROUND(AVG(MARKS)) AS AVERAGE_MARKS
FROM MARKS
WHERE STUDENTID = STUDENT_ID
GROUP BY STUDENTID;
END //

DELIMITER ;


-- 21
DELIMITER //

CREATE PROCEDURE STUDENT_RESULT
(IN STUDENT_ID INT)
BEGIN
SELECT STUDENTID,MARKS,
CASE WHEN MARKS >= 40 THEN 'PASSED'
ELSE 'FAILED'
END AS RESULT
FROM MARKS
WHERE STUDENTID = STUDENT_ID;
END //

DELIMITER ;


-- 22
DELIMITER //

CREATE PROCEDURE STUDENTS_ABOVE_AVERAGE
(IN GIVEN_MARK DECIMAL(5,2))
BEGIN
SELECT STUDENTID,STUDENTNAME,
ROUND(AVG(MARKS)) AS AVERAGE_MARKS
FROM STUDENTS 
GROUP BY S.STUDENTID,S.STUDENTNAME
HAVING AVG(MARKS) > GIVEN_MARK;
END //

DELIMITER ;


-- 23
DELIMITER //

CREATE PROCEDURE STUDENT_RESULT_REPORT()
BEGIN
SELECT S.STUDENTID,S.STUDENTNAME,
SUM(MARKS) AS TOTAL_MARKS,
ROUND(AVG(MARKS), 2) AS AVERAGE_MARKS,
CASE WHEN AVG(MARKS) >= 90 THEN 'A'
WHEN AVG(MARKS) >= 75 THEN 'B'
WHEN AVG(MARKS) >= 50 THEN 'C'
ELSE 'F'
END AS GRADE,
CASE WHEN AVG(M.MARKS) >= 50 THEN 'PASSED'
ELSE 'FAILED'
END AS RESULT_STATUS
FROM STUDENTS 
GROUP BY STUDENTID,STUDENTNAME;
END //

DELIMITER ;




-- HOSPITAL MANAGEMENT SYSTEM

-- 24
DELIMITER //

CREATE PROCEDURE GET_DOCTOR_APPOINTMENTS
(IN DOCTOR_ID INT,IN APPOINTMENT_DATE DATE)
BEGIN
SELECT APPOINTMENTID,PATIENTID,DOCTORID,
APPOINTMENTDATE,APPOINTMENTSTATUS
FROM APPOINTMENTS
WHERE DOCTORID = DOCTOR_ID
AND APPOINTMENTDATE = APPOINTMENT_DATE;
END //

DELIMITER ;


-- 25
DELIMITER //

CREATE PROCEDURE CALCULATE_PATIENT_BILL
(IN PATIENT_ID INT)
BEGIN
SELECT PATIENTID,
SUM(BILLAMOUNT) AS TOTAL_BILL_AMOUNT
FROM PATIENT_BILLS
WHERE PATIENTID = PATIENT_ID
GROUP BY PATIENTID;
END //

DELIMITER ;


-- 26
DELIMITER //

CREATE PROCEDURE GET_ADMITTED_PATIENTS
(IN START_DATE DATE,IN END_DATE DATE)
BEGIN
SELECT PATIENTID,PATIENTNAME,
ADMISSIONDATE,DISCHARGEDATE
FROM PATIENTS
WHERE ADMISSIONDATE BETWEEN START_DATE AND END_DATE;
END //

DELIMITER ;


-- 27
DELIMITER //

CREATE PROCEDURE UPDATE_PATIENT_DISCHARGE
(IN PATIENT_ID INT,IN DISCHARGE_STATUS VARCHAR(20),IN DISCHARGE_DATE DATE)
BEGIN
UPDATE PATIENTS
SET STATUS = DISCHARGE_STATUS,
DISCHARGEDATE = DISCHARGE_DATE
WHERE PATIENTID = PATIENT_ID;
END //

DELIMITER ;




-- INVENTORY MANAGEMENT

-- 28 
DELIMITER //

CREATE PROCEDURE LOW_STOCK_PRODUCTS()
BEGIN
SELECT PRODUCTID,PRODUCTNAME,
STOCK,REORDERLEVEL
FROM PRODUCTS
WHERE STOCK < REORDERLEVEL;
END //

DELIMITER ;


-- 29
DELIMITER //

CREATE PROCEDURE INCREASE_PRODUCT_STOCK
(IN PRODUCT_ID INT,IN SHIPMENT_QUANTITY INT)
BEGIN
UPDATE PRODUCTS
SET STOCK = STOCK + SHIPMENT_QUANTITY
WHERE PRODUCTID = PRODUCT_ID;
END //

DELIMITER ;


-- 30
DELIMITER //

CREATE PROCEDURE INVENTORY_REPORT()
BEGIN
SELECT PRODUCTNAME,STOCK AS AVAILABLE_QUANTITY,REORDERLEVEL,
CASE WHEN STOCK < REORDERLEVEL THEN 'LOW STOCK'
ELSE 'IN STOCK'
END AS STOCK_STATUS
FROM PRODUCTS;
END //

DELIMITER ;



-- TIME SCENARIOS


-- 31
DELIMITER //

CREATE PROCEDURE TRANSFER_MONEY_TRANSACTION
(IN FROM_ACCOUNT INT,IN TO_ACCOUNT INT,
IN TRANSFER_AMOUNT DECIMAL(10,2))
BEGIN
START TRANSACTION;
IF (SELECT BALANCE FROM ACCOUNTS
WHERE ACCOUNTNUMBER = FROM_ACCOUNT) >= TRANSFER_AMOUNT
THEN
UPDATE ACCOUNTS
SET BALANCE = BALANCE - TRANSFER_AMOUNT
WHERE ACCOUNTNUMBER = FROM_ACCOUNT;
UPDATE ACCOUNTS
SET BALANCE = BALANCE + TRANSFER_AMOUNT
WHERE ACCOUNTNUMBER = TO_ACCOUNT;
COMMIT;
SELECT 'TRANSFER SUCCESSFUL' AS MESSAGE;
ELSE
ROLLBACK;
SELECT 'INSUFFICIENT BALANCE' AS MESSAGE;
END IF;
END //

DELIMITER ;


-- 32
DELIMITER //

CREATE PROCEDURE PLACE_MULTI_TABLE_ORDER
(IN CUSTOMER_ID INT,IN PRODUCT_ID INT,IN ORDER_QUANTITY INT)
BEGIN
INSERT INTO ORDERS
(CUSTOMERID,PRODUCTID,QUANTITY,
UNITPRICE,TOTALAMOUNT,ORDERDATE,ORDERSTATUS)
SELECT CUSTOMER_ID,PRODUCT_ID,ORDER_QUANTITY,
P.PRICE,ORDER_QUANTITY * PRICE,CURDATE(),'PENDING'
FROM PRODUCTS P
WHERE PRODUCTID = PRODUCT_ID;
UPDATE PRODUCTS
SET STOCK = STOCK - ORDER_QUANTITY
WHERE PRODUCTID = PRODUCT_ID;
END //

DELIMITER ;

-- 33
DELIMITER //

CREATE PROCEDURE CUSTOMER_ORDER_SUMMARY
(IN CUSTOMER_ID INT,IN START_DATE DATE,IN END_DATE DATE)
BEGIN
SELECT CUSTOMERID,
COUNT(ORDERID) AS TOTAL_ORDERS,
SUM(TOTALAMOUNT) AS TOTAL_SPENDING
FROM ORDERS
WHERE CUSTOMERID = CUSTOMER_ID
AND ORDERDATE BETWEEN START_DATE AND END_DATE
GROUP BY CUSTOMERID;
END //

DELIMITER ;


-- 34
DELIMITER //

CREATE PROCEDURE UPDATE_EMPLOYEE_SALARY
(IN EMP_ID INT,IN NEW_SALARY DECIMAL(10,2))
BEGIN
DECLARE OLD_SALARY DECIMAL(10,2);
SELECT SALARY INTO OLD_SALARY
FROM EMPLOYEES
WHERE EMPLOYEEID = EMP_ID;
UPDATE EMPLOYEES
SET SALARY = NEW_SALARY
WHERE EMPLOYEEID = EMP_ID;
INSERT INTO SALARY_AUDIT 
(EMPLOYEEID,OLD_SALARY,
NEW_SALARY,UPDATEDATE)
VALUES (EMP_ID,OLD_SALARY,
NEW_SALARY,CURDATE());
END //

DELIMITER ;


-- 35
DELIMITER //

CREATE PROCEDURE DELETE_CUSTOMER_IF_NO_ORDERS
(IN CUSTOMER_ID INT)
BEGIN
IF NOT EXISTS (SELECT * FROM ORDERS
WHERE CUSTOMERID = CUSTOMER_ID
AND STATUS = 'ACTIVE')
THEN
DELETE FROM CUSTOMERS
WHERE CUSTOMERID = CUSTOMER_ID;
ELSE
SELECT 'CUSTOMER HAS ACTIVE ORDERS. CANNOT DELETE.' AS MESSAGE;
END IF;
END //

DELIMITER ;


-- 36
DELIMITER //

CREATE PROCEDURE CALCULATE_EMPLOYEE_BONUS
(IN EMP_ID INT,IN PERFORMANCE_RATING VARCHAR(20))
BEGIN
SELECT EMPLOYEEID,EMPLOYEENAME,SALARY,
CASE WHEN PERFORMANCE_RATING = 'EXCELLENT' THEN SALARY * 0.20
WHEN PERFORMANCE_RATING = 'GOOD'THEN SALARY * 0.10
WHEN PERFORMANCE_RATING = 'AVERAGE'THEN SALARY * 0.05
ELSE 0
END AS BONUS
FROM EMPLOYEES
WHERE EMPLOYEEID = EMP_ID;
END //

DELIMITER ;


-- 37
DELIMITER //

CREATE PROCEDURE GET_INACTIVE_CUSTOMERS()
BEGIN
SELECT C.CUSTOMERID,C.CUSTOMERNAME
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERID,C.CUSTOMERNAME
HAVING MAX(O.ORDERDATE) < DATE_SUB(CURDATE(), INTERVAL 6 MONTH);
END //

DELIMITER ;


-- 38
DELIMITER //

CREATE PROCEDURE MONTHLY_SALES_REPORT
(IN REPORT_MONTH INT,IN REPORT_YEAR INT)
BEGIN
SELECT COUNT(ORDERID) AS TOTAL_ORDERS,
SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD,
SUM(QUANTITY * UNITPRICE) AS TOTAL_REVENUE
FROM ORDERS
WHERE MONTH(ORDERDATE) = REPORT_MONTH
AND YEAR(ORDERDATE) = REPORT_YEAR;
END //

DELIMITER ;


-- 39
DELIMITER //

CREATE PROCEDURE CHECK_PRODUCT_ORDER
(IN PRODUCT_ID INT,IN REQUIRED_QUANTITY INT)
BEGIN
IF  (SELECT AVAILABLE_STOCK FROM PRODUCTS
WHERE PRODUCTID = PRODUCT_ID) >= REQUIRED_QUANTITY THEN
SELECT 'PRODUCT CAN BE ORDERED' AS MESSAGE;
ELSE
SELECT 'INSUFFICIENT STOCK' AS MESSAGE;
END IF;
END //

DELIMITER ;


-- 40
DELIMITER //

CREATE PROCEDURE PROCESS_ORDER
(IN CUSTOMER_ID INT,IN PRODUCT_ID INT,IN ORDER_QUANTITY INT)
BEGIN
START TRANSACTION;

IF NOT EXISTS
(SELECT * FROM CUSTOMERS
WHERE CUSTOMERID = CUSTOMER_ID) THEN
SELECT 'CUSTOMER DOES NOT EXIST' AS MESSAGE;
ROLLBACK;
ELSE

IF NOT EXISTS
(SELECT * FROM PRODUCTS
WHERE PRODUCTID = PRODUCT_ID)THEN
SELECT 'PRODUCT DOES NOT EXIST' AS MESSAGE;
ROLLBACK;
ELSE

IF NOT EXISTS
(SELECT * FROM PRODUCTS
WHERE PRODUCTID = PRODUCT_ID
AND STOCK >= ORDER_QUANTITY)THEN
SELECT 'INSUFFICIENT STOCK' AS MESSAGE;
ROLLBACK;
ELSE

INSERT INTO ORDERS
(CUSTOMERID,PRODUCTID,QUANTITY,
UNITPRICE,TOTALAMOUNT,ORDERDATE,STATUS)
SELECT CUSTOMER_ID,PRODUCT_ID,ORDER_QUANTITY,
P.PRICE,ORDER_QUANTITY * P.PRICE,CURDATE(),
'COMPLETED' FROM PRODUCTS P
WHERE P.PRODUCTID = PRODUCT_ID;

UPDATE PRODUCTS
SET STOCK = STOCK - ORDER_QUANTITY
WHERE PRODUCTID = PRODUCT_ID;
COMMIT;
SELECT 'ORDER PROCESSED SUCCESSFULLY' AS MESSAGE;
END IF;
END IF;
END IF;
END //

DELIMITER ;





