SELECT UPPER(EMPLOYEENAME) AS UPPERCASE_NAME                      -- 1
FROM EMPLOYEES;

SELECT LOWER(EMPLOYEENAME) AS LOWERCASE_NAME                      -- 2
FROM EMPLOYEES;

SELECT EMPLOYEENAME,                                              -- 3
LENGTH(EMPLOYEENAME) AS NAME_LENGTH
FROM EMPLOYEES;

SELECT EMPLOYEENAME,                                              -- 4
LEFT(EMPLOYEENAME, 3) AS FIRST_3_CHARACTERS
FROM EMPLOYEES;

SELECT EMPLOYEENAME,                                             -- 5
RIGHT(EMPLOYEENAME, 3) AS LAST_3_CHARACTERS
FROM EMPLOYEES;

SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULL_NAME              -- 6
FROM EMPLOYEES;

SELECT CUSTOMERNAME,                                             -- 7
TRIM(CUSTOMERNAME) AS TRIMMED_CUSTOMER_NAME
FROM CUSTOMERS;

SELECT CITY,                                                      -- 8
REPLACE(CITY, 'CHENNAI', 'MADRAS') AS UPDATED_CITY
FROM CUSTOMERS;