USE EMPLOYEEDB;                                              #BASIC SUBQUERY
SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES); 

SELECT * FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES); 

SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES); 

SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES); 

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS); 

SELECT * FROM PRODUCTS
WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE > (SELECT AVG(PRICE) FROM BOOKS); 

SELECT * FROM BOOKS
WHERE PRICE < (SELECT AVG(PRICE) FROM BOOKS);

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS); 

SELECT * FROM STUDENTS
WHERE AGE < (SELECT AVG(AGE) FROM STUDENTS);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS); 

SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE = (SELECT MAX(PRICE) FROM BOOKS);

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE = (SELECT MAX(AGE) FROM STUDENTS); 

SELECT * FROM STUDENTS
WHERE AGE = (SELECT MIN(AGE) FROM STUDENTS); 

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES > (SELECT AVG(FEES) FROM COURSES); 

SELECT * FROM COURSES
WHERE FEES < (SELECT AVG(FEES) FROM COURSES);

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING > (SELECT AVG(RATING) FROM MOVIES); 





USE EMPLOYEEDB;                                            #SUBQUERY WITH IN
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE EMPLOYEENAME = 'RAHUL');  

USE STUDENTDB;                                           
SELECT * FROM STUDENTS
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE STUDENTNAME = 'ANU');  

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY IN (SELECT CATEGORY FROM PRODUCTS WHERE PRODUCTNAME = 'LAPTOP');

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY IN (SELECT CATEGORY FROM BOOKS WHERE TITLE = 'SQL BASICS');

USE EMPLOYEEDB;                                            
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE SALARY>60000.00);  

USE STUDENTDB;                                           
SELECT * FROM STUDENTS
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE AGE>22); 

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY IN (SELECT CATEGORY FROM PRODUCTS WHERE PRICE>50000.00);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY IN (SELECT CATEGORY FROM BOOKS WHERE PRICE>1000.00);

USE EMPLOYEEDB;                                            
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE DESIGNATION='MANAGER'); 

USE COURSEDB;
SELECT * FROM COURSES
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM COURSES WHERE FEES>50000.00);

USE STUDENTDB;                                           
SELECT * FROM STUDENTS
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE AGE>25);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE CATEGORY IN (SELECT CATEGORY FROM PRODUCTS WHERE AVAILABLESTOCK>100);

USE EMPLOYEEDB;                                            
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE SALARY>70000.00); 

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE CATEGORY IN (SELECT CATEGORY FROM BOOKS WHERE PRICE>1500.00);

USE ECOMMERCEDB;
SELECT * FROM CUSTOMERS
WHERE CITY IN (SELECT CITY FROM CUSTOMERS WHERE STATE='TAMILNADU');

USE EMPLOYEEDB;                                            
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM EMPLOYEES WHERE SALARY<30000.00);

USE STUDENTDB;                                           
SELECT * FROM STUDENTS
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM STUDENTS WHERE AGE BETWEEN 20 AND 25);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE BRAND IN (SELECT BRAND FROM PRODUCTS WHERE PRICE>50000.00);

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE AUTHOR IN (SELECT AUTHOR FROM BOOKS WHERE PRICE>1000.00);

USE COURSEDB;
SELECT * FROM COURSES
WHERE DEPARTMENT IN (SELECT DEPARTMENT FROM COURSES WHERE COURSEDURATION='6 MONMTHS');





USE EMPLOYEEDB;                             #SUBQUERY WITH AGGREGATE FUNCTIONS
SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT'); 

USE EMPLOYEEDB;                             
SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR'); 

USE EMPLOYEEDB;                             
SELECT * FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'FINANCE'); 

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY='ELECTRONICS'); 

SELECT * FROM PRODUCTS
WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY='ACCESSORIES');

 USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE > (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY='TECHNOLOGY'); 

SELECT * FROM BOOKS
WHERE PRICE < (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY = 'SCIENCE');

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = 'IT'); 

SELECT * FROM STUDENTS
WHERE AGE < (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = 'CSE');

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES > (SELECT AVG(FEES) FROM COURSES WHERE DEPARTMENT = 'CSE'); 

SELECT * FROM COURSES
WHERE FEES < (SELECT AVG(FEES) FROM COURSES WHERE DEPARTMENT = 'IT');

USE EMPLOYEEDB;                             
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'IT'); 
                            
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = 'HR'); 

USE SHOPPINGDB;
SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS WHERE CATEGORY='ELECTRONICS'); 

SELECT * FROM PRODUCTS
WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS WHERE CATEGORY='ACCESSORIES');

USE LIBRARYDB;
SELECT * FROM BOOKS
WHERE PRICE = (SELECT MAX(PRICE) FROM BOOKS WHERE CATEGORY='TECHNOLOGY'); 

USE STUDENTDB;
SELECT * FROM STUDENTS
WHERE AGE = (SELECT MAX(AGE) FROM STUDENTS WHERE DEPARTMENT = 'CSE'); 

SELECT * FROM STUDENTS
WHERE AGE = (SELECT MIN(AGE) FROM STUDENTS WHERE DEPARTMENT = 'IT');

USE COURSEDB;
SELECT * FROM COURSES
WHERE FEES = (SELECT MAX(FEES) FROM COURSES WHERE DEPARTMENT = 'CSE'); 

USE MOVIEDB;
SELECT * FROM MOVIES
WHERE RATING = (SELECT MAX(RATING) FROM MOVIES);




USE EMPLOYEEDB;                             #CORRELATED SUBQUERY 
SELECT * FROM EMPLOYEES E
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT); 

SELECT * FROM EMPLOYEES E
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT); 

USE STUDENTDB;
SELECT * FROM STUDENTS S
WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);

SELECT * FROM STUDENTS S
WHERE AGE < (SELECT AVG(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS P
WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY=P.CATEGORY); 

SELECT * FROM PRODUCTS P
WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY=P.CATEGORY); 

USE LIBRARYDB;
SELECT * FROM BOOKS B
WHERE PRICE > (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY=B.CATEGORY); 

SELECT * FROM BOOKS B
WHERE PRICE < (SELECT AVG(PRICE) FROM BOOKS WHERE CATEGORY=B.CATEGORY); 

USE EMPLOYEEDB;                            
SELECT * FROM EMPLOYEES E
WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT); 

SELECT * FROM EMPLOYEES E
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT = E.DEPARTMENT); 

USE STUDENTDB;
SELECT * FROM STUDENTS S
WHERE AGE = (SELECT MAX(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);

SELECT * FROM STUDENTS S
WHERE AGE = (SELECT MIN(AGE) FROM STUDENTS WHERE DEPARTMENT = S.DEPARTMENT);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS P
WHERE PRICE = (SELECT MAX(PRICE) FROM PRODUCTS WHERE CATEGORY=P.CATEGORY); 

SELECT * FROM PRODUCTS P
WHERE PRICE = (SELECT MIN(PRICE) FROM PRODUCTS WHERE CATEGORY=P.CATEGORY); 

USE LIBRARYDB;
SELECT * FROM BOOKS B
WHERE PRICE = (SELECT MAX(PRICE) FROM BOOKS WHERE CATEGORY=B.CATEGORY); 

SELECT * FROM BOOKS B
WHERE PRICE = (SELECT MIN(PRICE) FROM BOOKS WHERE CATEGORY=B.CATEGORY); 

USE EMPLOYEEDB;                              
SELECT * FROM EMPLOYEES E
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DESIGNATION = E.DESIGNATION);

USE SHOPPINGDB;
SELECT * FROM PRODUCTS P
WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS WHERE BRAND=P.BRAND); 

USE STUDENTDB;
SELECT * FROM STUDENTS S
WHERE AGE > (SELECT AVG(AGE) FROM STUDENTS WHERE GENDER = S.GENDER);

USE COURSEDB;
SELECT * FROM COURSES C 
WHERE FEES > (SELECT AVG(FEES) FROM COURSES WHERE DEPARTMENT = C.DEPARTMENT);




USE EMPLOYEEDB;                                       #SUBQUERY WITH ANY AND ALL        
SELECT * FROM EMPLOYEES 
WHERE SALARY > ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');

SELECT * FROM EMPLOYEES 
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'HR');

SELECT * FROM EMPLOYEES 
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'IT');

SELECT * FROM EMPLOYEES 
WHERE SALARY < ALL (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT = 'IT');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE > ANY (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');

SELECT * FROM PRODUCTS 
WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ELECTRONICS');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE < ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

SELECT * FROM BOOKS 
WHERE PRICE < ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'TECHNOLOGY');

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE AGE > ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');

SELECT * FROM STUDENTS
WHERE AGE > ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'CSE');

USE COURSEDB;
SELECT * FROM COURSES 
WHERE FEES > ANY (SELECT FEES FROM STUDENTS WHERE DEPARTMENT = 'IT');

SELECT * FROM COURSES
WHERE FEES > ALL (SELECT FEES FROM STUDENTS WHERE DEPARTMENT = 'IT');

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES 
WHERE SALARY = ANY (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'DEVELOPER');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE = ANY (SELECT PRICE FROM PRODUCTS WHERE BRAND = 'SAMSUNG');

USE LIBRARYDB;
SELECT * FROM BOOKS 
WHERE PRICE > ANY (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'SCIENCE');

SELECT * FROM BOOKS 
WHERE PRICE > ALL (SELECT PRICE FROM BOOKS WHERE CATEGORY = 'SCIENCE');

USE STUDENTDB;
SELECT * FROM STUDENTS 
WHERE AGE < ANY (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'IT');

SELECT * FROM STUDENTS
WHERE AGE < ALL (SELECT AGE FROM STUDENTS WHERE DEPARTMENT = 'IT');

USE EMPLOYEEDB;
SELECT * FROM EMPLOYEES 
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE DESIGNATION = 'TESTERS');

USE SHOPPINGDB;
SELECT * FROM PRODUCTS 
WHERE PRICE > ALL (SELECT PRICE FROM PRODUCTS WHERE CATEGORY = 'ACCESSORIES');