CREATE TEMPORARY TABLE TEMP_EMPLOYEES                                              --  TEMPORARY TABLE
(EMPLOYEEID INT,                                                                    -- 1
EMPLOYEENAME VARCHAR(50),
DEPARTMENT VARCHAR(50),
SALARY DECIMAL(10,2));

INSERT INTO TEMP_EMPLOYEES (EMPLOYEEID, EMPLOYEENAME, DEPARTMENT, SALARY)              -- 2
VALUES(101, 'RAJESH', 'IT', 60000),(102, 'KUMAR', 'HR', 55000),
(103, 'SURESH', 'SALES', 50000),(104, 'MANOJ', 'IT', 70000),
(105, 'ARAVIND', 'FINANCE', 65000);

SELECT * FROM TEMP_EMPLOYEES;                                                         -- 3

DESC TEMP_EMPLOYEES;                                                                   -- 4 

CREATE TEMPORARY TABLE TEMP_HIGH_SALARY AS                                            -- 5
SELECT *                                                                 #TABLE CREATED WITH THOSE SPECIFIC COLUMN,DATA AND CONDITION FROM THE TEMP_EMPLOYEE TABLE
FROM TEMP_EMPLOYEES
WHERE SALARY > 50000;
SELECT * FROM TEMP_HIGH_SALARY;

CREATE TEMPORARY TABLE TEMP_EMPLOYEE_DETAILS AS                                         -- 6
SELECT EMPLOYEEID,EMPLOYEENAME,DEPARTMENT
FROM EMPLOYEES;
SELECT * FROM TEMP_EMPLOYEE_DETAILS;                                      #TABLE CREATED WITH THOSE SPECIFIC COLUMN AND DATA FROM THE TEMP_EMPLOYEE TABLE

UPDATE TEMP_EMPLOYEES                                                                    -- 7
SET SALARY = 75000
WHERE EMPLOYEEID = 101;
SELECT * FROM TEMP_EMPLOYEES
WHERE EMPLOYEEID = 101;

DROP TEMPORARY TABLE TEMP_EMPLOYEES;                                                      -- 8
SELECT * FROM TEMP_EMPLOYEES;                                                           # TABLE DOES NOT EXIST      






CREATE TABLE STUDENT_TEST                                                 --  TRUNCATE
(STUDENTID INT,                                                             #1
STUDENTNAME VARCHAR(50),
MARKS INT);
INSERT INTO STUDENT_TEST (STUDENTID, STUDENTNAME, MARKS)
VALUES
(1, 'ARUN', 85),
(2, 'BALAJI', 78),
(3, 'CHARAN', 92),
(4, 'DINESH', 75),
(5, 'GANESH', 88),
(6, 'HARI', 81),
(7, 'KARTHIK', 95),
(8, 'LOKESH', 72),
(9, 'MANOJ', 89),
(10, 'NAVEEN', 80);
SELECT * FROM STUDENT_TEST;
TRUNCATE TABLE STUDENT_TEST;                                       #ALL RECORDS GOT DELETED

CREATE TABLE STUDENT_DETAILS                                                 #2
(STUDENTID INT,                                                            
STUDENTNAME VARCHAR(50),
AGE INT);
INSERT INTO STUDENT_DETAILS  (STUDENTID, STUDENTNAME, AGE)
VALUES
(1, 'ARUN', 25),
(2, 'BALAJI', 28),
(3, 'CHARAN', 22),
(4, 'DINESH', 25),
(5, 'GANESH', 26),
(6, 'HARI', 21),
(7, 'KARTHIK', 29),
(8, 'LOKESH', 27),
(9, 'MANOJ', 20),
(10, 'NAVEEN', 30);
SELECT * FROM STUDENT_DETAILS;                            #TABLE WITH RECORDS IS DISPLYAED
TRUNCATE TABLE STUDENT_DETAILS;
SELECT * FROM STUDENT_DETAILS;                            #NO RECORDS AVAILABLE



CREATE TABLE STUDENTS                                              #3
(STUDENTID INT,                                                            
STUDENTNAME VARCHAR(50),
AGE INT);
INSERT INTO STUDENTS(STUDENTID, STUDENTNAME, AGE)
VALUES
(1, 'ARUN', 25),
(2, 'BALAJI', 28),
(3, 'CHARAN', 22),
(4, 'DINESH', 25),
(5, 'GANESH', 26),
(6, 'HARI', 21),
(7, 'KARTHIK', 29),
(8, 'LOKESH', 27),
(9, 'MANOJ', 20),
(10, 'NAVEEN', 30);
SELECT * FROM STUDENTS;                            #TABLE WITH RECORDS IS DISPLYAED
DELETE FROM STUDENTS;
SELECT * FROM STUDENTS;                            #NO RECORDS AVAILABLE

INSERT INTO STUDENTS(STUDENTID, STUDENTNAME, AGE)
VALUES
(1, 'ARUN', 25),
(2, 'BALAJI', 28),
(3, 'CHARAN', 22),
(4, 'DINESH', 25),
(5, 'GANESH', 26),
(6, 'HARI', 21),
(7, 'KARTHIK', 29),
(8, 'LOKESH', 27),
(9, 'MANOJ', 20),
(10, 'NAVEEN', 30);
SELECT * FROM STUDENTS;                            #TABLE WITH RECORDS IS DISPLYAED
TRUNCATE TABLE STUDENTS;
SELECT * FROM STUDENTS;                            #NO RECORDS AVAILABLE

INSERT INTO STUDENT_TEST (STUDENTID, STUDENTNAME, MARKS)                   -- 4
VALUES
(11, 'RAHUL', 85),
(12, 'VIGNESH', 90);
SELECT * FROM STUDENT_TEST;
TRUNCATE TABLE STUDENT_TEST;

DESC STUDENT_TEST;                                  #TABLE STRUCTURE IS AVAILABLE

TRUNCATE TABLE EMPLOYEES_DETAILS;                                           -- 5

CREATE TABLE EMPLOYEE_NAME                                                   -- 6
(ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50));

INSERT INTO EMPLOYEE_NAME  (NAME)
VALUES
('ARUN'),
('BALAJI'),
('CHARAN');

SELECT * FROM EMPLOYEE_NAME;                      #NAMES GOT INSERTED WITH EMPLOYEEIDS AUTOMATICALLY STARTING FROM 1
TRUNCATE TABLE EMPLOYEE_NAME;
SELECT * FROM EMPLOYEE_NAME;                       #NO RECORDS

INSERT INTO EMPLOYEE_NAME (NAME)
VALUES('DINESH');
SELECT * FROM EMPLOYEE_NAME;                  #NAME GOT INSERTED WITH EMPLOYEEID STARTING FROM 1


-- 7. DIFFERENCE BETWEEN DELETE, TRUNCATE, AND DROP


-- DELETE: REMOVES ROWS BUT KEEPS THE TABLE STRUCTURE
INSERT INTO EMPLOYEE_NAME (NAME)
VALUES('RUFUS'),('SIMON'),('PAUL'),('LEE'),('JAISON');
DELETE FROM EMPLOYEE_NAME
WHERE ID = 4;
SELECT * FROM EMPLOYEE_NAME;                      -- EMPLOYEE WITH ID = 4 ONLY GOT DELETED

DELETE FROM EMPLOYEE_NAME;
SELECT * FROM EMPLOYEE_NAME;                        -- NO RECORDS AVAILABLE ONLY TABLE IS PRESENT  JUST LIKE TRUNCATE 

INSERT INTO EMPLOYEE_NAME (NAME)
VALUES('RUFUS'),('SIMON'),('PAUL'),('LEE'),('JAISON');            -- -- NO RECORDS AVAILABLE ONLY TABLE IS PRESENT 
TRUNCATE TABLE EMPLOYEE_NAME;
SELECT * FROM EMPLOYEE_NAME; 

-- DROP: REMOVES THE ENTIRE TABLE INCLUDING ITS STRUCTURE
INSERT INTO EMPLOYEE_NAME (NAME)
VALUES('RUFUS'),('SIMON'),('PAUL'),('LEE'),('JAISON'); 
DROP TABLE EMPLOYEE_NAME;
SELECT * FROM EMPLOYEE_NAME;                                   -- SHOWING ERROR EMPLOYEE_NAME DOESN'T EXIST 




-- SEQUENCE

CREATE SEQUENCE EMPLOYEE_SEQ                                      #1              -- SEQUENCE
START WITH 1001;                                                                -- MYSQL IS NOT SUPPORTING SEQUENCE BUT STILL I WROTE MY QUERY WITH THE SYNTAX FROM THE CLASS

SELECT NEXTVAL('EMPLOYEE_SEQ');                                      #2

SELECT NEXTVAL('EMPLOYEE_SEQ');                                 #3
SELECT NEXTVAL('EMPLOYEE_SEQ');
SELECT NEXTVAL('EMPLOYEE_SEQ');
SELECT NEXTVAL('EMPLOYEE_SEQ');
SELECT NEXTVAL('EMPLOYEE_SEQ');

CREATE SEQUENCE EMPLOYEE_SEQ_1                               #4
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE EMPLOYEE_SEQ_2                               #5
START WITH 100
INCREMENT BY 10;

CREATE TABLE EMPLOYEES_SEQ                                #6
(EMPLOYEEID INT DEFAULT NEXTVAL('EMPLOYEE_ID_SEQ'),
EMPLOYEENAME VARCHAR(50),
SALARY DECIMAL(10,2));

#IN MYSQL
CREATE TABLE EMPLOYEES_1 
(EMPLOYEEID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEENAME VARCHAR(100),
SALARY DECIMAL(10,2));
ALTER TABLE EMPLOYEES_1
AUTO_INCREMENT = 1001;
INSERT INTO EMPLOYEES_1 (EMPLOYEENAME, SALARY)
VALUES ('RAJESH', 50000);
SELECT * FROM EMPLOYEES_1;


INSERT INTO EMPLOYEES_SEQ (EMPLOYEENAME, SALARY)                     #7
VALUES
('RAJESH', 60000),
('KUMAR', 55000),
('SURESH', 65000),
('MANOJ', 70000),
('ARAVIND', 62000);


ALTER SEQUENCE EMPLOYEE_ID_SEQ                                        #8
RESTART WITH 5001;
SELECT NEXTVAL('EMPLOYEE_ID_SEQ');

#IN MYSQL
ALTER TABLE EMPLOYEES_1
AUTO_INCREMENT = 5001;




CREATE TABLE STUDENTS                                                              --  COPY
(STUDENTID INT,                                                #NOT SURE ABOUT THE RESULTS REGARDING COPY JUST WROTE QUERY BASED ON THE SYNTAX FROM THE NOTES  
STUDENTNAME VARCHAR(50),
MARKS INT);

COPY STUDENTS                                                                      -- 1
TO '/path/students.csv'
DELIMITER ','
CSV HEADER;

COPY STUDENTS                                                                       -- 2
FROM '/path/students.csv'
DELIMITER ','
CSV HEADER;

COPY (SELECT STUDENTID, STUDENTNAME, MARKS                                         -- 3
FROM STUDENTS)
TO '/path/students_selected.csv'
DELIMITER ','
CSV HEADER;

COPY EMPLOYEES                                                                     -- 4
FROM '/path/employees.csv'
DELIMITER ','
CSV HEADER;

COPY (SELECT * FROM EMPLOYEES                                                        -- 5
WHERE SALARY > 50000)
TO '/path/high_salary_employees.csv'
DELIMITER ','
#CSV HEADER;






CREATE TEMPORARY TABLE TEMP_DEPARTMENT_SALARY AS                 -- 1                            -- CHALLENGE QUESTIONS
SELECT DEPARTMENT,ROUND(AVG(SALARY)) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT;
SELECT * FROM TEMP_DEPARTMENT_SALARY;

CREATE SEQUENCE EMPLOYEE_ID_SEQ                                                     -- 2
START WITH 1001
INCREMENT BY 1;
CREATE TABLE SEQUENCE_EMPLOYEES 
(EMPLOYEEID INT DEFAULT NEXTVAL('EMPLOYEE_ID_SEQ'),
EMPLOYEENAME VARCHAR(50),SALARY DECIMAL(10,2));

SHOW TABLES LIKE 'TEMP_DEPARTMENT_SALARY';
CREATE TABLE DETAILS_EMPLOYEES 
(EMPLOYEEID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEENAME VARCHAR(50),SALARY DECIMAL(10,2));

INSERT INTO DETAILS_EMPLOYEES(EMPLOYEENAME, SALARY)
VALUES
('RAJESH', 60000),
('KUMAR', 55000),
('SURESH', 65000),
('MANOJ', 70000),
('ARAVIND', 62000),
('VIJAY', 58000),
('KARTHIK', 72000),
('NAVEEN', 50000),
('PRAVEEN', 68000),
('SANJAY', 61000);
SELECT * FROM DETAILS_EMPLOYEES;

CREATE TABLE CSV_EMPLOYEES                                                  -- 3
(EMPLOYEEID INT,
EMPLOYEENAME VARCHAR(50),
DEPARTMENTID INT,
SALARY DECIMAL(10,2));

COPY CSV_EMPLOYEES
FROM '/path/employees.csv'
WITH (FORMAT CSV, HEADER);

SELECT * FROM CSV_EMPLOYEES;

TRUNCATE TABLE CSV_EMPLOYEES;
SELECT * FROM CSV_EMPLOYEES;


CREATE TEMPORARY TABLE TEMP_EMPLOYEES                                  -- 4
(EMPLOYEEID INT AUTO_INCREMENT('TEMP_EMPLOYEE_SEQ'),
EMPLOYEENAME VARCHAR(50),
SALARY DECIMAL(10,2));
ALTER TABLE TEMP_EMPLOYEES 
AUTO_INCREMENT = 2001;

INSERT INTO TEMP_EMPLOYEES (EMPLOYEENAME, SALARY)
VALUES
('ARUN', 50000),
('BALAJI', 55000),
('CHARAN', 60000),
('DINESH', 65000),
('GANESH', 70000);
SELECT * FROM TEMP_EMPLOYEES;

UPDATE TEMP_EMPLOYEES
SET SALARY = SALARY + 5000
WHERE EMPLOYEEID IN (2001, 2002);
SELECT * FROM TEMP_EMPLOYEES;

TRUNCATE TABLE TEMP_EMPLOYEES;
SELECT * FROM TEMP_EMPLOYEES;



CREATE TABLE WORKFLOW_EMPLOYEES                                   -- 5
(EMPLOYEEID INT,
EMPLOYEENAME VARCHAR(50),
DEPARTMENTID INT,
SALARY DECIMAL(10,2));

COPY CSV_EMPLOYEES
FROM '/path/CSV_employees.csv'
WITH (FORMAT CSV, HEADER);
SELECT * FROM CSV_EMPLOYEES;

CREATE TEMPORARY TABLE TEMP_CSV_EMPLOYEES AS
SELECT * FROM CSV_EMPLOYEES;

SELECT * FROM TEMP_CSV_EMPLOYEES;

UPDATE TEMP_CSV_EMPLOYEES
SET SALARY = SALARY + 5000
WHERE SALARY < 60000;

SELECT * FROM TEMP_CSV_EMPLOYEES;
TRUNCATE TABLE TEMP_CSV_EMPLOYEES;

SELECT * FROM TEMP_CSV_EMPLOYEES;
SELECT * FROM CSV_EMPLOYEES;