
-- A. BEFORE INSERT TRIGGERS

-- 1
DELIMITER //

CREATE TRIGGER INSERT_CREATEDDATE
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
SET NEW.CREATEDDATE = CURDATE();
END //

DELIMITER ;

-- 2
DELIMITER //

CREATE TRIGGER SALARY_LIMIT
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
IF NEW.SALARY<10000 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'SALARY CANNOT BE LESS THAN 10000';
END IF;
END //

DELIMITER ;

-- 3
DELIMITER //

CREATE TRIGGER EMPLOYEENAME_UPPERCASE
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
SET NEW.EMPLOYEENAME = UPPER(NEW.EMPLOYEENAME);
END //

DELIMITER ;

-- 4
DELIMITER //

CREATE TRIGGER EMPLOYEE_DEPARTMENT_CONDITION
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
IF NEW.DEPARTMENT IS NULL THEN
SET NEW.DEPARTMENT = 'GENERAL';
END IF;
END //

DELIMITER ;

-- 5
DELIMITER //

CREATE TRIGGER PRODUCT_PRICE_LIMIT
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
IF NEW.PRICE<0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'PRICE CANNOT BE NEGATIVE';
END IF;
END //

DELIMITER ;



-- B. AFTER INSERT TRIGGERS

-- 1
CREATE TABLE EMPLOYEE_AUDIT                                         
(AUDITID INT AUTO_INCREMENT PRIMARY KEY,EMPLOYEEID INT,
EMPLOYEENAME VARCHAR(50),DEPARTMENT VARCHAR(50),
SALARY DECIMAL(10,2),INSERTED_AT DATETIME);

DELIMITER //

CREATE TRIGGER EMPLOYEE_INSERT_AUDIT
AFTER INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_AUDIT
(EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY,
INSERTED_AT)
VALUES(NEW.EMPLOYEEID,NEW.EMPLOYEENAME,
NEW.DEPARTMENT,NEW.SALARY,NOW());
END //

DELIMITER ;

-- 2
CREATE TABLE EMPLOYEE_INSERT_LOG 
(LOGID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEEID INT,INSERTION_TIME DATETIME);

DELIMITER //

CREATE TRIGGER EMPLOYEE_INSERT_LOG
AFTER INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_INSERT_LOG
(EMPLOYEEID,INSERTION_TIME)
VALUES(NEW.EMPLOYEEID,NOW());
END //

DELIMITER ;

-- 3.
CREATE TABLE ORDER_AUDIT 
(AUDITID INT AUTO_INCREMENT PRIMARY KEY,ORDERID INT,
CUSTOMERID INT,ORDERAMOUNT DECIMAL(10,2),
ORDERDATE DATE,CREATED_AT DATETIME);

DELIMITER //

CREATE TRIGGER ORDER_INSERT_AUDIT
AFTER INSERT ON ORDERS
FOR EACH ROW
BEGIN
INSERT INTO ORDER_AUDIT
(ORDERID,CUSTOMERID,ORDERAMOUNT,
ORDERDATE,CREATED_AT)
VALUES(NEW.ORDERID,NEW.CUSTOMERID,
NEW.ORDERAMOUNT,
NEW.ORDERDATE,NOW());
END //

DELIMITER ;


-- 4. 
DELIMITER //

CREATE TRIGGER EMPLOYEE_INSERT_COUNT
AFTER INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
UPDATE DEPARTMENTS
SET EMPLOYEECOUNT = EMPLOYEECOUNT + 1
WHERE DEPARTMENTID = NEW.DEPARTMENTID;
END //

DELIMITER ;

-- 5
INSERT INTO EMPLOYEE
(EMPLOYEEID,EMPLOYEENAME,
DEPARTMENT,SALARY)
VALUES(101, 'ARUN', 'IT', 50000),
(102, 'BALAJI', 'HR', 55000),(103, 'CHARAN', 'SALES', 60000);

SELECT * FROM EMPLOYEE_AUDIT;                                  
SELECT * FROM EMPLOYEE_INSERT_LOG;
SELECT * FROM DEPARTMENTS;



-- C. BEFORE UPDATE TRIGGERS

-- 1
DELIMITER //

CREATE TRIGGER EMPLOYEE_UPDATE_SALARY_REDUCTION
BEFORE UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF NEW.SALARY < OLD.SALARY THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'SALARY CANNOT BE REDUCED';
END IF;
END //

DELIMITER ;

-- 2. 
DELIMITER //

CREATE TRIGGER EMPLOYEE_UPDATE_MIN_SALARY
BEFORE UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF NEW.SALARY < 15000 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'SALARY CANNOT BE BELOW 15000';
END IF;
END //

DELIMITER ;

-- 3
DELIMITER //

CREATE TRIGGER EMPLOYEE_UPDATE_MODIFIEDDATE
BEFORE UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
SET NEW.MODIFIEDDATE = NOW();
END //

DELIMITER ;


-- 4
DELIMITER //

CREATE TRIGGER EMPLOYEE_UPDATE_UPPERCASE
BEFORE UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
SET NEW.EMPLOYEENAME = UPPER(NEW.EMPLOYEENAME);
END //

DELIMITER ;


-- 5
DELIMITER //

CREATE TRIGGER BEFORE_EMPLOYEE_UPDATE_EMPLOYEEID
BEFORE UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF NEW.EMPLOYEEID <> OLD.EMPLOYEEID THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'EMPLOYEEID CANNOT BE CHANGED';
END IF;
END //

DELIMITER ;




-- D AFTER UPDATE

-- 1
CREATE TABLE EMPLOYEE_SALARY_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_ID INT,OLD_SALARY DECIMAL(10,2),
NEW_SALARY DECIMAL(10,2),CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_SALARY_UPDATE
AFTER UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF OLD.SALARY <> NEW.SALARY THEN
INSERT INTO EMPLOYEE_SALARY_AUDIT
(EMPLOYEE_ID, OLD_SALARY, NEW_SALARY)
VALUES
(OLD.EMPLOYEEID, OLD.SALARY, NEW.SALARY);
END IF;
END //

DELIMITER ;

-- 2
CREATE TABLE EMPLOYEE_DEPARTMENT_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_ID INT,OLD_DEPARTMENT_ID INT,
NEW_DEPARTMENT_ID INT,CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_DEPARTMENT_UPDATE
AFTER UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF OLD.DEPARTMENTID <> NEW.DEPARTMENTID THEN
INSERT INTO EMPLOYEE_DEPARTMENT_AUDIT
(EMPLOYEE_ID, OLD_DEPARTMENT_ID, NEW_DEPARTMENT_ID)
VALUES(OLD.EMPLOYEEID, OLD.DEPARTMENTID, NEW.DEPARTMENTID);
END IF;
END //

DELIMITER ;

-- 3
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_SALARY_UPDATE
AFTER UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF OLD.SALARY <> NEW.SALARY THEN
INSERT INTO EMPLOYEE_SALARY_AUDIT
(EMPLOYEE_ID, OLD_SALARY, NEW_SALARY)
VALUES
(OLD.EMPLOYEEID, OLD.SALARY, NEW.SALARY);
END IF;
END //

DELIMITER ;

-- 4.
UPDATE EMPLOYEES
SET SALARY = SALARY + 5000
WHERE EMPLOYEEID IN (101, 102, 103);

SELECT * FROM EMPLOYEE_SALARY_AUDIT;


-- 5
CREATE TABLE EMPLOYEE_DESIGNATION_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_ID INT,OLD_DESIGNATION VARCHAR(30),
NEW_DESIGNATION VARCHAR(30),
CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DELIMITER //

CREATE TRIGGER AFTER_DESIGNATION_UPDATE
AFTER UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF OLD.DESIGNATION <> NEW.DESIGNATION THEN
INSERT INTO EMPLOYEE_DESIGNATION_AUDIT
(EMPLOYEE_ID, OLD_DESIGNATION, NEW_DESIGNATION)
VALUES(OLD.EMPLOYEEID, OLD.DESIGNATION, NEW.DESIGNATION);
END IF;
END //

DELIMITER ;



-- E BEFORE DELETE

-- 1
DELIMITER //

CREATE TRIGGER BEFORE_EMPLOYEE_DELETE_MANAGER
BEFORE DELETE ON EMPLOYEE
FOR EACH ROW
BEGIN
IF OLD.DESIGNATION = 'MANAGER' THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'CANNOT DELETE AN EMPLOYEE WITH DESIGNATION MANAGER';
END IF;
END //

DELIMITER ;


-- 2
DELIMITER //

CREATE TRIGGER BEFORE_HIGH_SALARY_DELETE
BEFORE DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
IF OLD.SALARY > 100000 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'CANNOT DELETE AN EMPLOYEE WHOSE SALARY IS GREATER THAN 100000';
END IF;
END //

DELIMITER ;


-- 3
DELIMITER //

CREATE TRIGGER BEFORE_EMPLOYEE_PROJECT_DELETE
BEFORE DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
IF OLD.ACTIVEPROJECT = 'YES' THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'CANNOT DELETE EMPLOYEE ASSOCIATED WITH AN ACTIVE PROJECT';
END IF;
END //

DELIMITER ;


-- 4
DELIMITER //

CREATE TRIGGER BEFORE_PRODUCT_DELETE
BEFORE DELETE ON PRODUCTS
FOR EACH ROW
BEGIN
IF OLD.STOCK > 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'CANNOT DELETE A PRODUCT THAT STILL HAS STOCK';
END IF;
END //

DELIMITER ;


-- 5
DELIMITER //

CREATE TRIGGER BEFORE_CUSTOMER_DELETE
BEFORE DELETE ON CUSTOMERS
FOR EACH ROW
BEGIN
IF OLD.EXISTINGORDERS >0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'CANNOT DELETE CUSTOMER WHO HAS EXISTING ORDERS';
END IF;
END //

DELIMITER ;




-- F AFTER DELETE

-- 1
CREATE TABLE EMPLOYEE_DELETE_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_ID INT,EMPLOYEE_NAME VARCHAR(30),
DEPARTMENT_ID INT,SALARY DECIMAL(10,2),
DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_DELETE
AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_DELETE_AUDIT
(EMPLOYEE_ID,EMPLOYEE_NAME,
DEPARTMENT_ID,SALARY)
VALUES(OLD.EMPLOYEEID,OLD.EMPLOYEENAME,
OLD.DEPARTMENTID,OLD.SALARY);
END //

DELIMITER ;

-- 2
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_DELETE
AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_DELETE_AUDIT
(EMPLOYEE_ID,EMPLOYEE_NAME,
DEPARTMENT_ID,SALARY)
VALUES(OLD.EMPLOYEEID,OLD.EMPLOYEENAME,
OLD.DEPARTMENTID,OLD.SALARY);
END //

DELIMITER ;

-- 3
DELETE FROM EMPLOYEES
WHERE EMPLOYEEID IN (101, 102, 103);

SELECT * FROM EMPLOYEE_DELETE_AUDIT;


-- 4
CREATE TABLE ORDER_DELETE_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
ORDER_ID INT,CUSTOMER_ID INT,
ORDER_DATE DATE,DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DELIMITER //

CREATE TRIGGER AFTER_ORDER_DELETE
AFTER DELETE ON ORDERS
FOR EACH ROW
BEGIN
INSERT INTO ORDER_DELETE_AUDIT
(ORDER_ID,CUSTOMER_ID,ORDER_DATE)
VALUES(OLD.ORDERID,OLD.CUSTOMERID,OLD.ORDERDATE);
END //

DELIMITER ;


-- 5
CREATE TABLE EMPLOYEE_CHANGE_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
EMPLOYEE_ID INT,ACTION_TYPE VARCHAR(20),
OLD_NAME VARCHAR(30),NEW_NAME VARCHAR(30),
OLD_SALARY DECIMAL(10,2),NEW_SALARY DECIMAL(10,2),
CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- AFTER INSERT TRIGGER
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_INSERT_AUDIT
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_CHANGE_AUDIT
(EMPLOYEE_ID,ACTION_TYPE,
NEW_NAME,NEW_SALARY)
VALUES(NEW.EMPLOYEEID,'INSERT',
NEW.EMPLOYEENAME,NEW.SALARY);
END //

DELIMITER ;

-- AFTER UPDATE TRIGGER
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_UPDATE_AUDIT
AFTER UPDATE ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_CHANGE_AUDIT
(EMPLOYEE_ID,ACTION_TYPE,
OLD_NAME,NEW_NAME,
OLD_SALARY,NEW_SALARY)
VALUES(NEW.EMPLOYEEID,'UPDATE',
OLD.EMPLOYEENAME,NEW.EMPLOYEENAME,
OLD.SALARY,NEW.SALARY);
END //

DELIMITER ;

-- AFTER DELETE TRIGGER
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_DELETE_AUDIT
AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_CHANGE_AUDIT
(EMPLOYEE_ID,ACTION_TYPE,
OLD_NAME,OLD_SALARY)
VALUES(OLD.EMPLOYEEID,'DELETE',
OLD.EMPLOYEENAME,OLD.SALARY);
END //

DELIMITER ;




-- CHALLENGE QUESTIONS



-- 1
CREATE TABLE PRODUCTS 
(PRODUCTID INT PRIMARY KEY,PRODUCTNAME VARCHAR(30),
PRICE DECIMAL(10,2),CREATEDDATE DATE);

DELIMITER //

CREATE TRIGGER BEFORE_PRODUCT_INSERT
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
IF NEW.PRICE < 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'PRICE CANNOT BE NEGATIVE';
END IF;
END //

DELIMITER ;

INSERT INTO PRODUCTS
VALUES (1, 'LAPTOP', 50000, CURDATE()), (2, 'MOBILE', -10000, CURDATE());

-- 2
DELIMITER //

CREATE TRIGGER BEFORE_PRODUCT_PRICE_UPDATE
BEFORE UPDATE ON PRODUCTS
FOR EACH ROW
BEGIN
IF NEW.PRICE < OLD.PRICE * 0.80 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'PRICE CANNOT BE REDUCED BY MORE THAN 20%';
END IF;
END //

DELIMITER ;

-- 3
CREATE TABLE PRODUCT_PRICE_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(30),OLD_PRICE DECIMAL(10,2),NEW_PRICE DECIMAL(10,2),
CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELIMITER //

CREATE TRIGGER AFTER_PRODUCT_PRICE_UPDATE
AFTER UPDATE ON PRODUCTS
FOR EACH ROW
BEGIN
IF OLD.PRICE <> NEW.PRICE THEN
INSERT INTO PRODUCT_PRICE_AUDIT
(PRODUCT_ID,PRODUCT_NAME,OLD_PRICE,NEW_PRICE)
VALUES(OLD.PRODUCTID,OLD.PRODUCT_NAME,OLD.PRICE,NEW.PRICE);
END IF;
END //

DELIMITER ;

SELECT * FROM PRODUCT_PRICE_AUDIT;

-- 4
ALTER TABLE PRODUCTS
ADD STOCK INT DEFAULT 0;

DELIMITER //

CREATE TRIGGER BEFORE_PRODUCT_DELETE_STOCK
BEFORE DELETE ON PRODUCTS
FOR EACH ROW
BEGIN
IF OLD.STOCK > 0 THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'CANNOT DELETE PRODUCT WITH STOCK QUANTITY GREATER THAN 0';
END IF;
END //

DELIMITER ;

-- 5
CREATE TABLE EMPLOYEE_COMPLETE_AUDIT 
(AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,EMPLOYEE_ID INT,
ACTION_TYPE VARCHAR(20),
OLD_EMPLOYEE_NAME VARCHAR(30),NEW_EMPLOYEE_NAME VARCHAR(30),
OLD_DEPARTMENT_ID INT,NEW_DEPARTMENT_ID INT,
OLD_DESIGNATION VARCHAR(30),NEW_DESIGNATION VARCHAR(30),
OLD_SALARY DECIMAL(10,2),NEW_SALARY DECIMAL(10,2),
CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- AFTER INSERT
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_INSERT_COMPLETE
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_COMPLETE_AUDIT
(EMPLOYEE_ID,ACTION_TYPE,
NEW_EMPLOYEE_NAME,NEW_DEPARTMENT_ID,
NEW_DESIGNATION,NEW_SALARY)
VALUES(NEW.EMPLOYEEID,'INSERT',
NEW.EMPLOYEENAME,NEW.DEPARTMENTID,
NEW.DESIGNATION,NEW.SALARY);
END //

DELIMITER ;


-- AFTER UPDATE
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_UPDATE_COMPLETE
AFTER UPDATE ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_COMPLETE_AUDIT
(EMPLOYEE_ID,ACTION_TYPE,
OLD_EMPLOYEE_NAME,NEW_EMPLOYEE_NAME,
OLD_DEPARTMENT_ID,NEW_DEPARTMENT_ID,
OLD_DESIGNATION,NEW_DESIGNATION,
OLD_SALARY,NEW_SALARY)
VALUES(NEW.EMPLOYEEID,'UPDATE',
OLD.EMPLOYEENAME,NEW.EMPLOYEENAME,
OLD.DEPARTMENTID,NEW.DEPARTMENTID,
OLD.DESIGNATION,NEW.DESIGNATION,
OLD.SALARY,NEW.SALARY);
END //

DELIMITER ;


-- AFTER DELETE
DELIMITER //

CREATE TRIGGER AFTER_EMPLOYEE_DELETE_COMPLETE
AFTER DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
INSERT INTO EMPLOYEE_COMPLETE_AUDIT
(EMPLOYEE_ID,ACTION_TYPE,
OLD_EMPLOYEE_NAME,OLD_DEPARTMENT_ID,
OLD_DESIGNATION,OLD_SALARY)
VALUES(OLD.EMPLOYEEID,'DELETE',
OLD.EMPLOYEENAME,OLD.DEPARTMENTID,
OLD.DESIGNATION,OLD.SALARY);
END //

DELIMITER ;













