DELIMITER //
CREATE FUNCTION ADD_NUMBERS(A INT, B INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN A+B;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION SUBTRACT_NUMBERS(A INT, B INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN A-B;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION SQUARE_NUMBER(A INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN A*A;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CUBE_NUMBER(A INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN A*A*A;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION GREATER_NUMBER(A INT, B INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN GREATEST(A,B);
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CHECK_EVEN_ODD(A INT)
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
IF MOD(A,2)=0 THEN
RETURN 'EVEN';
ELSE
RETURN 'ODD';
END IF;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION ANNUAL_SALARY(SALARY DECIMAL(10,2))
RETURNS DECIMAL(12,2)
DETERMINISTIC
BEGIN
RETURN SALARY*12;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CALCULATE_AGE(DOB DATE)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN YEAR(CURDATE()) - YEAR(DOB);
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION TO_UPPERCASE(EMPLOYEENAME VARCHAR(50))
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
RETURN UPPER(EMPLOYEENAME);
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION STRING_LENGTH(EMPLOYEENAME VARCHAR(50))
RETURNS INT
DETERMINISTIC
BEGIN
RETURN LENGTH(EMPLOYEENAME);
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CALCULATE_DISCOUNT(PURCHASE_AMOUNT DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
IF PURCHASE_AMOUNT>=10000 THEN
RETURN PURCHASE_AMOUNT*0.20;
ELSEIF PURCHASE_AMOUNT>=5000 THEN
RETURN PURCHASE_AMOUNT*0.10;
ELSE
RETURN PURCHASE_AMOUNT*0.05;
END IF;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION PASS_FAIL(MARKS INT)
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
IF MARKS>=50 THEN
RETURN 'PASS';
ELSE
RETURN 'FAIL';
END IF;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION TOTAL_PRICE(QUANTITY INT, PRICE DECIMAL(10,2))
RETURNS DECIMAL(12,2)
DETERMINISTIC
BEGIN
RETURN QUANTITY*PRICE;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CALCULATE_GST(AMOUNT DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
RETURN AMOUNT*0.18;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION EMPLOYEE_EXPERIENCE(JOINING_DATE DATE)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN YEAR(CURDATE()) - YEAR(JOINING_DATE);
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CHECK_ELIGIBILITY(AGE INT)
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
IF AGE>=18 THEN
RETURN 'ELIGIBLE';
ELSE
RETURN 'NOT ELIGIBLE';
END IF;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CALCULATE_BMI(WEIGHT DECIMAL(10,2),
HEIGHT DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
RETURN WEIGHT/(HEIGHT*HEIGHT);
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION LAST_FOUR_CHARACTERS(EMPLOYEENAME VARCHAR(255))
RETURNS VARCHAR(4)
DETERMINISTIC
BEGIN
RETURN RIGHT(EMPLOYEENAME,4);
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CALCULATE_COMMISSION(SALES_AMOUNT DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
IF SALES_AMOUNT>=100000 THEN
RETURN SALES_AMOUNT*0.10;
ELSEIF SALES_AMOUNT>=50000 THEN
RETURN SALES_AMOUNT*0.05;
ELSE
RETURN SALES_AMOUNT*0.02;
END IF;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION CALCULATE_GRADE(MARKS INT)
RETURNS CHAR(1)
DETERMINISTIC
BEGIN
RETURN CASE
WHEN MARKS>=90 THEN 'A'
WHEN MARKS>=75 THEN 'B'
WHEN MARKS>=50 THEN 'C'
ELSE 'F'
END;
END //
DELIMITER ;