-- BANKING 

-- 1
CREATE VIEW CUSTOMER_DETAILS AS
SELECT CUSTOMERNAME,
ACCOUNTNUMBER,ACCOUNTTYPE,BALANCE
FROM CUSTOMERS;


-- 2
CREATE VIEW HIGH_BALANCE_CUSTOMERS AS
SELECT CUSTOMERNAME,
ACCOUNTNUMBER,ACCOUNTTYPE,BALANCE
FROM CUSTOMERS 
WHERE BALANCE > 50000;


-- 3
CREATE VIEW ACTIVE_ACCOUNTS AS
SELECT ACCOUNTID,ACCOUNTNUMBER,
CUSTOMERID,CUSTOMERNAME,ACCOUNTTYPE,
BALANCE,ACCOUNTSTATUS
FROM ACCOUNTS
WHERE ACCOUNTSTATUS = 'ACTIVE';


-- 4
CREATE VIEW CUSTOMER_TRANSACTIONS AS                           -- ASSUMED A SEPERATE TABLE FOR TRANSACTIONS
SELECT C.CUSTOMERNAME,C.CUSTOMERID,
       T.TRANSACTIONTYPE,
       T.AMOUNT,
       T.TRANSACTIONDATE
FROM CUSTOMERS C
LEFT JOIN TRANSACTIONS T
ON C.CUSTOMERID = T.CUSTOMERID;


-- 5
CREATE VIEW CURRENT_MONTH_TRANSACTIONS AS
SELECT DISTINCT C.CUSTOMERID,
       C.CUSTOMERNAME,C.ACCOUNTNUMBER
FROM CUSTOMERS C
INNER JOIN TRANSACTIONS T
ON C.CUSTOMERID = T.CUSTOMERID
WHERE MONTH(T.TRANSACTIONDATE) = MONTH(CURDATE())
AND YEAR(T.TRANSACTIONDATE) = YEAR(CURDATE());





-- E-COMMERCE 

-- 1
CREATE VIEW PRODUCT_STOCK AS
SELECT PRODUCTNAME,CATEGORY,
PRICE,STOCK
FROM PRODUCTS;


-- 2
CREATE VIEW LOW_STOCK_PRODUCTS AS
SELECT PRODUCTID,
PRODUCTNAME,CATEGORY,
STOCK,REORDERLEVEL
FROM PRODUCTS
WHERE STOCK < REORDERLEVEL;


-- 3
CREATE VIEW CUSTOMER_ORDERS AS
SELECT C.CUSTOMERNAME,
O.ORDERID,O.ORDERDATE,O.ORDERAMOUNT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;


-- 4
CREATE VIEW PENDING_ORDERS AS
SELECT ORDERID,CUSTOMERID,
ORDERDATE,ORDERAMOUNT,ORDERSTATUS
FROM ORDERS
WHERE ORDERSTATUS = 'PENDING';


-- 5. DISPLAY ORDER DETAILS ALONG WITH CUSTOMER
-- AND PRODUCT INFORMATION USING JOINS

CREATE VIEW CUSTOMER_ORDER_DETAILS AS
SELECT O.ORDERID,O.ORDERDATE,
C.CUSTOMERNAME,P.PRODUCTNAME,
O.QUANTITY,O.UNITPRICE,
O.QUANTITY*O.UNITPRICE AS TOTALAMOUNT
FROM ORDERS O
INNER JOIN CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;


-- 6
CREATE VIEW CUSTOMER_TOTAL_SPENT AS
SELECT C.CUSTOMERID,C.CUSTOMERNAME,
SUM(O.ORDERAMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERID, C.CUSTOMERNAME;


-- 7. SHOW CATEGORY-WISE TOTAL SALES

CREATE VIEW CATEGORY_TOTAL_SALES AS
SELECT P.CATEGORY,
SUM(O.QUANTITY*O.UNITPRICE) AS TOTAL_SALES
FROM PRODUCTS P
INNER JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.CATEGORY;


-- 8. DISPLAY TOP-SELLING PRODUCTS
-- BASED ON QUANTITY SOLD

CREATE VIEW TOP_SELLING_PRODUCTS AS
SELECT P.PRODUCTID,P.PRODUCTNAME,
SUM(O.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PRODUCTS P
INNER JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.PRODUCTID, P.PRODUCTNAME
ORDER BY TOTAL_QUANTITY_SOLD DESC;







-- EMPLOYEE / HR 



-- 1
CREATE VIEW EMPLOYEE_DETAILS AS
SELECT E.EMPLOYEENAME,D.DEPARTMENTNAME,
E.DESIGNATION,E.SALARY
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;


-- 2
CREATE VIEW HIGH_SALARY_EMPLOYEES AS
SELECT EMPLOYEEID,EMPLOYEENAME,SALARY
FROM EMPLOYEES
WHERE SALARY > 750000;


-- 3
CREATE VIEW IT_EMPLOYEES AS
SELECT E.EMPLOYEEID,E.EMPLOYEENAME,
D.DEPARTMENTNAME,E.DESIGNATION,E.SALARY
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'IT';


-- 4
CREATE VIEW DEPARTMENT_EMPLOYEE_COUNT AS
SELECT D.DEPARTMENTID,D.DEPARTMENTNAME,
COUNT(E.EMPLOYEEID) AS EMPLOYEE_COUNT
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTID, D.DEPARTMENTNAME;


-- 5
CREATE VIEW DEPARTMENT_AVERAGE_SALARY AS
SELECT D.DEPARTMENTID,D.DEPARTMENTNAME,
ROUND(AVG(E.SALARY)) AS AVERAGE_SALARY
FROM DEPARTMENTS D
INNER JOIN EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTID, D.DEPARTMENTNAME;


-- 6
CREATE VIEW EMPLOYEE_MANAGER AS
SELECT E.EMPLOYEENAME AS EMPLOYEE_NAME,
M.EMPLOYEENAME AS MANAGER_NAME
FROM EMPLOYEES E
LEFT JOIN EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;


-- 7
CREATE VIEW RECENT_EMPLOYEES AS
SELECT EMPLOYEEID,EMPLOYEENAME,JOININGDATE
FROM EMPLOYEES
WHERE JOININGDATE >= DATE_SUB(CURDATE(), INTERVAL 1 YEAR);



-- STUDENT MANAGEMENT 

-- 1

CREATE VIEW STUDENT_MARKS AS
SELECT S.STUDENTID,S.STUDENTNAME,
S.COURSENAME,SUM(M.MARKS) AS TOTAL_MARKS,
ROUND(AVG(M.MARKS)) AS AVERAGE_MARKS
FROM STUDENTS S
INNER JOIN MARKS M
ON S.STUDENTID = M.STUDENTID
GROUP BY S.STUDENTID,S.STUDENTNAME;


-- 2. SHOW STUDENTS WHO HAVE PASSED
-- ALL SUBJECTS

CREATE VIEW PASS_STUDENTS AS
SELECT S.STUDENTID,S.STUDENTNAME,M.RESULT
FROM STUDENTS S
INNER JOIN MARKS M
ON S.STUDENTID = M.STUDENTID
GROUP BY S.STUDENTID, S.STUDENTNAME
HAVING RESULT='PASSED';


-- 3
CREATE VIEW HIGH_AVERAGE_STUDENTS AS
SELECT S.STUDENTID,S.STUDENTNAME,
ROUND(AVG(M.MARKS)) AS AVERAGE_MARKS
FROM STUDENTS S
INNER JOIN MARKS M
ON S.STUDENTID = M.STUDENTID
GROUP BY S.STUDENTID, S.STUDENTNAME
HAVING ROUND(AVG(M.MARKS))>80;


-- 4
CREATE VIEW COURSE_STUDENT_COUNT AS
SELECT C.COURSEID,C.COURSENAME,
COUNT(SC.STUDENTID) AS STUDENT_COUNT
FROM COURSES C
LEFT JOIN STUDENT_COURSE SC
ON C.COURSEID = SC.COURSEID
GROUP BY C.COURSEID, C.COURSENAME;


-- 5
CREATE VIEW COURSE_AVERAGE_MARKS AS
SELECT C.COURSEID,C.COURSENAME,
ROUND(AVG(M.MARKS)) AS AVERAGE_MARKS
FROM COURSES C
INNER JOIN STUDENT_COURSE SC
ON C.COURSEID = SC.COURSEID
INNER JOIN MARKS M
ON SC.STUDENTID = M.STUDENTID
GROUP BY C.COURSEID, C.COURSENAME;


-- 6. CALCULATE THE STUDENT'S GRADE USING CASE

CREATE VIEW STUDENT_GRADES AS
SELECT S.STUDENTID,S.STUDENTNAME,
ROUND(AVG(M.MARKS)) AS AVERAGE_MARKS,
CASE WHEN AVG(M.MARKS) >= 90 THEN 'A'
WHEN AVG(M.MARKS)>=75 THEN 'B'
WHEN AVG(M.MARKS)>=50 THEN 'C'
ELSE 'F'
END AS GRADE
FROM STUDENTS S
INNER JOIN MARKS M
ON S.STUDENTID = M.STUDENTID
GROUP BY S.STUDENTID, S.STUDENTNAME;






-- HOSPITAL 



-- 1. DISPLAY PATIENT NAME, DOCTOR NAME,
-- APPOINTMENT DATE, AND APPOINTMENT STATUS

CREATE VIEW PATIENT_APPOINTMENTS AS
SELECT PATIENTNAME,DOCTORNAME,
APPOINTMENTDATE,APPOINTMENTSTATUS
FROM PATIENTS;


-- 2. SHOW ALL CURRENTLY ADMITTED PATIENTS

CREATE VIEW CURRENTLY_ADMITTED_PATIENTS AS
SELECT PATIENTID,PATIENTNAME,
ADMISSIONDATE,PATIENTSTATUS
FROM PATIENTS
WHERE PATIENTSTATUS = 'ADMITTED';


-- 3
CREATE VIEW PATIENT_BILL_DETAILS AS
SELECT PATIENTNAME,ADMISSIONDATE,
DISCHARGEDATE,TOTALBILL
FROM PATIENTS;


-- 4
CREATE VIEW DOCTOR_PATIENT_COUNT AS
SELECT DOCTORID,DOCTORNAME,
COUNT(PATIENTID) AS PATIENT_COUNT
FROM DOCTORS
GROUP BY DOCTORID,DOCTORNAME;


-- 5
CREATE VIEW HIGH_BILL_PATIENTS AS
SELECT P.PATIENTID,P.PATIENTNAME,A.TOTALBILL
FROM PATIENTS P
INNER JOIN ADMISSIONS A
ON P.PATIENTID = A.PATIENTID
WHERE A.TOTALBIL>10000;





-- ADVANCED VIEW SCENARIOS

CREATE VIEW CUSTOMER_ORDER_REPORT AS
SELECT C.CUSTOMERID,C.CUSTOMERNAME,
O.ORDERID,O.ORDERDATE,P.PRODUCTID,
P.PRODUCTNAME,O.QUANTITY,O.UNITPRICE,
O.QUANTITY * O.UNITPRICE AS TOTAL_AMOUNT
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;


-- 2. DISPLAY MONTHLY SALES SUMMARY WITH MONTH,
-- NUMBER OF ORDERS, QUANTITY SOLD, AND TOTAL REVENUE

CREATE VIEW MONTHLY_SALES_SUMMARY AS
SELECT P.PRODUCTNAME,DATE_FORMAT(O.ORDERDATE, '%Y-%M') AS SALES_MONTH,
COUNT(DISTINCT O.ORDERID) AS TOTAL_ORDERS,
SUM(OI.QUANTITY) AS QUANTITY_SOLD,
SUM(OI.QUANTITY * OI.UNITPRICE) AS TOTAL_REVENUE
FROM ORDERS O
INNER JOIN ORDER_ITEMS OI
ON O.ORDERID = OI.ORDERID
INNER JOIN PRODUCTS P
ON P.PRODUCTID=OI.PRODUCTID
GROUP BY P.PRODUCTNAME,DATE_FORMAT(O.ORDERDATE, '%Y-%M');


-- 3
CREATE VIEW CUSTOMERS_WITHOUT_ORDERS AS
SELECT C.CUSTOMERID,C.CUSTOMERNAME
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE O.ORDERID IS NULL;


-- 4.
CREATE VIEW UNSOLD_PRODUCTS AS
SELECT P.PRODUCTID,P.PRODUCTNAME,P.PRICE
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCTID = O.PRODUCTID
WHERE O.PRODUCTID IS NULL;


-- 5
CREATE VIEW HIGHEST_PAID_EMPLOYEE AS
SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENTID,SALARY
FROM EMPLOYEES 
WHERE SALARY IN(SELECT MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENTID);


-- 6
CREATE VIEW SECOND_HIGHEST_SALARY AS
SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENTID,SALARY
FROM(SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENTID,SALARY,DENSE_RANK() OVER
(PARTITION BY DEPARTMENTID
ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES) AS RANKED_EMPLOYEES
WHERE SALARY_RANK = 2;

-- 8
CREATE VIEW EMPLOYEE_SALARY_RANK AS
SELECT EMPLOYEEID,EMPLOYEENAME,
DEPARTMENTID,SALARY,RANK() OVER
(PARTITION BY DEPARTMENTID
ORDER BY SALARY DESC) AS SALARY_RANK
FROM EMPLOYEES;


-- 9
CREATE VIEW MANAGEMENT_SALES_REPORT AS
SELECT C.CUSTOMERIDC.CUSTOMERNAME,
COUNT(DISTINCT O.ORDERID) AS TOTAL_ORDERS,
SUM(O.QUANTITY) AS TOTAL_QUANTITY,
sUM(O.QUANTITY * O.UNITPRICE) AS TOTAL_SALES
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID
WHERE O.STATUS = 'COMPLETED'
GROUP BY C.CUSTOMERID,C.CUSTOMERNAME
HAVING SUM(O.QUANTITY * O.UNITPRICE) > 50000;








-- IMPORTANT INTERVIEW QUESTIONS – SQL VIEWS

-- 1. WHAT IS A VIEW?
-- A VIEW IS A VIRTUAL TABLE THAT DISPLAYS DATA FROM ONE OR MORE TABLES USING A SQL QUERY.

-- 2. WHY DO WE USE VIEWS?
-- WE USE VIEWS TO SIMPLIFY COMPLEX QUERIES, REUSE QUERIES, AND PROVIDE DATA SECURITY BY HIDING UNNECESSARY OR SENSITIVE DATA.

-- 3. WHAT IS THE DIFFERENCE BETWEEN A TABLE AND A VIEW?
-- A TABLE STORES ACTUAL DATA PHYSICALLY IN THE DATABASE. 
-- A VIEW IS A VIRTUAL TABLE THAT DISPLAYS DATA FROM ONE OR MORE TABLES USING A SQL QUERY.

-- 4. WHAT IS THE DIFFERENCE BETWEEN A VIEW AND A STORED PROCEDURE?
-- A VIEW IS MAINLY USED TO DISPLAY OR RETRIEVE DATA AND CAN BE QUERIED LIKE A TABLE.
 -- A STORED PROCEDURE IS A STORED SET OF SQL STATEMENTS USED TO PERFORM OPERATIONS, BUSINESS LOGIC, AND OTHER TASKS.

-- 5. CAN WE INSERT DATA THROUGH A VIEW?
-- YES, DATA CAN BE INSERTED THROUGH SOME VIEWS IF THE VIEW IS UPDATABLE.

-- 6. CAN WE UPDATE DATA THROUGH A VIEW?
-- YES, DATA CAN BE UPDATED THROUGH AN UPDATABLE VIEW. 

-- 7. WHAT IS AN UPDATABLE VIEW?
-- AN UPDATABLE VIEW IS A VIEW THROUGH WHICH WE CAN PERFORM INSERT, UPDATE, OR DELETE OPERATIONS. 
-- SIMPLE VIEWS BASED ON A SINGLE TABLE ARE GENERALLY UPDATABLE.

-- 8. CAN A VIEW CONTAIN JOINS?
-- YES. A VIEW CAN BE CREATED USING JOINS BETWEEN TWO OR MORE TABLES TO DISPLAY RELATED DATA.

-- 9. CAN A VIEW CONTAIN AGGREGATE FUNCTIONS?
-- YES. A VIEW CAN CONTAIN AGGREGATE FUNCTIONS SUCH AS SUM(), AVG(), COUNT(), MAX(), AND MIN().

-- 10. CAN A VIEW CONTAIN GROUP BY?
-- YES. A VIEW CAN USE GROUP BY TO GROUP DATA AND PERFORM AGGREGATE CALCULATIONS.

-- 11. CAN A VIEW CONTAIN A SUBQUERY?
-- YES. A VIEW CAN CONTAIN A SUBQUERY TO FILTER OR CALCULATE DATA.

-- 12. CAN A VIEW CONTAIN A WINDOW FUNCTION?
-- YES A VIEW CAN CONTAIN WINDOW FUNCTIONS SUCH AS ROW_NUMBER(), RANK(), DENSE_RANK(), LEAD(), AND LAG().

-- 13. WHAT HAPPENS TO A VIEW WHEN THE UNDERLYING TABLE IS DELETED?
-- THE VIEW DEFINITION MAY REMAIN IN THE DATABASE, BUT THE VIEW CANNOT BE USED PROPERLY. 
-- QUERYING THE VIEW WILL RESULT IN AN ERROR BECAUSE THE UNDERLYING TABLE NO LONGER EXISTS.

-- 14. HOW DO YOU MODIFY AN EXISTING VIEW?
-- AN EXISTING VIEW CAN BE MODIFIED BY RECREATING OR REPLACING ITS DEFINITION USING CREATE OR REPLACE VIEW, OR BY USING ALTER VIEW.

-- 15. HOW DO YOU DELETE A VIEW?
-- A VIEW CAN BE DELETED USING THE DROP VIEW COMMAND.

-- 16. WHAT ARE THE ADVANTAGES AND DISADVANTAGES OF VIEWS?
-- ADVANTAGES:
-- (1).SIMPLIFIES COMPLEX QUERIES,(2).IMPROVES DATA SECURITY,(3).HIDES UNNECESSARY COLUMNS,
-- (4).MAKES DATA EASIER TO ACCESS.

-- DISADVANTAGES:
-- (1).COMPLEX VIEWS CAN AFFECT PERFORMANCE,(2).SOME VIEWS CANNOT BE UPDATED,
-- (3).COMPLEX OR NESTED VIEWS CAN BE DIFFICULT TO MAINTAIN.

-- 17. HOW CAN VIEWS BE USED FOR DATA SECURITY?
-- VIEWS CAN RESTRICT USERS FROM SEEING SENSITIVE DATA. 
-- FOR EXAMPLE, A VIEW CAN DISPLAY ONLY EMPLOYEE NAME AND DEPARTMENT 
-- WHILE HIDING SALARY, PASSWORD, OR OTHER CONFIDENTIAL INFORMATION. USERS CAN BE GIVEN ACCESS TO THE VIEW INSTEAD OF THE ORIGINAL TABLE.

-- 18. WHAT IS THE DIFFERENCE BETWEEN A VIEW AND A MATERIALIZED VIEW?
-- A NORMAL VIEW USUALLY STORES ONLY THE QUERY DEFINITION AND RETRIEVES THE LATEST DATA FROM THE UNDERLYING TABLES WHEN QUERIED.
-- A MATERIALIZED VIEW STORES THE RESULT OF THE QUERY PHYSICALLY. BECAUSE THE DATA IS STORED, 
-- IT MAY NEED TO BE REFRESHED TO SHOW THE LATEST CHANGES.

-- 19. CAN ONE VIEW BE CREATED USING ANOTHER VIEW?
-- YES. A NEW VIEW CAN BE CREATED BY USING AN EXISTING VIEW AS ITS DATA SOURCE. THIS IS CALLED A NESTED VIEW.

-- 20. IN A REAL-TIME PROJECT, WHEN WOULD YOU PREFER A VIEW OVER A STORED PROCEDURE?
-- I WOULD PREFER A VIEW WHEN I NEED A REUSABLE AND SIMPLIFIED WAY TO RETRIEVE DATA, HIDE SENSITIVE COLUMNS, 
-- SIMPLIFY COMPLEX JOINS, OR PROVIDE A SPECIFIC REPRESENTATION OF DATA.

-- I WOULD PREFER A STORED PROCEDURE WHEN I NEED COMPLEX BUSINESS LOGIC, MULTIPLE SQL OPERATIONS OR TRANSACTION HANDLING.








